### ISSUE TITLE
want <iconv.h> in compatlib

### ISSUE THREAD

**Issue by ehem** [android-ndk/ndk#236] opened 2016-11-14 02:00 UTC
SSIA.  Running on a 64-bit ABI doesn't lessen the need for iconv if you're dealing with a source which _only_ provides UTF-16LE strings.  Only having 3 of 115 files available for 64-bit ABIs isn't too helpful.

**Comment by DanAlbert** [comment] 2016-11-14 21:50
This is somewhat working as intended, but in the future we want to do better. Right now libandroid_support serves one purpose: making libc++ work before L. The reason the LP64 libandroid_support is trimmed down so much is because libandroid_support is fairly unreliable.

Soon we're going to be gutting it and replacing it with the same internals we use in bionic (which are already battle hardened and well tested), and once we've done that it'll match across API levels. More information about this is in our roadmap: https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#NDK-r16-NDK-Compatibility-Library (there's also an earlier section about the shorter term step of making this good enough to replace libandroid_support but not much else).

**Comment by ehem** [comment] 2016-12-03 03:50
I thought the original topic was better.  While _my_ need is iconv support, there is a great deal more functionality in the support library and most of that is missing for 64-bit targets.  I imagine others may need the other functionality and would desire that fixed too.

**Comment by enh** [comment] 2016-12-03 19:15
the only things we're aware of that are in libandroid_support but aren't in current bionic are <monetary.h> (which we have an internal bug to track, even though probably no-one cares) and <iconv.h>. if you know of other gaps, file bugs.

**Comment by fornwall** [comment] 2016-12-03 20:22
@enh How is it with e.g. a function like wcwidth(3):

- [wcwidth() in bionic master](https://android.googlesource.com/platform/bionic.git/+/master/libc/bionic/wctype.cpp#153)
- [wcwidth() in libandroid_support](https://android.googlesource.com/platform/ndk.git/+/master/sources/android/support/src/musl-ctype/wcwidth.c#11)

While it may exist in bionic, it's more of a stub, compared to an actual implementation of it in libandroid_support. Do you consider that (and other similar functions) in scope for an updated compatlib, or will you only want to ship what is in current bionic - the stub function for now?

**Comment by enh** [comment] 2016-12-03 20:33
wcwidth is an interesting example that's pretty poorly defined, and what you want it to return in any of the interesting cases probably depends on your application anyway. (which is one reason why icu4c doesn't have any direct equivalent.)

for anyone who really needs real i18n functionality, we're assuming that exposing actual icu4c API is a far better solution. but if you have a actual use case where the current wcwidth doesn't work, file a bug. (we did recently forward the isw* family to icu4c, even though they're pretty useless in practice too.)

**Comment by DanAlbert** [comment] 2016-12-09 22:01
> for anyone who really needs real i18n functionality, we're assuming that exposing actual icu4c API is a far better solution

This is actually a really interesting question for us. For those of you that are asking for more of these things in `libandroid_support`, is the case here that you really want ICU, but the C library APIs would be close enough? It's actually probably easier for us to do ICU. We have plans for making ICU available in the NDK, but weren't planning on expanding `libandroid_support` for the localization APIs any more than what is needed for libc++ because we were under the impression that they are not terribly useful in comparison to something like ICU.

If we're wrong in that assumption, I think expanding the C library l10n APIs in `libandroid_support` is probably doable (though @enh would certainly know better here).

**Comment by enh** [comment] 2016-12-09 23:56
yeah, we can definitely do either/both. the only reason we've put no effort into the C library i18n stuff (and libc++ too) is that we just don't believe it's useful. no android code (or code in the rest of google) uses it. everything uses icu4c.

but if people come to us with actual examples where the C (or libc++) are genuinely useful, it would make sense for us to fix them (by implementing them in terms of icu4c, so they're always in sync with the better native APIs and the Java APIs too).

**Comment by DanAlbert** [comment] 2016-12-10 00:08
FWIW, "it makes it easier to port `$SOME_LIBRARY` to Android" is also a pretty compelling argument in our opinion.

**Comment by DanAlbert** [comment] 2017-05-05 21:03
Compatibility library got pushed to r16 because O ate all of r15's time.

**Comment by ehem** [comment] 2017-07-14 01:08
Upon trying with r15 I found now neither libc nor libandroid_support have iconv support.  Pulling the iconv support out of libandroid_support really should have happened _after_ it was available somewhere else...

Then I found _both_ libc and libandroid_support include definitions for several of the character set conversion functions. wcslen() wcstomb(), etc.  Bit of a problem with static builds.

**Comment by DanAlbert** [comment] 2017-07-14 02:02
Would ICU work for your needs? We never got an answer to that.

**Comment by ehem** [comment] 2017-07-14 02:17
Pretty likely, I didn't have a very complex need.  I simply needed to convert UTF-16LE to UTF-8 and back. wcstombs() and mbstowcs() appear to be sufficient, but finding appropriate documentation on the zillions of APIs was a bit of a challenge.

I'm pretty sure libandroid_support has a bunch of other functionality which is also disabled in 64-bit mode...

**Comment by DanAlbert** [comment] 2017-07-14 02:50
Wide characters on Android are UTF-32, not UTF-16, so that won't be what you want. There are variants of those functions for converting between explicit UTF types: http://en.cppreference.com/w/c/string/multibyte (c16 is UTF-16, c32 is UTF-32, mb is UTF-8)

I don't think any of those are or have ever been in libandroid_support though.

> I'm pretty sure libandroid_support has a bunch of other functionality which is also disabled in 64-bit mode...

That's intentional. Bundling all the stuff that used to be in the 32-bit libandroid_support into the 64-bit one would have only introduced bugs (libandroid_support is not particularly trustworthy until r16).

The goal of libandroid_support is to fill in the gaps that are needed for libc++ to work.  For a while we'd planned on expanding this to backport as much as possible, but every time we bring it up, no one seems interested. Given that it makes your APK larger, which seems to be the most important issue for everyone, we don't think that's the route we'll be going any more.

Given that *you* are interested in this though, we should probably explore making some pieces of libc a bit more modular and publishing them as cdep modules (the various character conversion APIs are very self contained, so those ones would be easy to do).

**Comment by ehem** [comment] 2017-07-15 04:38
Those may not have ever been in libandroid_support, but they do appear to be in libc for the appropriate Android versions.  The documentation for working with multi-byte character strings in C is problematic in places...

**Comment by DanAlbert** [comment] 2017-07-25 23:13
Given feedback on https://github.com/android-ndk/ndk/issues/440, I'm moving anything that would expand the compatlib into the unplanned bucket. I think for this one we probably will want to make *some* library available to handle this sort of thing, but it won't be part of the compatlib, and likely won't be iconv specifically (more likely icu4c).

**Comment by enh** [comment] 2017-07-28 21:43
wcwidth via icu4c in bionic: https://android-review.googlesource.com/446350

**Comment by DanAlbert** [comment] 2018-10-19 03:43
Closing out support lib bugs since we're not going down that route any more.

**Closed by DanAlbert** 2018-10-19 03:43 UTC
Labels: compatlib
