### ISSUE TITLE
atof linker error with armeabi

### ISSUE THREAD

**Issue by isuPatches** [android-ndk/ndk#315] opened 2017-03-05 00:30 UTC
#### Description

atof linker error with armeabi.

I noticed while using 3.2.4 version of FFMPEG that atof has an undefined reference.  As a work around I branched FFMPEG and changed atof to strtod(pointer, NULL).

```
error: undefined reference to 'atof'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Same details should be found here:
http://stackoverflow.com/questions/42601696/ffmpeg-with-android-sdks-16-25-and-ndk-14-atof-error

#### Environment Details

* NDK Version: 14.0.3770861
* Build sytem: ndk-build
* Host OS: Mac
* Compiler:  Clang
* ABI: armeabi
* STL: ??  (Sorry...I should know this but I don't)
* NDK API level: 16
* Device API level: 16 and 19

**Comment by DanAlbert** [comment] 2017-03-07 22:55
I'm not able to reproduce this. Here's what I tried: https://gist.github.com/DanAlbert/edae02a0f432e186f60c2b9f852ae303

```bash
$ android-ndk-r14/ndk-build -B
[armeabi] Compile++ thumb: foo <= foo.cpp
[armeabi] StaticLibrary  : libstdc++.a
[armeabi] Executable     : foo
[armeabi] Install        : foo => libs/armeabi/foo
$ android-ndk-r14/ndk-build -B APP_UNIFIED_HEADERS=true
[armeabi] Compile++ thumb: foo <= foo.cpp
[armeabi] StaticLibrary  : libstdc++.a
[armeabi] Executable     : foo
[armeabi] Install        : foo => libs/armeabi/foo
$ android-ndk-r14/ndk-build -B APP_STL=c++_static
[armeabi] Compile++ thumb: foo <= foo.cpp
[armeabi] Executable     : foo
[armeabi] Install        : foo => libs/armeabi/foo
$ android-ndk-r14/ndk-build -B APP_UNIFIED_HEADERS=true APP_STL=gnustl_static
[armeabi] Compile++ thumb: foo <= foo.cpp
[armeabi] Executable     : foo
[armeabi] Install        : foo => libs/armeabi/foo
$ android-ndk-r14/ndk-build -B APP_STL=c++_static
[armeabi] Compile++ thumb: foo <= foo.cpp
[armeabi] Executable     : foo
[armeabi] Install        : foo => libs/armeabi/foo
$ android-ndk-r14/ndk-build -B APP_UNIFIED_HEADERS=true APP_STL=gnustl_static
[armeabi] Compile++ thumb: foo <= foo.cpp
[armeabi] Executable     : foo
[armeabi] Install        : foo => libs/armeabi/foo
```

Based on the stackoverflow post, I do have another theory. Is the ffmpeg build perhaps building some other library against a higher platform level and then linking that into the thing you're building against android-16? This might be a case of the first bullet point under https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#Using-Mismatched-Prebuilt-Libraries

> If your target API level is android-9, but you‘re using a prebuilt library that was built against android-16, the resulting app’s minimum API level is android-16. **Failure to adhere to this will be visible at build time if the prebuilt library is static, but may not appear until run time for prebuilt shared libraries.**

**Comment by DanAlbert** [comment] 2017-03-13 18:42
Ping? I'd like to get a fix for this into r14b, but I can't do that without a repro case.

**Comment by isuPatches** [comment] 2017-03-14 01:49
@DanAlbert Sorry for the delay...I'm seeing if I can reproduce locally and getting a test app set up with non-sensitive information that's the shortest path to reproduce...I'll hopefully have something before tomorrow morning for you.

**Comment by isuPatches** [comment] 2017-03-14 03:29
@DanAlbert I've tried FFMPEG v3.2.4 built against both SDK and 24 and SDK 16...what I have boiled it down to is have a c file I have in jni/h264 that reproduces the issue:

```
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libswscale/swscale.h>

int main(int argc, char *argv[]){
  av_register_all();
  return 0;
}

#ifdef __cplusplus
}
#endif
```
and ffmpeg in /jni/h264/ffmpeg/build/<ARCHITECTURE>.

I did not see the issue until I called av_register_all().  Before then I could build as normal.  Even when I did:

```
int main(int argc, char *argv[]){
  printf("%lf\n", atof(argv[1]));
  return 0;
}  
```

It's a really bizarre issue. 

```
APP_ABI := arm64-v8a armeabi armeabi-v7a x86 x86_64
APP_PLATFORM := android-16
APP_STL := gnustl_stati
```
 
What other details would you need?

**Comment by DanAlbert** [comment] 2017-03-14 04:20
Are you building a pure upstream ffmpeg? Last time I looked they didn't have Android.mk files in the project so I'd need to know how you're building this.

If you can, the easiest thing would be for you to upload a test case, but I understand if you can't if the source is confidential.

**Comment by alexcohn** [comment] 2017-03-14 10:56
How did you build your **ffmpeg** libraries? Maybe they were compiled for SDK 21, which does have **atof()** in **libc**. Now when you link your C file with these libraries, you need **atof**! But you build it with SDK 16, where **atof** was defined `inline` in **stdlib.h**.

Make sure that your **ffmpeg** libraries are built against NDK headers of SDK 16.

**Comment by enh** [comment] 2017-05-30 22:21
closing for lack of needed info.

**Closed by enh** 2017-05-30 22:21 UTC
Labels: needs-info

**Comment by DanAlbert** [comment] 2017-05-30 22:27
Alex's guess sounds pretty likely to me anyway, and that's the expected behavior until we get the compatlib in place.
