### ISSUE TITLE
clang from r11c crashes when compiling Firefox for Android

### ISSUE THREAD

**Issue by froydnj** [android-ndk/ndk#114] opened 2016-06-06 18:24 UTC
The attached zip file contains a preprocessed source file and shell script (the same files clang indicates should be included when filing a bug, zipped so Github will accept them) for demonstrating a crash we have seen when compiling with the r11c NDK.  We have observed a similar problem when using the r11b NDK.

The error message is:

```
fatal error: error in backend: Cannot select: 0x120e3420: i32 = truncate 0x13af1ea0 [ORD=18] [ID=70]/opt/build/froydnj/build-android/dist/include/js/Conversions.h:410:5
  0x13af1ea0: f64,ch = CopyFromReg 0x1089d440, 0x141ddf48 [ORD=18] [ID=59]/opt/build/froydnj/build-android/dist/include/js/Conversions.h:410:5
    0x141ddf48: f64 = Register %vreg19 [ID=32]
In function: _ZN7mozilla3dom24CanvasRenderingContext2D12GetImageDataEP9JSContextddddRNS_11ErrorResultE
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 3.8.243773
Target: armv5te-none-linux-android-eabi
Thread model: posix
clang++: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/Unified_cpp_dom_canvas0-796ddf.cpp
clang++: note: diagnostic msg: /tmp/Unified_cpp_dom_canvas0-796ddf.sh
clang++: note: diagnostic msg:

********************
```

[clang-crasher.zip](https://github.com/android-ndk/ndk/files/301057/clang-crasher.zip)

I assume that filing the bug here is better than filing it at llvm.org.

**Comment by enh** [comment] 2016-06-06 20:33
can you reproduce this with r12 (https://github.com/android-ndk/ndk/wiki)?

**Comment by froydnj** [comment] 2016-06-06 21:00
> can you reproduce this with r12 (https://github.com/android-ndk/ndk/wiki)?

Yes.  The shell script output (after removing `-g`, which apparently isn't supported by the driver anymore?) is:

```
fatal error: error in backend: Cannot select: 0x165d0a60: i32 = truncate 0x16484610
  0x16484610: f64,ch = CopyFromReg 0x1632c770, Register:f64 %vreg19
    0x164e2b40: f64 = Register %vreg19
In function: _ZN7mozilla3dom24CanvasRenderingContext2D12GetImageDataEP9JSContextddddRNS_11ErrorResultE
```

**Comment by DanAlbert** [comment] 2016-06-10 17:36
Could you provide us with instructions on building Firefox with the NDK? When I tried a few months ago it didn't even work with r10e, but we'd love to use that as a test before we ship the NDK.

**Comment by froydnj** [comment] 2016-06-14 07:56
Assuming you have the source code (https://hg.mozilla.org/mozilla-central/), you should be able to create a `.mozconfig` file at the top of the source checkout that contains:

```
# Build Firefox for Android:
ac_add_options --enable-application=mobile/android
ac_add_options --target=arm-linux-androideabi

# With the following Android SDK and NDK:
ac_add_options --with-android-sdk="/absolute/path/to/android-sdk"
ac_add_options --with-android-ndk="/absolute/path/to/android-ndk-r10e

# With the following version of things:
ac_add_options --with-android-gnu-compiler-version=4.9
ac_add_options --with-android-version=9

# Optional bits if you want to compile with clang:
clang_path="/absolute/path/to/clang/bin"
export CC="${clang_path}/clang"
export CXX="${clang_path}/clang++"
```

modifying the paths to the SDK, NDK, and clang appropriately.  r10e or r11 should work, though obviously only with GCC.  I've been writing various patches to make things work with clang, so clang should be usable to build things; I think all the patches for clang issues should be landed this week, so modulo the clang crashes, things should Just Work.

Since r12 moved some things around (moving the Thumb libraries to where the ARM ones were and changing what needs to be linked for `libc++` support, maybe a few other things?), the current code won't build with r12.  I'll try to get that fixed this week or the next.

**Comment by DanAlbert** [comment] 2016-06-14 18:06
Great, thanks. I'll definitely find some time to work that into our testing for r13.

Let me know what you find when switching to r12. It'd be a really valuable test for us so I'm happy to help where I can.

**Comment by DanAlbert** [comment] 2016-06-28 22:53
@froydnj: I found some time to try building firefox against r12b, and I was able to produce a successful build (any instructions you can provide on running a test suite?).

It did require some tweaking to `build/autoconf/android.m4` to update paths to libc++ libraries and whatnot. How does Firefox typically handle things that vary from one NDK release to the next? Is it just assumed that Firefox is only built with r11b (I saw that downloaded when I ran `./mach bootstrap`), or is there some way I can submit a patch with version checks when I find things like this? Patch is below:

```diff
diff --git a/build/autoconf/android.m4 b/build/autoconf/android.m4
--- a/build/autoconf/android.m4
+++ b/build/autoconf/android.m4
@@ -95,9 +95,6 @@ AC_DEFUN([MOZ_ANDROID_STLPORT],
 
 if test "$OS_TARGET" = "Android"; then
     cpu_arch_dir="$ANDROID_CPU_ARCH"
-    if test "$MOZ_THUMB2" = 1; then
-        cpu_arch_dir="$cpu_arch_dir/thumb"
-    fi
 
     if test -z "$STLPORT_CPPFLAGS$STLPORT_LIBS"; then
         case "$android_cxx_stl" in
@@ -124,11 +121,11 @@ if test "$OS_TARGET" = "Android"; then
             cxxabi_base="$ndk_base/llvm-libc++abi"
             cxxabi_include="$cxxabi_base/libcxxabi/include"
 
-            if ! test -e "$cxx_libs/libc++_static.a"; then
+            if ! test -e "$cxx_libs/libc++.a"; then
                 AC_MSG_ERROR([Couldn't find path to llvm-libc++ in the android ndk])
             fi
 
-            STLPORT_LIBS="-L$cxx_libs -lc++_static"
+            STLPORT_LIBS="-L$cxx_libs -Bstatic -lc++ -Bdynamic"
             # Add android/support/include/ for prototyping long double math
             # functions, locale-specific C library functions, multibyte support,
             # etc.
```

**Comment by froydnj** [comment] 2016-06-29 16:24
@DanAlbert: cool, thanks for looking into this.  I committed a very similar patch yesterday:

https://hg.mozilla.org/mozilla-central/rev/08f48f6431b9

which works for me locally with an r12(a) NDK.

As for testing, assuming that you built with `./mach build`, you should be able to run `./mach package && ./mach install`.  `./mach package` builds the actual APK, while `./mach install` installs is on an available device.  If you have a device plugged in, `./mach install` will install to that device; otherwise, it ought to prompt you to start the emulator and install the APK in the emulator.

After that, something like `./mach cppunittest` will run some basic C++ tests; these take ~1 hour to run on our infrastructure.  We have more complete tests, but those take quite a bit longer to run (and we parallelize them by running slices of the tests simultaneously, which is a bit impractical to do locally).

**Comment by DanAlbert** [comment] 2016-06-30 22:49
> which works for me locally with an r12(a) NDK.

That's with GCC, or with Clang? There was a Clang update in r12 so it's possible we've gotten past the crash issue with that.

I'll check myself in a bit if I don't hear back. Poking around with an r13 build atm.

**Comment by DanAlbert** [comment] 2017-01-04 22:00
Not actually sure if this is still happening, but at any rate we can't get another Clang update for r14 (we maybe could, but it wouldn't be a good idea).

**Comment by enh** [comment] 2017-05-30 22:24
closing for lack of needed info.

**Closed by enh** 2017-05-30 22:24 UTC
Labels: clang, needs-info

**Comment by DanAlbert** [comment] 2017-05-30 22:25
@froydnj: Have you had a chance to look at Firefox with clang again? It's been a while since I've tried.

**Comment by froydnj** [comment] 2017-06-05 21:03
> Have you had a chance to look at Firefox with clang again? It's been a while since I've tried.

I haven't tried, because it doesn't seem worth it until there's some movement on #133.
