### ISSUE TITLE
internal compiler error when build Firfox / aarch64 with NDK r17b

### ISSUE THREAD

**Issue by makotokato** [android-ndk/ndk#732] opened 2018-07-02 09:59 UTC
#### Description

When building Firefox/aarch64 using NDK r17b, the following internal error always occurs.
```
#0 0x00000000014b9f84 (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x14b9f84)
#1 0x00000000014ba1b6 (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x14ba1b6)
#2 0x00007fdc4977cf50 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11f50)
#3 0x0000000000f74a10 (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0xf74a10)
#4 0x0000000000f72304 (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0xf72304)
#5 0x0000000000e6389a llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0xe6389a)
#6 0x00000000010fea7b llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x10fea7b)
#7 0x00000000010fece3 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x10fece3)
#8 0x00000000010ff164 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x10ff164)
#9 0x0000000001616432 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1616432)
#10 0x0000000001cad14c (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1cad14c)
#11 0x000000000213a7f6 clang::ParseAST(clang::Sema&, bool, bool) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x213a7f6)
#12 0x00000000019c4a5b clang::FrontendAction::Execute() (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x19c4a5b)
#13 0x0000000001972738 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1972738)
#14 0x0000000001a48cc4 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1a48cc4)
#15 0x00000000007b7db6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x7b7db6)
#16 0x00000000007b3f6d main (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x7b3f6d)
#17 0x00007fdc482daa87 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21a87)
#18 0x00000000007b30b2 _start (/home/mkato/.mozbuild/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x7b30b2)
```
```
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'Unified_cpp_js_src15-853206.cpp'.
4.      Running pass 'Machine Loop Invariant Code Motion' on function '@_ZN2js3jit22CacheRegisterAllocator20saveIonLiveRegistersERNS0_14MacroAssemblerENS0_7LiveSetINS0_11RegisterSetEEENS0_8RegisterEPNS0_9IonScriptE'
Segmentation fault
```
Sample (*.cpp + *.sh by clang) is attached as sample.zip
[sample.zip](https://github.com/android-ndk/ndk/files/2154715/sample.zip)

#### Environment Details
* NDK Version: r17b
* Build system: standalone toolchain
* Host OS: Linux (Debian/sid)
* Compiler: clang
* ABI: armv8-a
* NDK API level: 21
* Device API level: 21

**Comment by makotokato** [comment] 2018-07-02 10:08
When not using -O2 or -O3, this works well.

**Comment by pirama-arumuga-nainar** [comment] 2018-07-02 18:56
This does not happen in the latest Clang, which is slated for r18.
```
PASS clang-r328903 (based on r328903) <-- will be in r18?
PASS clang-4679922 (based on r326829) <-- not in any NDK
FAIL clang-4691093 (based on r316199) <-- in r17b
PASS clang-4053586 (based on r300080) <-- in r16?
```
My guess is that this was a regression that's since been fixed (rather than a bug being exposed and hidden).

Marking this closed assuming the compiler above will be released in r18.  @DanAlbert please re-open if that's not the case.

**Closed** 2018-07-02 19:10 UTC
