### ISSUE TITLE
Missing symbol __ctype_get_mb_cur_max in C libraries with android r16b1

### ISSUE THREAD

**Issue by tru** [android-ndk/ndk#544] opened 2017-10-13 07:27 UTC
#### Description

We build several libraries with the NDK for our app including iconv. With r16b1 we noticed that iconv fails to link on armv7 and i686 targeting API level 16 with the following error:

`error: undefined reference to '__ctype_get_mb_cur_max'`

After looking around it seems like this symbol is only in `libandroid_support.a` and in order to link to that one you also need to link to `libc++` (otherwise you get a error saying that new and delete is missing) which seems a bit wrong considering libiconv is a plain C library.

Not sure if there is any downsides to link to android_support and c++ in all our libraries but it works as a workaround for now.

#### Environment Details

* NDK Version: r16-beta1
* Build system: standalone toolchain, conan.io, cmake, autoconf
* Host OS: Linux ubuntu 16.04
* Compiler: Clang 4.0.1 from llvm.org
* ABI:
* STL: libc++
* NDK API level: 16
* Device API level:

**Comment by DanAlbert** [comment] 2017-10-13 07:34
If you were getting that error *before* you started using libc++, I'm fairly certain something went wrong in your build. Presumably you did build against the libc++/libandroid_support headers but didn't link it and that's where the reference came from.

**Comment by tru** [comment] 2017-10-13 07:44
Hmm - interesting. I don't rule out that we are doing anything wrong here at all. We have a bit of a special setup considering we are using clang from llvm.org instead of the included one, we do this to guarantee we are using the same compiler on all our platforms. I then construct a CFLAGS / LDFLAGS that looks something like this:

```
CFLAGS=fPIC -DPIC -march=armv7-a -Os -D__ANDROID_API__=16 --sysroot=<standalone toolchain>/sysroot --target=arm-linux-androideabi --gcc-toolchain=<standalone toolchain>

LDFLAGS=-fuse-ld=gold --sysroot=<standalone toolchain>/sysroot --target=arm-linux-androideabi --gcc-toolchain=<standalone toolchain>

CXXFLAGS=-fPIC -DPIC -std=gnu++98 -D_GLIBCXX_USE_CXX11_ABI=0 -march=armv7-a -Os -D__ANDROID_API__=16 --sysroot=<standalone toolchain>/sysroot --target=arm-linux-androideabi --gcc-toolchain=<standalone toolchain>
```

Where are the libc++/libandroid_support headers located in the standalone toolchain? Would a standard clang pick them out differently than the bundled one in the NDK?

**Comment by DanAlbert** [comment] 2017-10-13 07:46
How did you generate your standalone toolchain? If it contains libc++, the libandroid_support headers are installed to the sysroot alongside the normal C library headers (in usr/*local*/include rather than usr/include though).

**Comment by tru** [comment] 2017-10-13 07:52
`make_standalone_toolchain.py --arch=armv7 --api=16 --stl=libc++ --install-dir=<path>`

Hmm that's interesting I wonder if something makes the search path pick those includes over the others - could even be configure that does funny things there. I could try to reproduce the problem with a stock libiconv just setting the environments above outside our build scripts if that would be helpful.

**Comment by tru** [comment] 2017-10-13 07:55
Oh I saw your comment about `--sysroot` now. So is the fix to not pass sysroot by `-isystem` for CFLAGS instead?

**Comment by DanAlbert** [comment] 2017-10-13 07:59
> I wonder if something makes the search path pick those includes over the others

That's by design. libandroid_support fills in gaps in libc, so it needs to be able to override the libc headers. usr/local/include is prefered over usr/include, so the libandroid_support headers are preferred.

> So is the fix to not pass sysroot by -isystem for CFLAGS instead?

That would be one fix. I assume this problem is only happening for C code? For C++ it should be linking libc++ which is actually a linker script that also include libandroid_support and then you should have no issues. For C code, though, it will have those headers included but won't link libc++, and then you can run in to issues.

Whether or not that is the case for you, that is a bug I've just realized exists :)

**Comment by tru** [comment] 2017-10-13 08:13
No that seems exactly like the problem I have. C++ libs seems just fine but C libs have the problem of getting symbols from the headers in the support lib.

I might just end up with just adding `-lc++` to LDFLAGS. Btw, is that correct or should it be `lc++_shared`? Will that pull in android_support without explicitly linking to it?

**Comment by DanAlbert** [comment] 2017-10-13 08:25
Option 1: skip libandroid_support for C code using `-isystem` instead of `--sysroot`.

I *think* this is the behavior you'd get from ndk-build (I can confirm tomorrow when I'm back at a computer).

If you're planning to drop libandroid_support from C builds once I've fixed this bug, I'd take this option. Like I said, libandroid_support fills in APIs that were missing in older API levels. If you go to remove your workaround, you don't want to find that you've been depending on APIs that came from libandroid_support, not libc.

Option 2: link libc++ into C code.
Using libandroid_support does increase the size, if your binaries since it statically links implementations of APIs that were not available in ICS (regardless of your actual target API level). libc++ also causes code size increases compared to not linking any STL (some pieces of it are used in libandroid_supporr, so it can't be stripped entirely).

The nice part of this option is that you do get some additional APIs that wouldn't be available in old releases (not a ton, mostly wide char stuff, and the implementation isn't particularly efficient) and some bug fixes (we patch a few functions, mostly things in libm iirc).

**Comment by DanAlbert** [comment] 2018-02-23 00:26
Turns out we don't need this decl in libandroid_support any more: https://android-review.googlesource.com/#/c/platform/ndk/+/625227

Should fix your problem. I was able to use a standalone toolchain to link a C program that used `MB_CUR_MAX` without any issues, which I wasn't able to do before this change.

**Comment by DanAlbert** [comment] 2018-02-23 20:34
Merged into r17.

**Closed by DanAlbert** 2018-02-23 20:34 UTC
Labels: standalone-toolchain

**Comment by epicstar** [comment] 2018-04-30 15:57
@tru, were you able to add `-lc++` in your `LDFLAGS` from the standalone toolchain?

A libc++.so doesn't seem to be present in my install folder which I find awkward.

I'm doing this:

```bash
make_standalone_toolchain.py --arch=armv7 --api=19 --stl=libc++ --install-dir=/tmp/toolchain/arm
```

`find /tmp/toolchain -iname "libc++.so"` gives me this:

```bash
./arm/lib/lib64/libc++.so
./arm/lib64/libc++.so
```

I would have expected `libc++.so` to be in this folder: `./arm/arm-linux-androideabi/lib/armv7-a/`

Running `readelf -h /path/to/libc++.so` on both `libc++.so`'s give me this, which suggest that this isn't the libc++ so's I should be linking against since these are x86-64 binaries and not armv7 binaries:

```
Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          1106400 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         8
  Size of section headers:           64 (bytes)
  Number of section headers:         32
  Section header string table index: 31
``` 

@DanAlbert I'm not sure if I'm doing something wrong or my side or if it is a bug in the standalone toolchain, hence why I'm not creating a ticket yet... However, as a result, I'm unable to add the following to my CXXFLAGS as a result: `-stdlib=libc++`. However, I would expect @tru to have the same issue as I have.

**Comment by DanAlbert** [comment] 2018-04-30 17:26
Don't pass `-lc++`. The standalone toolchain script already handles this for you. For historical reasons the libc++ linker scripts get installed to the standalone toolchain as libstdc++.so and libstdc++.a.

**Comment by epicstar** [comment] 2018-04-30 17:48
I know this is off topic but...

Does this mean I don't have to specify `--stl=libc++`/`-stdlib=libc++` or `-listdc++` when compiling C++ projects with libc++? (I assume `lstdc++` picks up `libstdc++.so` before `libstdc++.a` which is what we will prefer).

**Comment by DanAlbert** [comment] 2018-04-30 18:36
> Does this mean I don't have to specify --stl=libc++/-stdlib=libc++ or -listdc++ when compiling C++ projects with libc++?

More than just don't have to: cannot.

> or -lstdc++

Don't have to. This is implicit (the whole point of standalone toolchains is to avoid needing to pass things like this; `clang++ foo.cpp` Just Works).

> The documentation on the standalone toolchain says that --stl=libc++ needs to be explicitly set.

That's not the same as `-stdlib=libc++`. `--stl=libc++` is a flag passed to `make_standalone_toolchain.py`. `-stdlib=libc++` is a flag you would (but should not, in the case of a standalone toolchain) pass to Clang itself.

**Comment by epicstar** [comment] 2018-04-30 19:06
@DanAlbert thanks for the clarification.

The first option you have here works great, also. Thank you: https://github.com/android-ndk/ndk/issues/544#issuecomment-336385649

I was hoping to use libandroid_support for C libs, but seeing how iconv can't be compiled with it for ANDROID_API's under 21, I think that'll have to wait until NDK17 next month :)

**Comment by DanAlbert** [comment] 2018-04-30 21:14
> If you need me to be a guinea pig for the NDK17 beta, lmk.

More are always helpful. https://groups.google.com/forum/#!topic/android-ndk-announce/rAxMs6ho4zg for info on beta 2, and https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md for info on canary builds if you're feeling particularly adventurous.
