### ISSUE TITLE
clang inserts undefined reference to __mulodi4

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#506] opened 2017-09-04 11:27 UTC
#### Description

Build of **sqlite3.c** for armeabi-v7a with clang fails in NDK r15c: 

    sqlite3.c:function sqlite3MulInt64: error: undefined reference to '__mulodi4'

Here is the _minimal_ command to reproduce this:

    void q(long long qq) {
        __builtin_mul_overflow(qq, qq, &qq);
    }

    clang -arch arm --sysroot $NDK_ROOT/sysroot -c q.c && nm q.o

Note a similar issue in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=503229.
**sqlite3.c** does not use `__builtin_mul_overflow` for CLANG_VERSION under 4000000, hence build succeeds in NDK 14.

#### Environment Details

* NDK Version: **15.2.4203891**
* Build sytem: **ndk-build**
* Host OS: **Mac**
* Compiler: **clang** `version 5.0.300080`
* ABI: **armeabi-v7a**

**Comment by fornwall** [comment] 2017-09-04 11:30
I think https://github.com/android-ndk/ndk/issues/294 is the canonical issue for functions provided by compiler-rt.

**Comment by alexcohn** [comment] 2017-09-04 11:50
@fornwall thanks for the link. It doesn't seem a duplicate though, because my example is 32-bit. Are we really expected to compile [mulodi4.c](https://llvm.org/svn/llvm-project/compiler-rt/branches/release_34/lib/mulodi4.c)?

**Comment by enh** [comment] 2017-09-05 17:25
duplicate of issue #184 .

**Closed by enh** 2017-09-05 17:25 UTC

**Comment by UnaPlugin** [comment] 2017-09-28 08:02
Same question about the **undefined reference to '__mulodi4'** Error

**Comment by dibya001** [comment] 2019-05-09 18:22
Was anyone able to resolve this issue. Still facing the same error.

**Comment by mhsmith** [comment] 2020-01-22 13:49
Fixed in NDK r19, according to #294.
