### ISSUE TITLE
Undefined reference to `__muloti4' when using clang

### ISSUE THREAD

**Issue by fornwall** [android-ndk/ndk#295] opened 2017-02-02 21:55 UTC
When building some things I encounter `undefined reference to __muloti4` when changing from gcc to clang using both NDK r13 and r14-beta2.

I've found the following minimal test case:

```sh
$NDK/build/tools/make_standalone_toolchain.py \
	--api 21 \
	--arch arm64 \
	--install-dir $TOOLCHAIN
export PATH=$TOOLCHAIN/bin:$PATH

curl -O https://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz
tar xf m4-1.4.18.tar.xz
cd m4-1.4.18

export CC=aarch64-linux-android-clang
./configure --host=aarch64-linux-android
make
```

Is this a known issue with some known workaround?

**Comment by DanAlbert** [comment] 2017-02-02 22:00
I just started turning up some similar issues: https://github.com/android-ndk/ndk/issues/294

Going to close this one and track on the other since the problem is fundamentally the same. Thanks for reporting another case of it.

**Closed by DanAlbert** 2017-02-02 22:00 UTC

**Comment by fornwall** [comment] 2017-02-02 22:03
Thanks! Just found https://llvm.org/bugs/show_bug.cgi?id=16404 which confirms that this is due to symbols not in libgcc but in compiler-rt, and can happen either when using `-fsanitize=undefined` or, as in the test case above, `__builtin_mul_overflow`.
