### ISSUE TITLE
Unwanted rpath is being set automatically by Clang when -fopenmp compiler flag is set

### ISSUE THREAD

**Issue by sephirot864** [android-ndk/ndk#797] opened 2018-09-18 10:06 UTC
--------------------------------------------------------------------------------

#### Description
Clang++, which is a part of android-ndk, seems to add -rpath linker flag when -fopenmp compiler flag is set. Path which is being added points to: android-ndk-r17b/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/6.0.2/lib/linux/arm. This folder contains only static libraries. It seems that there is no way to disable this functionality. This also makes impossible to set runpath by yourself. 

For tests I have created file which does nothing (empty main which returns 0) and has no dependencies. The comand used to build (verbose):

`android-ndk-r17b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -target armv7-none-linux-androideabi -gcc-toolchain D:/Programy/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/Programy/android-ndk-r17b/platforms/android-24/arch-arm -fopenmp -LD:/Programy/android-ndk-r17b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a main.cpp -o main -v`

This command produces working binary. The linker command line produced with this command:

`android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\\ld" --sysroot=D:/Programy/android-ndk-r17b/platforms/android-24/arch-arm -X --eh-frame-hdr -m armelf_linux_eabi -dynamic-linker /system/bin/linker -o main "D:/Programy/android-ndk-r17b/platforms/android-24/arch-arm/usr/lib/../lib\\crtbegin_dynamic.o" -LD:/Programy/android-ndk-r17b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a "-LD:\\Programy\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\arm" -LD:/Programy/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/armv7-a -LD:/Programy/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a -LD:/Programy/android-ndk-r17b/platforms/android-24/arch-arm/usr/lib/../lib -LD:/Programy/android-ndk-r17b/platforms/android-24/arch-arm/usr/lib/arm-linux-androideabi/../../lib -LD:/Programy/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/armv7-a -LD:/Programy/android-ndk-r17b/platforms/android-24/arch-arm/usr/lib "C:\\Users\\jblumenf\\AppData\\Local\\Temp\\main-9dc836.o" -lstdc++ -lm -lomp -rpath "D:\\Programy\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\arm" -lgcc -lgcc -ldl -lc -lgcc -lgcc -ldl "D:/Programy/android-ndk-r17b/platforms/android-24/arch-arm/usr/lib/../lib\\crtend_android.o"`

For some reason `-rpath "D:\\Programy\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\arm"` was added. 

The command line could be simplyfied to one which failes but shows the problem:

`android-ndk-r17b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -target armv7-none-linux-androideabi -fopenmp main.cpp -o main -v`

this results in:

`"ld" -X --eh-frame-hdr -m armelf_linux_eabi -dynamic-linker /system/bin/linker -o main crtbegin_dynamic.o "-LD:\\Programy\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\arm" "C:\\Users\\jblumenf\\AppData\\Local\\Temp\\main-b2a26e.o" -lstdc++ -lm -lomp -rpath "D:\\Programy\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\arm" -lgcc -lgcc -ldl -lc -lgcc -lgcc -ldl crtend_android.o`

If -fopenmp flag is removed, rpath is not being set anymore:

`android-ndk-r17b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -target armv7-none-linux-androideabi main.cpp -o main -v`

->

`"ld" -X --eh-frame-hdr -m armelf_linux_eabi -dynamic-linker /system/bin/linker -o main crtbegin_dynamic.o "-LD:\\Programy\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\arm" "C:\\Users\\jblumenf\\AppData\\Local\\Temp\\main-1034a4.o" -lstdc++ -lm -lgcc -lgcc -ldl -lc -lgcc -lgcc -ldl crtend_android.o`

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 17.1.4828580
* Build system: android-ndk-r17b, toolchain - llvm
* Host OS: Windows
* Compiler: Clang 6.0.2

**Comment by pirama-arumuga-nainar** [comment] 2018-09-18 18:52
@sephirot864 This is by design - to allow OpenMP-enabled binaries to find the `libomp.so` that ships with Clang (without having to specify `LD_LIBRARY_PATH`).  It servers a narrow use case where binaries are built and run in the same host (see https://reviews.llvm.org/D30015 for background).

It is not supposed to be added in case of static libraries.  I'll investigate.  In the meantime, you can prevent the addition of `-rpath` by using `-fno-rtlib-add-rpath`.

**Comment by DanAlbert** [comment] 2018-09-18 19:48
@pirama-arumuga-nainar: not emitting that argument if host triple != target triple would probably be a good change too.

**Comment by pirama-arumuga-nainar** [comment] 2018-09-18 19:51
@DanAlbert  I don't think it's that simple.  There may be multiple (slightly) different triples that can run on a host (i386-linux, i686-linux, for e.g.).  But it's definitely worth a second look and trimming the cases where this gets added.

**Comment by sephirot864** [comment] 2018-09-19 09:41
@pirama-arumuga-nainar It seems like `-fno-rtlib-add-rpath` flag has no effect:
`D:/Programy/android-ndk-r17b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -target armv7-none-linux-androideabi -fno-rtlib-add-rpath -fopenmp -static main.cpp -o main -v`

->

` "ld" -X --eh-frame-hdr -m armelf_linux_eabi -Bstatic -o main crtbegin_static.o "-LD:\\Programy\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\arm" "C:\\Users\\jblumenf\\AppData\\Local\\Temp\\main-30b8a9.o" -lstdc++ -lm --start-group -lomp -rpath "D:\\Programy\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\arm" -lgcc -lgcc -lc --end-group crtend_android.o`

**Comment by pirama-arumuga-nainar** [comment] 2018-09-19 21:17
@sephirot864 My bad - this flag didn't do anything when I first set it up and was fixed only recently: https://reviews.llvm.org/D45145.  It should be fixed the next time Clang is updated in the NDK.

**Comment by pirama-arumuga-nainar** [comment] 2018-09-19 21:18
> the next time Clang is updated in the NDK.

after r18, that is.  r18's Clang still doesn't have the fix.

**Comment by sephirot864** [comment] 2018-09-19 21:37
Then we'll have to wait for the update. Thank you for your response.

**Comment by DanAlbert** [comment] 2018-09-19 21:53
I'm going to keep this open until we actually get the fix. r19 doesn't have the new Clang yet.

**Comment by DanAlbert** [comment] 2018-09-19 21:54
(we should also see what we can do to make sure this is the default when appropriate)

**Comment by DanAlbert** [comment] 2018-10-17 19:58
Confirmed fixed in r19.

**Closed by DanAlbert** 2018-10-17 19:58 UTC
Labels: clang
