### ISSUE TITLE
mmap no define in sysroot when __USE_FILE_OFFSET64 define and android api < 21

### ISSUE THREAD

**Issue by owen200008** [android-ndk/ndk#512] opened 2017-09-08 07:05 UTC
Pkg.Desc = Android NDK Pkg.Revision = 15.2.4203891
mmap no define in sysroot->usr->include->sys->mman.h
when __USE_FILE_OFFSET64 define and android api < 21

**Comment by owen200008** [comment] 2017-09-08 07:06
low ndk version is success. update to 15 it compile fail.

**Comment by enh** [comment] 2017-09-08 17:43
duplicate of #477

**Closed by enh** 2017-09-08 17:43 UTC
