### ISSUE TITLE
Undefined reference error

### ISSUE THREAD

**Issue by SanjithKanagavel** [android-ndk/ndk#175] opened 2016-08-04 06:13 UTC
error: undefined reference to '__cxa_bad_typeid'
error: undefined reference to '__cxa_bad_cast'
error: relocation overflow in R_ARM_THM_CALL

I am using ndk-r12b. Facing this issue. Undefined reference references everywhere. Can you please help me sir ?

**Comment by DanAlbert** [comment] 2016-08-04 17:02
Are you sure you're using r12b? https://github.com/android-ndk/ndk/issues/140

If you are in fact on r12b and not r12, I'm going to need more information since it's going to be a different root cause than the bug I linked.

**Comment by enh** [comment] 2016-12-24 17:20
closing for lack of needed info.

**Closed by enh** 2016-12-24 17:20 UTC
Labels: needs-info

**Comment by ivan-ushakov** [comment] 2017-05-27 08:21
Hello,

I faced with same problem.

    05-27 10:59:12.777 1527-1527/com... W/linker: /data/app/com...-1/lib/arm64/lib...so: unused DT entry: type 0xf arg 0x45291f
    05-27 10:59:12.822 1527-1527/com... D/AndroidRuntime: Shutting down VM
    05-27 10:59:12.823 1527-1527/com... E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.lunarkey.monerotest, PID: 1527
                                                          java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/app/com....-1/lib/arm64/lib...so"...
                                                                at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                                at java.lang.System.loadLibrary(System.java:1562)

NDK: android-ndk-r14-beta1-linux-x86_64.zip
Standalone toolchain: make_standalone_toolchain.py --api 21 --stl=libc++ --arch arm64
Target architecture: armv8-a
Build tool: cmake
Build type: debug
Test device: Nexus 5X (Android 7.1.2)

If I set build type to release then I can run app but it crashes. So idea was to build debug version for more details about crash but unfortunately I can't run debug version of library.

**Comment by SanjithKanagavel** [comment] 2017-05-30 06:05
Sorry this issue is fixed. Thanks.

**Comment by sushil-lakra** [comment] 2018-09-02 07:26
Hi, How did  you solve the problem, I am facing same issue.
