### ISSUE TITLE
Incorrectly choosing 64 bit function signatures.

### ISSUE THREAD

**Issue by gpx1000** [android-ndk/ndk#364] opened 2017-04-11 19:01 UTC
The latest beta NDK seems to chose ftello64 and fseeko64 when building a armeabi-v7a making the clang link step fail with an undefined reference.
To repo this, attempt to build minizip as a static lib with clang then link that static lib anywhere.  Observe that it works with ndk 14 (stable) but fails with 15.0.3869509 RC1

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15.0.3869609-beta1
* Build sytem: cmake
* Host OS: Windows
* Compiler: clang
* ABI: armeabi-v7a
* STL: c++_static/c++_shared
* NDK API level: 23
* Device API level: 24

**Comment by enh** [comment] 2017-04-11 19:59
are you sure you didn't define _FILE_OFFSET_BITS=64? we'll need a reproduceable test case...

**Comment by DanAlbert** [comment] 2017-04-17 20:12
Assuming this is the `_FILE_OFFSET_BITS=64` issue, we've actually already fixed this in bionic, it just hasn't made it to the NDK. If that's the case, you can still use the deprecated headers in r15 beta 1 to avoid  this problem. https://android.googlesource.com/platform/ndk/+/master/docs/UnifiedHeaders.md#Using-Unified-Headers will tell you how.

We'll have that problem fixed in beta 2, at which point you'll definitely want to give the new headers another shot because the old headers will be going away in r16.

**Comment by gpx1000** [comment] 2017-04-17 21:53
Confirmed that the Unified headers causes this bug in Beta 1.

**Comment by alexcohn** [comment] 2017-04-24 15:11
FWIW, we do use minizip and our fix was to modify [one line](https://github.com/madler/zlib/blob/master/contrib/minizip/ioapi.h#L24): 

    -#if (!defined(_WIN32)) && (!defined(WIN32)) && (!defined(__APPLE__))
    +#if (!defined(_WIN32)) && (!defined(WIN32)) && (!defined(__APPLE__)) && (!defined(ANDROID))

**Comment by gpx1000** [comment] 2017-04-24 18:22
@alexcohn thanks for the tip.  That does look like a decent change to solve the same problem.  I doubt we'd have a need to unzip a file that's larger than 4gigs so it should be valid in all usecases.
That said, I'm opting for avoiding making a custom change to a multi-project dependent library and instead turning off unified headers until r16 is released.

**Comment by DanAlbert** [comment] 2017-05-05 20:52
We've merged the latest headers into r15.

**Closed by DanAlbert** 2017-05-05 20:52 UTC
