### ISSUE TITLE
ev-compile-cpp-source regression in r14 beta 2

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#302] opened 2017-02-20 14:37 UTC
#### Description

Same C++ code (**boost 1.63**'s **asio/detail/impl/epoll_reactor.ipp**) compiles in r13, but fails in r14β2. I could trace the change back to file `definitions.mk`, scrips `ev-compile-cpp-source` and her kin. In r13, the `_FLAGS` end with

    -isystem $$(call host-path,$$(SYSROOT_INC)/usr/include) \

While in r14, this has changed to

    --sysroot $$(call host-path,$$(SYSROOT_INC)) \
    $(SYSROOT_ARCH_INC_ARG) \

Now if we call `ndk-build` with `APP_UNIFIED_HEADERS=true`, the compile command ends with 

    --sysroot <ndk-root>/sysroot -isystem <ndk-root>/sysroot/usr/include/i686-linux-android

and the result is:

    <path>/boost/asio/detail/impl/epoll_reactor.ipp: In static member function 'static int boost::asio::detail::epoll_reactor::do_epoll_create()':
    <path>/boost/asio/detail/impl/epoll_reactor.ipp:463:39: error: 'epoll_create1' was not declared in this scope
      int fd = epoll_create1(EPOLL_CLOEXEC);

If I use `ndk-build` with `APP_UNIFIED_HEADERS=false`, the compile command line does not contain `-isystem` at all, with equally unpleasant result:

    <path>/boost/asio/impl/serial_port_base.ipp: In member function 'boost::system::error_code boost::asio::serial_port_base::baud_rate::store(termios&, boost::system::error_code&) const':
    <path>/boost/asio/impl/serial_port_base.ipp:118:3: error: '::cfsetspeed' has not been declared
      ::cfsetspeed(&storage, baud);

#### Environment Details

* NDK Version: 14.0.3675639-beta2.
* Build sytem: ndk-build
* Host OS: Mac
* Compiler: GCC; clang does not provide a workaround for https://github.com/android-ndk/ndk/issues/297
* ABI: x86
* STL: c++_shared (but switching to gnustl does not resolve the issue)
* NDK API level: 14
* Device API level: *not applicable*

**Comment by enh** [comment] 2017-02-20 17:47
epoll_create1 and cfsetspeed were both introduced in API level 21, so it's expected that they wouldn't be visible at 14...

**Comment by alexcohn** [comment] 2017-02-20 22:47
but boost can use `cfsetinspeed()` instead, if configured correctly. It knows not to use `epoll_create1()`, too. The fact is that with GCC and r13 compilation succeeds without tuning.

**Comment by DanAlbert** [comment] 2017-02-21 19:12
https://github.com/boostorg/asio/blob/develop/include/boost/asio/detail/impl/epoll_reactor.ipp#L462

We didn't used to have `EPOLL_CLOEXEC`. That seems like the wrong way to check if `epoll_create1` is available (presumably boost has some "is this function available?" configure mechanism?). imo this is a bug in boost.

https://github.com/boostorg/asio/blob/develop/include/boost/asio/impl/serial_port_base.ipp#L117

The `cfsetspeed` is used instead of `cfsetispeed` `#if defined(_BSD_SOURCE)`. This also looks like a fragile feature test. `_BSD_SOURCE` is the way to tell the C library that you want the extensions hidden by it, not the way for the C library to indicate that it actually has *all* that functionality.

**Comment by alexcohn** [comment] 2017-02-22 12:59
@DanAlbert I agree that in both cases boost did not do their best to protect against hostile build environment. They don't have `./configure` or other mechanisms to check which functions are available in the **libc**, and I believe this their conscious approach, and they rely on the toolchain headers to be consistent. 

I think that both cases can be safely resolved without changing **boost** code, and being a regression in the r14 *beta*, don't justify filing bug reports at https://svn.boost.org/trac/boost/newticket.

Regarding **EPOLL_CLOEXEC**: I believe that `#if __ANDROID_API__ >= 21` in both `linux/eventpoll.h` and `sys/epoll.h` will not do any harm to NDK users. Even if presence of `#define EPOLL_CLOEXEC O_CLOEXEC` is not a strong evidence that `epoll_create1()` is available, its absence definitely is a strong enough evidence that a workaround `epoll_create1()` should be used.

As for **cfsetspeed()**, I believe that NDK r13 compiled our code *'by lucky chance'*. It so happens that with `-isystem`, we get `platforms/android-14/arch-x86/usr/include/asm/posix_types.h` included, but not `toolchains/x86-4.9/prebuilt/darwin-x86_64/lib/gcc/i686-linux-android/4.9.x/include-fixed/asm/posix_types.h`, which happens to include `platforms/android-14/features.h` which defines **`_BSD_SOURCE`**.

Now the things get weird. In unified headers, **`_BSD_SOURCE`** is not defined, and left to be defined by the user. This is a breaking change from the older behavior, and I am sure some code will not compile anymore. IMHO, this is a legitimate change, but it should be explicitly documented in the changelog.

On the other hand, on Android platform 21 and higher, **cfsetspeed()** is defined, and **boost** will be OK with it, regardless whether `_BSD_SOURCE` is defined or not.

But for platform less than 21, while **cfsetspeed()** is missing, it is enough to `#define cfsetspeed cfsetispeed` - anyways the latter is inlined in `termios.h`. So, to make **boost** happy again, you can simply add **cfsetspeed** to `android/legacy_termios_inlines.h`. It is a breaking change; but it is *'breaking'* in the sense that code that did not compile before, will simply compile, and compile correctly. People who introduced their private workarounds for **cfsetspeed** will need to touch their code, alas.

**Comment by DanAlbert** [comment] 2017-02-22 19:39
Hiding `EPOLL_CLOEXEC` does break the case of people adding behavior conditionally via `dlsym` though. They'd have to define `EPOLL_CLOEXEC` themselves. That sort of use case is pretty core to the NDK, so I don't think we should break that.

Agreed that the `_BSD_SOURCE` change should be called out in the release notes. https://android-review.googlesource.com/342472

> As for **cfsetspeed()**, I believe that NDK r13 compiled our code '*by lucky chance*'. It so happens that with `-isystem`, we get `platforms/android-14/arch-x86/usr/include/asm/posix_types.h` included, but not `toolchains/x86-4.9/prebuilt/darwin-x86_64/lib/gcc/i686-linux-android/4.9.x/include-fixed/asm/posix_types.h`, which happens to include `platforms/android-14/features.h` which defines **`_BSD_SOURCE`**.

I'm confused about the rest of this though. You're saying that with r13 you *didn't* have `_BSD_SOURCE` defined, but now you do? That sounds like it would have the opposite effect; `cfsetspeed` would only get used by boost if `_BSD_SOURCE` *was* defined. Similarly, the fact that the choice is now left to the user should make this work, so I'm not sure why it's breaking. Presumably I've missed something here.

**Comment by enh** [comment] 2017-02-22 20:00
`<linux/eventpoll.h>` is a Linux uapi header, not one of ours, so we won't be changing that. going forward the Android platform and NDK unified headers will always have the latest Linux structs and constants, but functions appropriate to the API level you're targeting, so boost's model is just broken there. (it kind of has to be this way since Android API levels don't imply anything about kernel versions.)

(we might want to remove the duplication and have `<sys/epoll.h>` include `<linux/eventpoll.h>`; it's mildly awkward because the kernel header has an opaque struct where the real userspace header should have a more helpful one.)

the specific case of missing system call stubs like `epoll_create1` should solve itself, hopefully in r15, though, because we can trivially just statically link all the system call stubs.

as for `cfsetspeed`, i think what the reporter is saying is that with r13 they _did_ have _BSD_SOURCE defined via `<features.h>`.

changing `legacy_termios_inlines.h` to match `termios.cpp` (which, as the reporter says, defines `cfsetispeed` and `cfsetospeed` as calls to `cfsetspeed`) sounds fine to me though, if we assume the legacy inlines live on in r15.

**Comment by DanAlbert** [comment] 2017-02-22 20:34
> as for `cfsetspeed`, i think what the reporter is saying is that with r13 they _did_ have _BSD_SOURCE defined via `<features.h>`.

I think I typo'd something in my comment, but now I'm having trouble untangling things. Based on the behavior (boost compiles fine), `_BSD_SOURCE` would have to not be set.

> changing `legacy_termios_inlines.h` to match `termios.cpp` (which, as the reporter says, defines `cfsetispeed` and `cfsetospeed` as calls to `cfsetspeed`) sounds fine to me though, if we assume the legacy inlines live on in r15.

Yeah, this is doable. I think boost needs to make some fixes anyway because of the epoll issue though, so I'd rather avoid respinning. I'll go file bugs with boost and see how accommodating they are.

**Comment by DanAlbert** [comment] 2017-02-22 20:46
https://svn.boost.org/trac/boost/ticket/12863

**Comment by enh** [comment] 2017-02-23 07:26
https://android-review.googlesource.com/342780 removes the EPOLL_CLOEXEC duplication.

**Comment by alexcohn** [comment] 2017-02-23 08:37
Hiding **EPOLL_CLOEXEC** in unified headers for API < 21 cannot, IMHO, break someone's code even if they use **dlsym**, because this simply reflects the current situation in platform headers.

**Comment by DanAlbert** [comment] 2017-02-23 08:54
They could `syscall(__NR_epoll_create1, EPOLL_CLOEXEC)` though.

**Comment by DanAlbert** [comment] 2017-02-23 08:55
And, actually, that'd probably be the simplest fix for boost.

**Comment by alexcohn** [comment] 2017-02-23 09:03
The story of **_BSD_SOURCE** defined or not defined in our file is purely academic. It just happens so that the chain of includes with r14 w/o unified headers includes **<features.h>**  and this causes the wrong side of [`#if`](https://github.com/boostorg/asio/blob/develop/include/boost/asio/impl/serial_port_base.ipp#L118) to be compiled.

**Comment by DanAlbert** [comment] 2017-02-23 09:18
Okay, so yes, I did misunderstand you earlier (you actually said it quite clearly in the OP, but apparently I can't read). It's the `APP_UNIFIED_HEADERS=false` case where the `_BSD_SOURCE` problem is an issue. That makes a lot more sense.

I suppose we can fix that the same way we plan to for the unified headers: we'll just add the inline definition to the deprecated headers.

With that fixed you should be able to keep using the old headers if you like, or with a small fixup to boost to use `syscall` instead of using `epoll_create1` directly, unified headers would work too.

**Comment by alexcohn** [comment] 2017-02-23 12:37
Well I have forged a workaround for **cfsetspeed()** as soon as I understood where **_BSD_SOURCE** came from. 

I believe that we will not switch to unified headers with r14, but the command-line workaround for **epoll_create1()** is easy, as well:

    APP_CXXFLAGS='"-Depoll_create1(x)=-1;errno=EINVAL"'

**Comment by DanAlbert** [comment] 2017-02-23 19:29
I've uploaded a fix for the old headers so you should be able to remove your workaround when r14 ships: https://android-review.googlesource.com/c/343306/

> I believe that we will not switch to unified headers with r14

Any other issues we can help with? We're going to be turning these on by default in r15 unless things go horribly wrong (not sure if you've seen [our roadmap] before).

[our roadmap]: https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md

Thanks a ton for trying these out early, by the way. It helps a lot.

**Comment by DanAlbert** [comment] 2017-02-23 21:48
The `cfsetspeed` fix is in now. The epoll issue will need a fix on the boost side.

**Closed by DanAlbert** 2017-02-23 21:48 UTC

**Comment by alexcohn** [comment] 2017-02-23 22:18
I appreciate your quick response times. 

I don't know of specific issues with unified headers, but I prefer to make small steps, and testing the result on the real users every time. There exist too many weird devices on this planet, and some require very special shims. I guess we will be ready to switch when we upgrade to r15.

**Comment by DanAlbert** [comment] 2017-03-01 20:49
FYI, build 3770861 is the one I'm expecting to push to stable later this week. If you're feeling adventurous you can download it now by following https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md

**Comment by alexcohn** [comment] 2017-03-02 13:52
@DanAlbert I can wait for the official release; I am much more concerned with the patch for Clang x86 stack protection, which is not expected to be available this week.

**Comment by IgorGanapolsky** [comment] 2017-05-11 13:30
@DanAlbert I tried the continuous build #3996500 from https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md, and it didn't solve the problem.  Still getting compilation errors:
> Error:(28, 10) 'asm/page.h' file not found
#include <asm/page.h> // http://code.google.com/p/android/issues/detail?id=39983
         ^~~~~~~~~~~~
1 error generated.
FAILED: /android-ndk-r16-canary/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv5te-none-linux-androideabi --gcc-toolchain=/android-ndk-r16-canary/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/android-ndk-r16-canary/sysroot  -Dandros_EXPORTS -I../../../../ext-libs/live555/basicusageenvironment/include -I../../../../ext-libs/live555/usageenvironment/include -I../../../../ext-libs/live555/groupsock/include -I../../../../ext-libs/live555/livemedia/include -I../../../../ext-libs/live555/openRTSP/include -I/mobilegroup_shared/boost_shared/android/boost_1_57_0/include -I../../../../ext-libs/cpp_netlib/include -I../../../../ext-libs/openssl/include -I../../../../src/main/jni -I../../../../src/main/jni/Logger -I../../../../src/main/jni/BinaryCIPClient -I../../../../src/main/jni/JSON -I../../../../src/main/jni/JSONSpirit -I../../../../src/main/jni/SettingsManager -I../../../../src/main/jni/SystemManager -I../../../../src/main/jni/AutoDiscovery -I../../../../ext-libs/curl/include -I../../../../ext-libs/iconv/include -I../../../../ext-libs/pjsip/include -I../../../../src/main/jni/andros -I../../../../src/main/jni/SIP -I../../../../src/main/jni/MjpegStreamInterface -I../../../../src/main/jni/MjpegStreamLib -I../../../../src/main/jni/ReservedJoinManager -I../../../../src/main/jni/Utility -I../../../../src/main/jni/VideoStreaming -I../../../../src/main/jni/VideoStreaming/StreamManager -I../../../../src/main/jni/VideoStreaming/StreamManager/H264 -I../../../../src/main/jni/VideoStreaming/Stream/H264 -I../../../../src/main/jni/VideoStreaming/Stream/H264/hls_web_server/src -I../../../../src/main/jni/VideoStreaming/Stream/H264/transport_stream -I../../../../src/main/jni/VideoStreaming/Stream -I../../../../src/main/jni/VideoStreaming/StreamManager/MJPEG -I../../../../src/main/jni/VideoStreaming/Stream/MJPEG -I../../../../src/main/jni/VideoStreaming/PlatformAdapter -I../../../../s
rc/main/jni/VideoStreaming/PlatformAdapter/android -I../../../../src/main/jni/VideoStreaming/UrlProcessor -I../../../../src/main/jni/VideoStreaming/Live555Igor -I../../../../src/main/jni/third_party_app_launch -I../../../../src/main/jni/reserved_joins -I../../../../src/main/jni/reserved_join_handlers -I../../../../src/main/jni/service_manager -I../../../../src/main/jni/bcip_client_ng -isystem /android-ndk-r16-canary/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /android-ndk-r16-canary/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -isystem /android-ndk-r16-canary/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem /android-ndk-r16-canary/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -Wno-error=format-security -fexceptions -frtti -DANDROID_H264 -Os -DNDEBUG  -fPIC -MD -MT CMakeFiles/andros.dir/src/main/jni/AutoDiscovery/device_discovery_timeout_worker.cpp.o -MF CMakeFiles/andros.dir/src/main/jni/AutoDiscovery/device_discovery_timeout_worker.cpp.o.d -o CMakeFiles/andros.dir/src/main/jni/AutoDiscovery/device_discovery_timeout_worker.cpp.o -c /workspace/cmake2/trunk/jni-code/src/main/jni/AutoDiscovery/device_discovery_timeout_worker.cpp
In file included from /workspace/cmake2/trunk/jni-code/src/main/jni/AutoDiscovery/device_discovery_timeout_worker.cpp:11:
In file included from ../../../../src/main/jni/AutoDiscovery/device_discovery_timeout_worker.h:12:
In file included from /mobilegroup_shared/boost_shared/android/boost_1_57_0/include/boost/thread.hpp:13:
In file included from /boost_shared/android/boost_1_57_0/include/boost/th
read/thread.hpp:12:
In file included from /boost_shared/android/boost_1_57_0/include/boost/thread/thread_only.hpp:17:
/boost_shared/android/boost_1_57_0/include/boost/thread/pthread/thread_data.hpp:28:10: fatal error: 'asm/page.h' file not found
#include <asm/page.h> // http://code.google.com/p/android/issues/detail?id=39983
         ^~~~~~~~~~~~
1 error generated.
FAILED: /android-ndk-r16-canary/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv5te-none-linux-androideabi --gcc-toolchain=/android-ndk-r16-canary/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/android-ndk-r16-canary/sysroot  -Dandros_EXPORTS -I../../../../ext-libs/live555/basicusageenvironment/include -I../../../../ext-libs/live555/usageenvironment/include -I../../../../ext-libs/live555/groupsock/include -I../../../../ext-libs/live555/livemedia/include -I../../../../ext-libs/live555/openRTSP/include -I/boost_shared/android/boost_1_57_0/include -I../../../../ext-libs/cpp_netlib/include -I../../../../ext-libs/openssl/include -I../../../../src/main/jni -I../../../../src/main/jni/Logger -I../../../../src/main/jni/BinaryCIPClient -I../../../../src/main/jni/JSON -I../../../../src/main/jni/JSONSpirit -I../../../../src/main/jni/SettingsManager -I../../../../src/main/jni/SystemManager -I../../../../src/main/jni/AutoDiscovery -I../../../../ext-libs/curl/include -I../../../../ext-libs/iconv/include -I../../../../ext-libs/pjsip/include -I../../../../src/main/jni/andros -I../../../../src/main/jni/SIP -I../../../../src/main/jni/MjpegStreamInterface -I../../../../src/main/jni/MjpegStreamLib -I../../../../src/main/jni/ReservedJoinManager -I../../../../src/main/jni/Utility -I../../../../src/main/jni/VideoStreaming -I../../../../src/main/jni/VideoStreaming/StreamManager -I../../../../src/main/jni/VideoStreaming/StreamManager/H264 -I../../../../src/main/jni/VideoStreaming/Stream/H264 -I../../../../src/main/jni/VideoStreaming/Stream/H264/hls_web_server/src -I../../../../src/main/jni/VideoStreaming/Stream/H264/transport_stream -I../../../../src/main/jni/VideoStreaming/Stream -I../../../../src/main/jni/VideoStreaming/StreamManager/MJPEG -I../../../../src/main/jni/VideoStreaming/Stream/MJPEG -I../../../../src/main/jni/VideoStreaming/PlatformAdapter -I../../../../s
rc/main/jni/VideoStreaming/PlatformAdapter/android -I../../../../src/main/jni/VideoStreaming/UrlProcessor -I../../../../src/main/jni/VideoStreaming/Live555Igor -I../../../../src/main/jni/third_party_app_launch -I../../../../src/main/jni/reserved_joins -I../../../../src/main/jni/reserved_join_handlers -I../../../../src/main/jni/service_manager -I../../../../src/main/jni/bcip_client_ng -isystem /android-ndk-r16-canary/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /android-ndk-r16-canary/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -isystem /android-ndk-r16-canary/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem /android-ndk-r16-canary/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -Wno-error=format-security -fexceptions -frtti -DANDROID_H264 -Os -DNDEBUG  -fPIC -MD -MT CMakeFiles/andros.dir/src/main/jni/AutoDiscovery/cip_sendpacket_worker.cpp.o -MF CMakeFiles/andros.dir/src/main/jni/AutoDiscovery/cip_sendpacket_worker.cpp.o.d -o CMakeFiles/andros.dir/src/main/jni/AutoDiscovery/cip_sendpacket_worker.cpp.o -c /cmake2/trunk/jni-code/src/main/jni/AutoDiscovery/cip_sendpacket_worker.cpp
In file included from /cmake2/trunk/jni-code/src/main/jni/AutoDiscovery/cip_sendpacket_worker.cpp:10:
In file included from ../../../../src/main/jni/AutoDiscovery/cip_sendpacket_worker.h:12:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio.hpp:21:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio/basic_datagram_socket.hpp:20:
In file included from /Users/
/android/boost_1_57_0/include/boost/asio/basic_socket.hpp:20:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio/basic_io_object.hpp:19:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio/io_service.hpp:767:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio/impl/io_service.hpp:71:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio/detail/task_io_service.hpp:198:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio/detail/impl/task_io_service.ipp:24:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio/detail/reactor.hpp:21:
In file included from /boost_shared/android/boost_1_57_0/include/boost/asio/detail/epoll_reactor.hpp:239:
/boost_shared/android/boost_1_57_0/include/boost/asio/detail/impl/epoll_reactor.ipp:463:12: error: use of undeclared identifier 'epoll_create1'; did you mean 'epoll_create'?
  int fd = epoll_create1(EPOLL_CLOEXEC);
           ^~~~~~~~~~~~~
           epoll_create
/android-ndk-r16-canary/sysroot/usr/include/sys/epoll.h:76:5: note: 'epoll_create' declared here

**Comment by DanAlbert** [comment] 2017-05-11 16:16
Something has gone wrong with your build.

> `#include <asm/page.h> // http://code.google.com/p/android/issues/detail?id=39983

This line doesn't appear anywhere in that build, so one of the projects you're including there is probably the one including `asm/page.h` (that header doesn't exist any more). I've cases where iptables actually has its own copies of old Linux headers, but that doesn't seem to be here. Possibly something similar though?

**Comment by IgorGanapolsky** [comment] 2017-05-11 16:23
@DanAlbert Doing a machine wide search located this for me: **/android-ndk-r16-canary/platforms/android-14/arch-x86/usr/include/linux** - where you can see
`#include <asm/a.out.h>`

**Comment by enh** [comment] 2017-05-11 16:25
(looks like current boost says

#if defined(__ANDROID__)
# ifndef PAGE_SIZE
#  define PAGE_SIZE 4096
# endif
#endif

instead: http://www.boost.org/doc/libs/1_64_0/boost/thread/pthread/thread_data.hpp)

**Comment by DanAlbert** [comment] 2017-05-11 16:26
I see plenty of includes of `asm/page.h`, but I don't see any that include that bug URL.

```bash
$ grep -r 39983 .android-ndk-r16-canary/
```

Turns up nothing.

The specific header you've pointed at shouldn't be used in your build anyway. Those are the deprecated headers, not the ones that should have this fixed.

**Comment by enh** [comment] 2017-05-11 16:31
the line with the bug URL was a boost file. but like i said, the current version looks different. so it looks like an out of date boost that won't work with unified headers.

**Comment by IgorGanapolsky** [comment] 2017-05-11 17:04
That URL is being reported by **org.gradle.internal.buildevents.BuildExceptionReporter** with ninja build system.  Tracing back to the build error, I see that the problem is in `thread_only.hpp` where it includes:
 **#include <boost/thread/pthread/thread_data.hpp>**

**Comment by yan12125** [comment] 2018-01-30 06:16
Hello, https://android-review.googlesource.com/c/platform/bionic/+/401372 breaks building CPython with NDK r15+ and android-19 (https://bugs.python.org/issue28914). Is there a chance to revert the aforementioned change in r17? I guess after r15 and r16 cycles, most third-party codes have been fixed.

**Comment by enh** [comment] 2018-01-30 06:57
_because_ of the workaround, no third-party code will have changed: the workaround ensures that they continue to build because they won't see the constants if the function isn't available.

**Comment by yan12125** [comment] 2018-01-30 07:31
Thanks I guess you're right. I'll go back to CPython for a fix.

**Comment by enh** [comment] 2018-01-30 16:00
https://github.com/python/cpython/commit/b8d90328ad2abc9d6d2c9b8ce769fb82b18bbc10 (using configure to detect epoll_create1) looks like the right fix.
