### ISSUE TITLE
Segmentation fault while building PPSSPP with NDK r20

### ISSUE THREAD

**Issue by devopsdeluxe** [android-ndk/ndk#1000] opened 2019-06-07 05:06 UTC
#### Description

The following error occurs while building PPSSPP with NDK r20:

```
Stack dump:
0.	Program arguments: /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -cc1 -triple thumbv7-none-linux-android16 -emit-obj -mnoexecstack -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hlslParseHelper.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -relaxed-aliasing -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature -fp-only-sp -target-feature -d16 -target-feature +vfp3 -target-feature -fp16 -target-feature -vfp4 -target-feature -fp-armv8 -target-feature +neon -target-feature -crypto -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -ffunction-sections -fdata-sections -coverage-notes-file /home/drb/Git/ppsspp/android/.externalNativeBuild/cmake/goldRelease/armeabi-v7a/ext/glslang/hlsl/CMakeFiles/HLSL.dir/hlslParseHelper.cpp.gcno -sys-header-deps -D AMD_EXTENSIONS -D ENABLE_HLSL -D ENABLE_OPT=0 -D GLSLANG_OSINCLUDE_UNIX -D GOLD -D MOBILE_DEVICE -D NV_EXTENSIONS -D USING_GLES2 -D __STDC_CONSTANT_MACROS -D ANDROID -D NDEBUG -D _NDEBUG -O3 -Wformat -Werror=format-security -Wno-switch -Wno-uninitialized -Wno-multichar -Wno-deprecated-register -Wall -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Wno-reorder -std=c++11 -fdeprecated-macro -ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-loops -vectorize-slp -x c++ hlslParseHelper-3e494b.cpp 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'hlslParseHelper-3e494b.cpp'.
4.	Running pass 'Simple Register Coalescing' on function '@_ZN7glslang16HlslParseContext17remapEntryPointIOERNS_9TFunctionERPNS_9TVariableERNS_7TVectorIS4_EES8_'
#0 0x000000000242f066 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x242f066)
#1 0x000000000242dca0 llvm::sys::RunSignalHandlers() (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x242dca0)
#2 0x000000000242f34f (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x242f34f)
#3 0x00007fb01a6144d0 __restore_rt (/usr/lib/libpthread.so.0+0x124d0)
#4 0x0000000001e43747 llvm::LiveRange::join(llvm::LiveRange&, int const*, int const*, llvm::SmallVectorImpl<llvm::VNInfo*>&) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1e43747)
#5 0x0000000001eec54f (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1eec54f)
#6 0x0000000001ee8d18 (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1ee8d18)
#7 0x0000000001ee8686 (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1ee8686)
#8 0x0000000001ee83cb (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1ee83cb)
#9 0x0000000001ee7d85 (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1ee7d85)
#10 0x0000000001ee7a57 (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1ee7a57)
#11 0x0000000001e79ec3 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1e79ec3)
#12 0x000000000209208b llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x209208b)
#13 0x00000000020924e3 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x20924e3)
#14 0x00000000020928ad (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x20928ad)
#15 0x000000000209265d llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x209265d)
#16 0x0000000002755c1c (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2755c1c)
#17 0x0000000002753184 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2753184)
#18 0x0000000002936591 (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2936591)
#19 0x000000000307b7a8 clang::ParseAST(clang::Sema&, bool, bool) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x307b7a8)
#20 0x00000000028d0cf5 clang::FrontendAction::Execute() (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x28d0cf5)
#21 0x000000000286db67 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x286db67)
#22 0x0000000002932ff5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2932ff5)
#23 0x00000000018876d4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x18876d4)
#24 0x0000000001883f22 main (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1883f22)
#25 0x00007fb01a002ce3 __libc_start_main (/usr/lib/libc.so.6+0x23ce3)
#26 0x0000000001883029 _start (/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1883029)
```

Test case: https://github.com/hrydgard/ppsspp/files/3259867/hlslParseHelper-3e494b.tar.gz

#### Environment Details

* NDK Version: r20 (20.0.5594570)
* Build system: Standalone? (Since it's reproducible without gradle)
* Host OS: Linux (Archlinux)
* ABI: v7a (To the best of my knowledge)
* NDK API level: Is this required? If so, how can I query it?
* Device API level: N/A

**Comment by devopsdeluxe** [comment] 2019-06-07 05:37
For good measure I downloaded NDK r20 from: https://developer.android.com/ndk/downloads onto a machine running Ubuntu 18.04 and was able to recreate the issue using the test case there as well.

**Comment by enh** [comment] 2019-06-07 15:21
@stephenhines for llvm crash...

**Comment by pirama-arumuga-nainar** [comment] 2019-06-07 18:17
I confirmed the crash in r20 (clang-r349610) but it doesn't reproduce in the latest AOSP clang (clang-r353983c).  This version is slated to be in r21.

**Comment by DanAlbert** [comment] 2019-06-07 18:19
Thanks for verifying. I've uploaded the changes to update master to that build, but they're currently blocked on https://github.com/android-ndk/ndk/issues/999.

**Comment by hrydgard** [comment] 2019-06-26 13:43
Isn't this broken enough to warrant an NDK point release in the meantime? A regression crashing the ARMv7 compiler completely is pretty bad, we can't yet require 64-bit. #999 seems to be done?

**Comment by stephenhines** [comment] 2019-06-26 19:18
At this point, cherry-picking a fix for this specific issue is not realistic for r20. Do you have a workaround for your code sample? If not, we might be able to help in getting something that at least prevents the compiler crash.

**Comment by DanAlbert** [comment] 2019-09-04 19:55
Master now has r365631, so this will be in r21.

**Closed by DanAlbert** 2019-09-04 19:55 UTC
Labels: bug
