### ISSUE TITLE
undef ref to __cxa_bad_cast with c++_shared, rtti and exceptions activated

### ISSUE THREAD

**Issue by victorlevasseur** [android-ndk/ndk#170] opened 2016-07-24 08:20 UTC
Hi,

I updated the NDK version I used for my C++ project to the NDK 12b. Unfortunately, the compilation now fails with this error message : 

```
jni/Core/GDCore/Project/ImageManager.cpp:43: error: undefined reference to '__cxa_bad_cast'
jni/Core/GDCore/Project/ImageManager.cpp:97: error: undefined reference to '__cxa_bad_cast'
jni/Core/GDCore/Project/ImageManager.cpp:143: error: undefined reference to '__cxa_bad_cast'
jni/GDCpp/GDCpp/Extensions/ExtensionBase.inl:20: error: undefined reference to '__cxa_bad_cast'
collect2.exe: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/libsfml-example.so] Error 1
```

My app uses exceptions and, as you can see, it catches ```std::bad_cast```

(my app is based on an example provided by SFML).

Here is my Android.mk file : 

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := sfml-example

LOCAL_CPP_FEATURES := rtti exceptions

#GDCpp game engine
LOCAL_CFLAGS +=  -I$(LOCAL_PATH)/GDCpp -I$(LOCAL_PATH)/Core -DGD_CORE_API="" -DGD_API=""
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/GDCpp/GDCpp/Runtime/*.cpp))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/GDCpp/GDCpp/Runtime/Serialization/*.cpp))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/GDCpp/GDCpp/Runtime/Utf8/*.c))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/GDCpp/GDCpp/Runtime/Tools/*.cpp))
LOCAL_SRC_FILES += OTHER FILES, AGAIN AND AGAIN :)

#SFML
LOCAL_SHARED_LIBRARIES := sfml-system
LOCAL_SHARED_LIBRARIES += sfml-window
LOCAL_SHARED_LIBRARIES += sfml-graphics
LOCAL_SHARED_LIBRARIES += sfml-audio
LOCAL_SHARED_LIBRARIES += sfml-network
LOCAL_WHOLE_STATIC_LIBRARIES := sfml-main

include $(BUILD_SHARED_LIBRARY)

$(call import-module,sfml)

```

and my Application.mk file : 

```
NDK_TOOLCHAIN_VERSION := 4.9
APP_PLATFORM := android-9
APP_STL := c++_shared
APP_ABI := armeabi-v7a
APP_MODULES := sfml-activity sfml-example
```

**Comment by DanAlbert** [comment] 2016-07-25 18:33
Was fixed with these two patches: https://android-review.googlesource.com/#/q/topic:android_support_ordering

This was fixed after r12b, unfortunately. You might be able to workaround this by linking libc++abi explicitly (`LOCAL_STATIC_LIBRARIES += libc++abi`).

`c++_static` should work fine, but that can have surprising results when your app consists of more than one shared library (multiple copies of global data). If you have the option of only using static libraries for your intermediates and only shipping a single `libmyapp.so`, you'd be able to switch to `c++_static` and get around the issue (probably would have some code size improvements as well since the linker would be able to prune more unused code).

**Comment by victorlevasseur** [comment] 2016-07-26 15:36
Yes, my app uses multiple shared libraries, so I will wait for the next version (and use r11c meanwhile).

Thanks for your quick reply. :+1:

**Comment by DrMetallius** [comment] 2016-10-10 16:33
Doesn't seem to be fixed in NDK r13, I get `undefined reference to '__cxa_bad_cast'` as well.

**Comment by DanAlbert** [comment] 2016-10-10 18:34
@DrMetallius, do you have a repro case? We have a test that shows `-frtti -fexceptions` works fine with `c++_shared`: https://android.googlesource.com/platform/ndk/+/master/tests/device/libcxx-unwind/

**Comment by myliojordank** [comment] 2016-10-10 22:34
I was able to reproduce the `undefined reference to '__cxa_bad_cast'` linker error by adding a dynamic cast as follows:

    struct Foo
    {
        virtual ~Foo() {}
    };

    struct Bar
    {
        virtual ~Bar() {}
    };

    ...

    Foo f;

    try
    {
        Bar& b = dynamic_cast<Bar&>(f);
    }
    catch (...)
    {

    }

I am using clang on OS X with NDK r13 and, like the others, the linker error only occurs when `APP_STL := c++_shared`

**Comment by DanAlbert** [comment] 2016-10-10 23:34
That repros (r12b, r13, r14-canary are all broken, r11c works). Thanks for the test case, @myliojordank. I'll take a look.

**Comment by myliojordank** [comment] 2016-10-10 23:48
@DanAlbert no problem, thanks for investigating.

**Comment by DanAlbert** [comment] 2016-10-10 23:53
Just an FYI about logistics for this bug: if the fix seems safe this seems like justification for an r13b to me. It's not a regression from r12, but it is a pretty important thing that I'm guessing is keeping a lot of people stuck on r11, and I'd rather not keep people stuck there until r14 in December. Also, it's something I tried to fix in r13, but apparently I only fixed part of the problem.

If the fix ends up being something that might have unintended consequences, it'll probably need to wait for r14.

**Comment by DanAlbert** [comment] 2016-10-11 00:23
Tentative fix looks safe. libc++abi was mostly re-exported from libc++ because libc++ actually uses most of the things in libc++abi, but anything not used won't be re-exported. Moving libc++abi to libc++'s `LOCAL_WHOLE_STATIC_LIBRARIES` fixes this.

Will need to run the more complete test suite before I can say for sure, but assuming that all comes back clean I'll make an r13b for this (will hold off until at least next week to see what other issues come in).

**Comment by DanAlbert** [comment] 2016-10-13 20:45
Changes are in for r13b. I'm aiming for a release some time next week. Not waiting as long as I said above because the way scheduling works out means we either go then or have to wait quite a bit longer.

**Closed by DanAlbert** 2016-10-13 20:45 UTC

**Comment by myliojordank** [comment] 2016-10-13 22:04
Awesome, thanks @DanAlbert

**Comment by kangjoni76** [comment] 2016-10-14 02:02
Sorry for making noise, @DanAlbert, does this means that iced cream sandwich stack unwinding c++shared will be made in r14 too? I was one of those who feel stuck and settled on the version r10e, because of this case.
