### ISSUE TITLE
r11 GCC 4.9 x86 incompatible posix_memalign declaration

### ISSUE THREAD

**Issue by edkimmel** [android-ndk/ndk#91] opened 2016-04-29 17:33 UTC
I believe this mailing list is actually specifying the same problem https://gcc.gnu.org/ml/gcc-patches/2015-05/msg01425.html

Error occurred when compiling zeromq (https://github.com/zeromq/libzmq)
- x86
- NDK r11
- GCC 4.9

```
Toolchains/x86/lib/gcc/i686-linux-android/4.9/include/mm_malloc.h:35:64: error: declaration of 'int posix_memalign(void**, size_t, size_t) throw ()' has a different exception specifier
 extern "C" int posix_memalign (void **, size_t, size_t) throw ();
                                                                ^
In file included from Toolchains/x86/include/c++/4.9/cstdlib:72:0,
                 from Toolchains/x86/include/c++/4.9/bits/stl_algo.h:59,
                 from Toolchains/x86/include/c++/4.9/algorithm:62,
                 from src/own.hpp:34,
                 from src/socket_base.hpp:37,
                 from src/dish.hpp:36,
                 from src/dish.cpp:41:
Toolchains/x86/sysroot/usr/include/stdlib.h:69:12: error: from previous declaration 'int posix_memalign(void**, size_t, size_t)'
 extern int posix_memalign(void **memptr, size_t alignment, size_t size);

In file included from Toolchains/x86/lib/gcc/i686-linux-android/4.9/include/xmmintrin.h:34:0,
                 from Toolchains/x86/lib/gcc/i686-linux-android/4.9/include/x86intrin.h:31,
                 from Toolchains/x86/include/c++/4.9/i686-linux-android/bits/opt_random.h:33,
                 from Toolchains/x86/include/c++/4.9/random:50,
                 from Toolchains/x86/include/c++/4.9/bits/stl_algo.h:66,
                 from Toolchains/x86/include/c++/4.9/algorithm:62,

```

This feels like a really, really bad question...but could I modify mm_malloc.h in the meantime to match the declaration?

**Comment by DanAlbert** [comment] 2016-04-29 18:08
wtf? Why does GCC have exception specifications in their C headers (and why is this one only for x86?)

Clang doesn't have this (and it has a comment explaining that they don't match GCC because they agree that GCC is wrong). You'd be better off switching to the non-deprecated compiler :)

The fix is trivial enough though. If @thanm agrees, I'll upload a patch removing the exception specification.

**Comment by edkimmel** [comment] 2016-04-29 18:24
Every now and then I'll be given the time to try moving to clang again. We have some larger dependencies that don't use a standard configure/make system, and their Android configs only expect gcc (stuck in the past). Pretty sad, but we're waiting for them to catch up with the new clang support.

Actually, there was an issue logged here somewhere about having clang log warnings on unsupported flags instead of causing an error. Do you know the state of that?

**Comment by DanAlbert** [comment] 2016-04-29 18:27
Doesn't ring a bell. We do that in the platform and it's been quite helpful, so seems like a good thing to add to the NDK. https://github.com/android-ndk/ndk/issues/92

**Comment by DanAlbert** [comment] 2016-09-08 17:42
FYI I've raised this internally with our GCC folks.

**Comment by edkimmel** [comment] 2016-09-21 19:09
Any info on whether this will be available for r13?

**Comment by DanAlbert** [comment] 2016-09-21 20:04
Hasn't been fixed yet and r13 is essentially done (I haven't had any bugs filed for beta 2 yet, so probably releasing to stable in the next two weeks). Even if it were fixed today, swapping compilers post beta 2 would not be a good idea :)

I'll ping the internal bug.

**Comment by cmtice** [comment] 2016-10-03 17:04
I think I have a fix, but I need to verify it by first reproducing your problem, then making sure my fix fixes it. Could you please give me detailed instructions on how to set up your environment and reproduce your problem?

**Comment by DanAlbert** [comment] 2016-10-04 22:53
@cmtice merged a change that should fix this (https://android-review.googlesource.com/#/c/280335/) but I still need to update the prebuilt GCC for the NDK before we actually get the change.

**Comment by DanAlbert** [comment] 2016-10-04 22:54
(I also need to come up with a regression case for our test suite)

**Comment by enh** [comment] 2017-05-30 22:26
did the GCC prebuilt update ever happen?

**Comment by DanAlbert** [comment] 2017-05-30 22:29
I don't think so. GCC was declared unsupported by the time the fix made it.

**Closed by DanAlbert** 2017-05-30 22:29 UTC
Labels: gcc
