### ISSUE TITLE
Use openssl static library in android refer a link error

### ISSUE THREAD

**Issue by jishuo1213** [android-ndk/ndk#160] opened 2016-07-14 07:00 UTC
I build openssl static library follow the openssl [wiki](https://wiki.openssl.org/index.php/Android),my build environment is as follows:
openssl-1.0.2h
ndk:android-ndk-r12b
android-api:android-14
android_arch=arch-arm
At first,I use md5 to test wether build success, it's ok.But when I use some other functions,there is a link error as follows:

> libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'bsd_signal'

I search this error and found that in android version less than or equal 19,in [signal.h](https://chromium.googlesource.com/android_tools/+/20ee6d20/ndk/platforms/android-19/arch-arm/usr/include/signal.h),there is bsd_signal symbol,but in android version 21 or higher [signal.h](https://chromium.googlesource.com/android_tools/+/20ee6d/ndk/platforms/android-21/arch-arm/usr/include/signal.h),the bsd_signal was removed,so I changed android-api to 21 and rebuild the library,everything is ok on android api version higher or equal 21, but on earlier version,it's failed.
I find the code in [ui_openssl.c](https://github.com/openssl/openssl/blob/master/crypto/ui/ui_openssl.c),Will this problem be solved if modify some source code?
I am very confuse about two point:
1.in every version in android ,there is a function called signal(),in previous version less than 21,it's a wrapper function of bsd_signal,in later version,It's not a wrapper function,so there must be no error when we called signal().
2.when I use android-api=14 to build library,the library have same error on android version less than 19 and higher than 19, in android version less than or equal 19 there is bsd_signed() in signal.h,I think the library must can be used in version less than 19 and can't use in other version.
Look forward to you reply.

**Comment by DanAlbert** [comment] 2016-07-14 22:35
This should be cleared up once we get all the headers updated. The libraries in the NDK all got pruned to remove things that were also removed in newer versions (to make porting across versions easier), but the headers were a much larger and more complicated task. Apparently separating these tasks confuses autoconf since the headers now declare functions that don't actually exist (there have actually always been cases of this, but not for anything as important as `signal`).

**Comment by minggo** [comment] 2016-07-29 03:40
Yep, i met this issue. I am the maintainer of [cocos2d-x](https://github.com/cocos2d/cocos2d-x), and cocos2d-x depends on libwebsockets with uses `signal`. It is an important issue, can i know when it can be fixed?

**Comment by DanAlbert** [comment] 2016-07-29 05:39
So this isn't actually a header issue. The problem is that objects built against a pre-21 (where signal.h got fixed) API level are being linked into something built against 21 or newer. The first object gets the inline definition of `signal` that refers to `bsd_signal` and then when linking that object into something built against android-21 we don't have `bsd_signal` available (because it isn't needed in 21 and later).

Mixing and matching target platforms is a little funky (note that `ndk-build` won't let you do this directly), but I think it's something that prevalent enough that we ought to support it in the older -> newer direction (the reverse is not possible).

@dimitry-, all make sense? The fix here is to put `bsd_signal` back for 21+.

**Comment by minggo** [comment] 2016-07-29 06:01
Yep, it is because bsd_signal is removed since 21+, it breaks compatibility. I think building with lower API level should work in higher API level.

**Comment by minggo** [comment] 2016-07-29 08:06
But it is strange that, when i build with 19 and run on Nexus 5x(Android 6.0), it doesn't crash. But it may crash on some devices. I don't know why. I think it will crash on all devices with Android OS 5.0+(21).

**Comment by mastakrishna** [comment] 2016-07-29 12:02
The fun part is that although bsd_signal was removed from signal.h in android-21, the symbol was still there in android-21 libc.so of NDK r10e. However it's not there in NDK r11's libc.so (checked NDK r11c) resulting in such linking errors.
The bsd_signal is still available in libc.so on Android devices even with Android N developer preview, so what I ended up doing as a work around was getting the pointer to bsd_signal via dlsym and calling it from bsd_signal defined in my code.
Using "signal" directly (compiling the lib that uses signal with android-21 and up) breaks compatibility with older devices that don't have "signal" symbol in their libc.so.

**Comment by dimitry-** [comment] 2016-07-29 21:18
> The fix here is to put bsd_signal back for 21+.
Yes, this makes sense.. let's put it back.

**Comment by minggo** [comment] 2016-08-01 02:32
@mastakrishna good to know, thanks. But we can not change codes that used in 3rd part library, so i think put `bsd_singal` back is needed.

@dimitry- thanks.

**Comment by mastakrishna** [comment] 2016-08-01 06:25
Sure, bringing back bsd_signal symbol in next release of NDK (r13) is more than welcome. I was just providing a temporary all-around. Plus, this bsd_signal code can be put in your code, not the 3rd party lib one. After all its "just" a linking error.

**Comment by minggo** [comment] 2016-08-01 06:28
No, it will crash on some devices.

**Comment by mastakrishna** [comment] 2016-08-01 06:31
@minggo Could you elaborate? I've tested on a couple of devices ranging Android 4.1 up to Android 7.0 (latest developer preview) and seemed fine to me on all of them.

**Comment by minggo** [comment] 2016-08-01 06:40
@mastakrishna its my fault, it is link error. But i can not add `bsd_signal` in cocos2d-x because it is an open source game engine. And developers can use build with different NDK version, use different API level. If added `bad_signal` in cocos2d-x, will cause link error if building with 19?

**Comment by mastakrishna** [comment] 2016-08-01 06:45
You can put an #if testing for ANDROID ndk level. Plus AFAIR I checked with NDK r10e (where bsd_signal.l is still there in libc.so on android-21) and there was no link issue. After all libc.so is linked dynamically, so there can be more than one symbol with the same name.

PS. I put some comments in your cocos2d-x issue. Note that if bsd_signal is indeed missing in some devices' libc.so, bringing it back to NDK won't fix your problem.

**Comment by minggo** [comment] 2016-08-02 06:32
@mastakrishna thanks. Did you mean i should do like this:

```
#if API_LEVEL_GREATTER_THAN_19
    extern __sighandler_t bsd_signal(int, __sighandler_t);
#endif
```

**Comment by mastakrishna** [comment] 2016-08-02 07:52
@minggo No, no, no. If you wanted to just have that extern would only fix compilation, not linking. At link time you still need the symbol in one of the libs, even if declaring it extern.

You really have to go with the code I put in stackoverflow until it's fixed in the NDK, but yeah, you should put:
```
#if (__ANDROID_API__ > 19)
(...)
#endif
```
around it.

**Comment by minggo** [comment] 2016-08-02 07:59
Thanks @mastakrishna .

**Comment by DanAlbert** [comment] 2016-08-09 21:12
Fix up for review: https://android-review.googlesource.com/#/c/255054/
And the regression test: https://android-review.googlesource.com/#/c/255053/

**Closed** 2016-08-11 17:23 UTC

**Comment by Cristo86** [comment] 2016-11-23 21:57
Workaround for a particular case. If you are building a particular library for android targeting android-20 (or lower) and then static linking it to a project targeting android-21+, remember to rebuild the former for android-21. That's how there will be no needed reference for bsd_signal.

**Comment by DanAlbert** [comment] 2016-11-28 22:46
You shouldn't need to do that with r13. The commits I posted above should have fixed that. We want to support linking older into newer (other way around is infeasible), so if you're seeing more issues like this with r13 please file bugs.
