### ISSUE TITLE
ndk-stack file is missing

### ISSUE THREAD

**Issue by edkimmel** [android-ndk/ndk#24] opened 2016-03-16 17:25 UTC
http://developer.android.com/ndk/guides/ndk-stack.html

$NDK/ndk-stack does not exist in the ndk11 package.

**Comment by DanAlbert** [comment] 2016-03-16 17:27
Duplicate of https://github.com/android-ndk/ndk/issues/19

**Closed by DanAlbert** 2016-03-16 17:27 UTC
