### ISSUE TITLE
Memory leak detected when creating threads in libc++

### ISSUE THREAD

**Issue by bhupeshpant19jan** [android-ndk/ndk#819] opened 2018-10-17 19:00 UTC
------------------------------------------------------------------------------

#### Memory leak is detected when we are creating std::thread object.

Our existing test suite has started detecting memory leak where we are creating std::thread object after we moved from gnustl to libc++. Apart from stdlib changes, nothing has changed in our code.

I also wrote a test case which to replicate the issue.

```c++
TEST_METHOD(Test_make_thread)
{
               std::thread thread_to_test(foo);
		thread_to_test.join();
		TestAssert::IsFalse(false);
}	
```

I am seeing this issue during teardown process.
                 * FAIL:
4 leaks

    [1 / 4] Leaked 4 bytes allocated at 0xabc29f88
     at Mso::Memory::AllocateEx(unsigned int, unsigned long) (line 0)
     at Mso::Memory::Throw::AllocateEx(unsigned int, unsigned long) (line 0)
     at operator new(unsigned int) (line 0)
     at unknown
     at Mso::Events::UnitTest::ResetableWaitableEventTests::Test_make_thread() (line 0)
     at RunnableMotifTest::Run(void (MotifCppTestBase::*)(), bool) (line 0)
     at RunnableMotifTest::RunTest() (line 0)
     at UnitTestRunner::RunTest(RunnableMotifTest*, TestErrorLogger&) (line 0)
     at UnitTestCollection::TestActionRunTest(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&) (line 0)
     at unknown
     at unknown
     at unknown
     at unknown
     at UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&)) (line 0)
     at UnitTestCollection::RunTestAction(RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&)) (line 0)
     at UnitTestCollection::RunUnitTestMethodImplementation(UnitTestString const&, UnitTestString const&) (line 0)
     at UnitTestCollection::RunUnitTestMethod(UnitTestString const&, UnitTestString const&) (line 0)
     at UnitTestApiRunTestMethodBody(wchar_t*, wchar_t*, tagNativeTestInteropMethods) (line 0)
     at Motif::NativeTestAdapter::TestMethodRun(wchar_t const*, wchar_t const*) (line 0)
     at Motif::NativeMethodRunner::RunTestMethod(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__nd (line 0)
     at Motif::Application::HandleTestMethodInvoke(Motif::TestMethodInvokeRequest const&, long long) (line 0)
     at unknown
     at unknown
     at unknown
     at std::__ndk1::function<void (Motif::TestMethodInvokeRequest, long long)>::operator()(Motif::TestMethodInvokeRequest, long long) const (line 0)
     at void Motif::RegisterReceiver<Motif::TestMethodInvokeRequest>(std::__ndk1::unique_ptr<Grf::Messaging::RequestResponseBroker, std::__ndk1::function<void (Grf::Messaging::RequestResponseBroker*)> >&, std::__ndk1::shared_ptr<Grf::IDispatcher> const&, std::__nd (line 0)
     at Grf::FuncAction<void Motif::RegisterReceiver<Motif::TestMethodInvokeRequest>(std::__ndk1::unique_ptr<Grf::Messaging::RequestResponseBroker, std::__ndk1::function<void (Grf::Messaging::RequestResponseBroker*)> >&, std::__ndk1::shared_ptr<Grf::IDispatcher> c (line 0)
     at void Grf::Messaging::RequestResponseBroker::AddTypedReceiver<Motif::GrfSerializer, Motif::TestMethodInvokeRequest, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >(std::__ndk1::map<std::__ndk1::basic_string<c (line 0)
     at void Grf::Details::DeferredFunctionCall<0u>::Call<void Grf::Messaging::RequestResponseBroker::AddTypedReceiver<Motif::GrfSerializer, Motif::TestMethodInvokeRequest, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char (line 0)
     at void Grf::Details::DeferredFunctionCall<1u>::Call<void Grf::Messaging::RequestResponseBroker::AddTypedReceiver<Motif::GrfSerializer, Motif::TestMethodInvokeRequest, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char (line 0)
     at void Grf::Details::DeferredFunctionCall<2u>::Call<void Grf::Messaging::RequestResponseBroker::AddTypedReceiver<Motif::GrfSerializer, Motif::TestMethodInvokeRequest, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char (line 0)
     at Grf::DeferredFunction<void Grf::Messaging::RequestResponseBroker::AddTypedReceiver<Motif::GrfSerializer, Motif::TestMethodInvokeRequest, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >(std::__ndk1::map<std:: (line 0)
OAUTOBUGTAG:CLS[DEBUGHEAP_LEAK][4][][][]ENDOABT

Bug reports with better test cases will be resolved sooner than those with bad
test cases. A good test case:

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: r16
* Build system: Clang
* Host OS: Android on Windows
* Compiler: Clang
* ABI: 
* STL: libc++
* NDK API level: 21
* Device API level:

**Comment by DanAlbert** [comment] 2018-10-17 19:52
Do you see this with r18?

**Comment by bhupeshpant19jan** [comment] 2018-10-18 02:55
No, as mentioned above we are using r16.

**Comment by bhupeshpant19jan** [comment] 2018-10-18 03:36
Thanks, Dan for your response.
It won't be straightforward to repro this because our current infra has r16 support, including our test suite. It is not an easy effort to upgrade to r18. 
Can you recommend any other tool where I can test this?
Also, is it possible for you to confirm/test this behavior in r16?

**Comment by bhupeshpant19jan** [comment] 2018-10-18 03:37
One more update, I have tested the same scenario with gnustl lib and there I am not observing any leak.

  Test_make_thread.................................................................................................................................................................................................................PASSED


Top 3 Slowest Tests                                                    Seconds
------------------------------------------------------------------------------
TestFileSetup                                                        00.049647
ResetableWaitableEventTests.Teardown                                 00.042814
TestFileTeardown                                                     00.042519



Test Method Results
-------------------
PASSED            2
FAILED            0
WARNINGS          5

Detailed logs are available at "f:\stl\Logs\ut.droidx86.debug.log".

TESTS PASSED

Execution Times
---------------
Test Run Time           20 sec
Total Execution Time    20 sec

f:\stl\dev\liblet\events\test>

**Comment by DanAlbert** [comment] 2018-10-18 03:42
I'm not sure how I'm going to repro it with any NDK release if you don't have a repro case that works outside your environment. I see there's a snippet in the original post, but it's not complete. What test library is that? How is it built? How are you checking for leaks?

**Comment by bhupeshpant19jan** [comment] 2018-10-18 04:04
This is our internal test suite. I am not sure how we are checking for leaks but I strongly think that it is being done in a  standard way by overloading new,

**Comment by bhupeshpant19jan** [comment] 2018-10-19 04:02
I got this link:- http://clang-developers.42468.n3.nabble.com/Libcxx-TizenRT-Memory-leak-in-std-thread-td4060726.html
Which has observed the similar behavior, can you deduce anything with this information?

**Comment by bhupeshpant19jan** [comment] 2018-10-19 04:03
> Try to reduce a test case if you can.

I am able to reproduce it even with the one test case. I have added others just to try other scenarios.

**Comment by bhupeshpant19jan** [comment] 2018-10-19 04:35
template <class _Tp>
__thread_specific_ptr<_Tp>::~__thread_specific_ptr()
{
    // __thread_specific_ptr is only created with a static storage duration
    // so this destructor is only invoked during program termination. Invoking
    // pthread_key_delete(__key_) may prevent other threads from deleting their
    // thread local data. For this reason we leak the key.
}

What should we do about it?
I think I need to understand why are we doing this and how this will impact our applications.

**Comment by DanAlbert** [comment] 2018-10-19 04:54
The thread you linked explains the rationale.

> This is a common technique used in language libraries and runtimes.  It's even considered good practice, at it allows the process to exit faster and eliminates a source of crashes during user-provided atexit() teardown.

And the comment in the code gives another reason:

```c++
// __thread_specific_ptr is only created with a static storage duration
// so this destructor is only invoked during program termination. Invoking
// pthread_key_delete(__key_) may prevent other threads from deleting their
// thread local data. For this reason we leak the key.
```

Closing since this is intended behavior.

**Closed by DanAlbert** 2018-10-19 04:54 UTC
Labels: needs-info

**Comment by DanAlbert** [comment] 2018-10-19 04:57
As for what you can do about it on your end, I'd probably look at whatever method you're using to detect leaks. Probably would also be informative to see how valgrind or some other leak detector behaves with libc++'s std::thread.

**Comment by bhupeshpant19jan** [comment] 2018-10-20 08:04
Appreciate you for your efforts and time for investigating this issue.

**Comment by Charles90900** [comment] 2019-09-14 03:02
[https://cloudbl.txt](https://github.com/android/ndk/files/3612290/https.cloudbl.txt)

**Comment by Charles90900** [comment] 2019-09-14 03:04
[PP_Q22018_April_EN.pdf](https://github.com/android/ndk/files/3612294/PP_Q22018_April_EN.pdf)
 

- [ ] [#[](url)](url)
