### ISSUE TITLE
Any good way to speed up Clang-tidy Scan in AOSP build?

### ISSUE THREAD

**Issue by butterl** [android-ndk/ndk#665] opened 2018-04-08 03:44 UTC
#### Description
I'm now running Clang-tidy in AOSP build and failed to generate  compile_commands.json 
so I wrote a workaround test script to generate from the ninja files. The keyword is like
"description = host cross C++: host_cross_libsimpleperf_64"  which really generate the source file in the ninja file, and  ninja_file is what generated from ninja build.
```
#!/bin/bash
keyword=$1
ninja_file=$2
compdb_file="compile_commands.json"

if [ -f "$compdb_file" ]; then rm -f $compdb_file; fi
lines=(`grep -nr "$keyword" $ninja_file | awk -F ":" '{print $1}'`)
rules=""

for line in ${lines[@]}; do
    check=`expr $line - 1`p
    rule=`sed -n $check $ninja_file | awk -F " " '{print $2}'`
    echo $rule
    rules="$rules $rule"
done
echo "Generating..."
ninja -f $ninja_file -t compdb $rules >> $compdb_file
```
but the compile_commands.json went error reading value "command" with [clang-diagnostic-error] when running run-clang-tidy.py in the prebuilts. 

I searched the build scripts and find WITH_TIDY=1;WITH_TIDY_ONLY=1; could be used when build to trigger clang-tidy scan. The scan is OK but the it would run all the dependence not only the target repo, and it's really slow.
 
Is there any good instruction to generate good compile_commands.json or faster way to generate result with AOPS build？

Thanks 
#### Environment Details
* NDK Version: same as the newest AOSP integrated 
* Build system: AOSP build system 
* Host OS: Ubuntu 16.04
* Compiler: Clang from the AOSP prebuilts folder .
* ABI:
* STL:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment] 2018-04-08 05:10
Closing as we don't track the platform build here, just the NDK.

@stephenhines: what's the right place for people to file platform clang-tidy bugs?

**Closed by DanAlbert** 2018-04-08 05:10 UTC

**Comment by stephenhines** [comment] 2018-04-09 20:40
https://issuetracker.google.com/issues/new?component=192763&template=0 goes to Android Public Tracker > App Development > SDK > NDK

There isn't really a platform tool component for clang-tidy, but I think it would be fine to put future requests there (and then assign to my team). For this issue, however, I don't think there is much that we can do. Changing an environment variable does trigger files to get rebuilt. In this case, because WITH_TIDY affects compilation, nearly everything gets rebuilt (and has clang-tidy run on it as well). Incremental builds after that should be reasonably fast unless you touch a common header or just a lot of files. Clang-tidy does a lot of analysis to detect issues, so it isn't going to be very fast, and is unfortunately more likely to keep getting slower as the checks are improved.

**Comment by DanAlbert** [comment] 2018-04-09 20:45
> because WITH_TIDY affects compilation

That sounds like a bug. Are you saying it affects the regular non-tidy parts of the build?

**Comment by stephenhines** [comment] 2018-04-09 20:48
It's not a bug. It's unimplemented to have multiple compilation steps in Soong today, so we just trigger a clang-tidy compilation alongside the regular compilation. There are plans to separate this out, but it is most certainly a feature.

**Comment by DanAlbert** [comment] 2018-04-09 20:52
They're different output files though. Ninja isn't going to rebuild all of your .o files just because it needs to re-run clang-tidy unless something about the clang++ command changed.

**Comment by stephenhines** [comment] 2018-04-09 23:10
You can just set WITH_TIDY=1 and run "mm" in a subdirectory to only apply clang-tidy to those files (although it will also build their dependencies). Yet another option is to just add the flags and tidy request directly to the project/defaults that you want to check. Take a look at https://android.googlesource.com/platform/frameworks/native/+/master/cmds/installd/Android.bp#38 for how this can be customized too.
