### ISSUE TITLE
ndk produces problematic DF_1_PIE flag

### ISSUE THREAD

**Issue by zx2c4** [android-ndk/ndk#602] opened 2017-12-18 04:31 UTC
This linker warning comes up when running executables compiled using the ndk's cmake:

```
$ /path/to/executable
WARNING: linker: /path/to/executable: unsupported flags DT_FLAGS_1=0x8000001
```

This problem is not present in older versions of the ndk. The following sequence will reproduce this bug:

```
zx2c4@thinkpad /tmp/ndkfail $ grep Revision /opt/android-sdk-update-manager/ndk-bundle/source.properties 
Pkg.Revision = 16.1.4479499
zx2c4@thinkpad /tmp/ndkfail $ adb shell getprop ro.build.version.release
7.1.2
zx2c4@thinkpad /tmp/ndkfail $ adb shell getprop ro.build.version.sdk
25

zx2c4@thinkpad /tmp/ndkfail $ echo -e '#include <stdio.h>\nint main() { puts("hello world"); return 0; }' > a.c
zx2c4@thinkpad /tmp/ndkfail $ echo -e 'cmake_minimum_required(VERSION 3.4.1)\nadd_executable(a a.c)' > CMakeLists.txt

zx2c4@thinkpad /tmp/ndkfail $ /opt/android-sdk-update-manager/cmake/3.6.4111459/bin/cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/opt/android-sdk-update-manager/ndk-bundle -DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk-update-manager/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/opt/android-sdk-update-manager/cmake/3.6.4111459/bin/ninja "-GAndroid Gradle - Ninja" .
CMake Warning at /opt/android-sdk-update-manager/ndk-bundle/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  /opt/android-sdk-update-manager/ndk-bundle
Call Stack (most recent call first):
  /opt/android-sdk-update-manager/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt


-- Check for working C compiler: /opt/android-sdk-update-manager/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /opt/android-sdk-update-manager/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/android-sdk-update-manager/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /opt/android-sdk-update-manager/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ndkfail

zx2c4@thinkpad /tmp/ndkfail $ ninja -v
[1/2] /opt/android-sdk-update-manager/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang  --target=aarch64-none-linux-android --gcc-toolchain=/opt/android-sdk-update-manager/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-sdk-update-manager/ndk-bundle/sysroot   -isystem /opt/android-sdk-update-manager/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIE -MD -MT CMakeFiles/a.dir/a.c.o -MF CMakeFiles/a.dir/a.c.o.d -o CMakeFiles/a.dir/a.c.o   -c /tmp/ndkfail/a.c
[2/2] : && /opt/android-sdk-update-manager/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang  --target=aarch64-none-linux-android --gcc-toolchain=/opt/android-sdk-update-manager/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-sdk-update-manager/ndk-bundle/sysroot -isystem /opt/android-sdk-update-manager/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot /opt/android-sdk-update-manager/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc -pie -fPIE CMakeFiles/a.dir/a.c.o  -o a  -latomic -lm && :

zx2c4@thinkpad /tmp/ndkfail $ adb push a /data/local/tmp
a: 1 file pushed. 1.5 MB/s (9400 bytes in 0.006s)
zx2c4@thinkpad /tmp/ndkfail $ adb shell /data/local/tmp/a
WARNING: linker: /data/local/tmp/a: unsupported flags DT_FLAGS_1=0x8000001
hello world
```

**Comment by enh** [comment] 2017-12-18 23:48
`-D__ANDROID_API__=21` implies you're targeting 21, which only supports PIE executables.

**Comment by DanAlbert** [comment] 2017-12-18 23:50
There's not enough information to tell what really went wrong here. Please provide the information that was in the bug template that you deleted.

> -D__ANDROID_API__=21 implies you're targeting 21, which only supports PIE executables.

And also that you don't want to run on any device running KitKat or older.

**Comment by zx2c4** [comment] 2017-12-19 00:32
With the exception of the Host OS (which shouldn't matter), all this information is in or implied by the original post. Here it is in the form requested, though.

* NDK Version: 16.1.4479499
* Build sytem: cmake
* Host OS: Gentoo Linux, kernel 4.14.3
* Compiler: This is using the NDK's compiler - Clang 5.0.300080
* ABI: aarch64
* STL: no C++ code
* NDK API level: 21
* Device API level: 25

> -D__ANDROID_API__=21 implies you're targeting 21, which only supports PIE executables.

That's fine with me. The issue is that it's creating executables that elicit that linker warning. The reproducer above should make it pretty simple to see for yourself, if you're curious.

**Comment by rprichard** [comment] 2017-12-19 00:55
Using an r16b standalone toolchain, I see the 0x08000000 flag in ARM64 PIE binaries. The flag isn't set for non-PIE binaries, nor is it set for ARM or x86_64 binaries. The flag appears with `-fuse-ld=bfd` but not with `-fuse-ld=gold`.

Using an r15c standalone toolchain, the flag isn't set.

I'll see if I can reproduce the linker warning.

**Comment by rprichard** [comment] 2017-12-19 01:16
I reproduced the linker warning:
```
WARNING: linker: /data/local/tmp/a.out: unsupported flags DT_FLAGS_1=0x8000000
```

```
$ adb shell getprop ro.build.fingerprint
Android/aosp_sailfish/sailfish:7.1.2/N2G48I/4477536:userdebug/test-keys
$ adb shell getprop ro.build.version.sdk
25
```

The warning was fixed here: https://android-review.googlesource.com/c/platform/bionic/+/259790. I'm guessing that fix is in O.

Do we need to change the NDK bfd linker to stop setting the flag?

**Comment by rprichard** [comment] 2017-12-19 01:42
> The flag isn't set for non-PIE binaries, nor is it set for ARM or x86_64 binaries.

Nevermind, the problem applies to the bfd linker in all architectures. Some architectures default to ld.gold. Maybe it'd be sufficient to switch the default linker to ld.gold? https://github.com/android-ndk/ndk/issues/556.

It looks like DF_1_PIE was initially a fix for Solaris 12: https://sourceware.org/ml/binutils/2015-09/msg00235.html.

I'm not sure which Android versions are affected. e.g. The warning doesn't exist in KitKat.

**Comment by zx2c4** [comment] 2017-12-19 01:45
Seems like the best thing to do would be to just modify bfd to not set the flag.

**Comment by topjohnwu** [comment] 2017-12-21 07:55
@zx2c4 I'm fed up with the new NDK versions, they compile binaries with weird flags. For example binaries compiled with newer NDK versions will cause `DT_ENTRY` (or `DT_FLAG` can't remember) linker warnings on Android 5.1. And recently NDK r16 will cause `DT_ENTRY` warnings on Samsung and OnePlus devices.

I'm no expert in these stuffs and super frustrated. I rolled all the way back to NDK r10e. It has SDK 21 support, which is all I need, and the binaries compiled with it have no issues whatsoever.

**Comment by rprichard** [comment] 2017-12-21 09:21
> For example binaries compiled with newer NDK versions will cause DT_ENTRY (or DT_FLAG can't remember) linker warnings on Android 5.1.

I noticed that when I was working on this issue. https://android-review.googlesource.com/c/toolchain/binutils/+/571550#message-07efb48b6e8c26830153ec7ae05384dfb2acf14a:

> with the API-22 emulator, the system linker also complains about the VERNEED and VERNEEDNUM entries. The warning doesn't appear with 21 or 23. API 22 is 20.2% on the dashboard.
>
>    WARNING: linker: ./a.out: unused DT entry: type 0x6ffffffe arg 0x2e0
>    WARNING: linker: ./a.out: unused DT entry: type 0x6fffffff arg 0x1

I think it has something to do with a "LIBC" version marker on symbols in the NDK libc.so stub libraries.

> And recently NDK r16 will cause DT_ENTRY warnings on Samsung and OnePlus devices.

Maybe this is the same problem as above? Can you share specific warnings and OS versions?

**Comment by andrejku** [comment] 2018-01-19 11:12
Late to the party.
I've been stumbling upon "WARNING: linker: <executable_name> unsupported flags DT_FLAGS_1=0x8000001" too.
I've been getting this warning on following devices: HTC Nexus 9, Samsung Galaxy S6, but **not** on LG Nexus 5x.
Seems to appear only on arm64-v8a, with newest NDK versions (r16 and r16b), r14b works fine.
The warning appears even with basic Hello World app. Do you want me to provide more details or a sample to reproduce?

**Comment by rprichard** [comment] 2018-01-20 05:25
@andrejku I don't think we need more details -- that looks like the issue. The 0x8000000 flag is DF_1_PIE, which results in the warning on Android versions L MR1 through N MR1 inclusive.

My fix was merged into the toolchain/binutils AOSP repo (but not upstream binutils, unfortunately), which turns off the DF_1_PIE flag. We just need to update the gcc and/or binutils in the NDK prebuilts.

**Comment by rprichard** [comment] 2018-01-20 08:11
I split off the DT entry problem into its own issue: https://github.com/android-ndk/ndk/issues/622.

**Comment by hacker1024** [comment] 2018-01-24 06:12
Hi, noob here. I just want to make sure that this warning is only a warning and won't cause errors in programs?

**Comment by DanAlbert** [comment] 2018-01-24 06:21
It's only a warning that the version of Android you're running in doesn't understand the flag. I doesn't cause any errors.

**Comment by zx2c4** [comment] 2018-01-24 10:28
Unless you're relying on having a clean stderr, in which case this bug is super annoying.

**Comment by rprichard** [comment] 2018-02-05 21:19
The DF_1_PIE warnings should be fixed in r17 beta1. (Binaries will still have version markers that cause warnings on L MR1 only.)

https://android-review.googlesource.com/c/toolchain/binutils/+/571550
https://android-review.googlesource.com/c/platform/prebuilts/ndk/+/601016
https://android-review.googlesource.com/c/platform/prebuilts/ndk/+/601094

**Closed by rprichard** 2018-02-05 21:19 UTC

**Comment by rprichard** [comment] 2023-05-24 23:36
This issue regressed somewhat in NDK r22. LLD in r22 adds DF_1_PIE while LLD in r21e did not. That means:
 - With r21e, binaries only warn on L MR1 only, about DT_GNU_HASH, DT_VERNEED, and DT_VERNEEDNUM (`unused DT entry`).
 - With r22, binaries produce the same `unused DT entry` warnings for L MR1, but they _also_ produce a DF_1_PIE warning on L MR1 to N MR1, inclusive. (`unsupported flags DT_FLAGS_1=0x8000001`)

https://reviews.llvm.org/D80872

quoting @maskray:
> Not affected. Many people think that the spirit of ELF is to ignore what you don't use.

Maybe these two Bionic warnings should be removed from the current loader so we don't create another version of this bug later?

IIRC, there might have been a way to avoid the version tag issue by doing something unusual in the stubs. We'd _also_ have to set `--hash-style=sysv` unless the min-API is 23 or greater. Not sure if this is reasonable. Currently the driver uses `--hash-style=both` for min-API less than 23, because we want GNU hashes available when the binary runs on a newer device.

IIRC, LLD doesn't know it's targeting Android. I suppose it'd be easy to just stop setting DT_1_PIE unconditionally in Android's build of LLD.
