### ISSUE TITLE
implicit declaration of function 'mmap'

### ISSUE THREAD

**Issue by don11995** [android-ndk/ndk#503] opened 2017-09-02 23:43 UTC
**Description**

Hello! I'm trying to build latest ffmpeg binary with NDK r15. While compiling there is an error:
`error: implicit declaration of function 'mmap' [-Werror=implicit-function-declaration]`

I think, there is an error in ifdef block in `sys/mman.h` file:
```
#if defined(__USE_FILE_OFFSET64)

#if __ANDROID_API__ >= 21
void* mmap(void*, size_t, int, int, int, off_t) __RENAME(mmap64) __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */

#else
void* mmap(void*, size_t, int, int, int, off_t);
#endif
```
If I write `mmap` declaration out of the ifdef block in `sys/mman.h` - library compiles correctly.

**Environment Details**

NDK Version: 15.2.4203891
Build system: standalone toolchain
Host OS: Windows 10 x64
Compiler: Clang
ABI: x86
STL: none
NDK API Level: 16
Device API level: Android Studio Emulator API 23

**Comment by alexcohn** [comment] 2017-09-04 14:23
This seems to be duplicate of https://github.com/android-ndk/ndk/issues/477

**Closed** 2017-09-06 00:49 UTC
