### ISSUE TITLE
NDK r11 for Linux size / hash mismatch

### ISSUE THREAD

**Issue by aaaaalbert** [android-ndk/ndk#22] opened 2016-03-15 19:19 UTC
[The NDK download page](https://developer.android.com/ndk/downloads/index.html) currently reports the file size and SHA1 hash for Linux 64-bit (x86) `android-ndk-r11-linux-x86_64.zip` as 794012672 and `7b4e0d13f6bbf48dd87475be9d052273dc766fb6`, respectively.

When I download the file, it is *796414803* bytes instead, and hashes to `8583ff5c22af1603129a6ec35afd3d51163e3fc1`. (Tried downloading on Mac OS X 10.11.3 with both Firefox 45.0 and GNU Wget 1.17.1, same result).

Can you confirm?

**Comment by DanAlbert** [comment] 2016-03-15 19:31
So, the problem is that the website and the downloads are out of sync. There was a SNAFU in updating the packages, but the docs push went live anyway :(

I've been chasing this all morning, and it looks like it's finally being resolved. Should be fixed any time now.

**Comment by DanAlbert** [comment] 2016-03-15 19:54
New packages are live, SHAs match. Sizes apparently don't... I guess they're wrong on the docs end of things.

**Comment by aaaaalbert** [comment] 2016-03-16 09:34
Thanks for looking into this! I redownloaded the file and get the appropriate hash of `7b4e0d...` now. Actual file size is 794012655 which indeed is different from what's currently listed (and also from what I reported yesterday).

If you don't mind, I'll leave the issue open until the numbers match.

**Comment by DanAlbert** [comment] 2016-03-17 21:05
r11 is live and the sizes and SHAs match now: http://developer.android.com/ndk/downloads/index.html#download

**Closed by DanAlbert** 2016-03-17 21:05 UTC
Labels: docs

**Comment by aaaaalbert** [comment] 2016-03-17 22:08
Yup, fixed now. Thank you!
