### ISSUE TITLE
Compiler errors when providing -stdlib=libc++ to Clang / NDK 16 Beta 2

### ISSUE THREAD

**Issue by davidschreiber** [android-ndk/ndk#564] opened 2017-11-02 20:24 UTC
#### Description

After updating from NDK r15c to NDK 16 Beta 2 we experienced compile errors from missing standard library symbols. After investigating, we found out that it's related to existing `-stdlib=libc++` compile argument that were emitted by our CMake setup and provided to `clang++`.

After removing these `-stdlib` arguments from the compile commands (and since that worked from our CMake setup too) our builds seem to work fine again.

My question (for understanding): What change in the update to NDK 16 could have caused this behavior? We have been using unified headers, with `clang` and `c++_static` since NDK r15b without problems. Is this related to the new `libc++` in NDK 16?

To me it seemed that after updating, adding `-stdlib=libc++` causes Clang to use the wrong standard lib headers, or in a wrong order. But why would it have work previously?

#### Environment Details

* NDK Version: 16.0.4414007-beta2
* Build sytem: cmake
* Host OS: Mac
* Compiler: Clang
* ABI: -
* STL: libc++
* NDK API level: 19
* Device API level: minSdk 19, targetSdk 26

**Comment by DanAlbert** [comment] 2017-11-02 20:40
What errors?

**Comment by davidschreiber** [comment] 2017-11-02 21:12
As an example, here's one of the compiler commands generated by CMake, including the invalid `-stdlib=libc++` flag. This is just one example (from the `boost` library we compile) since our project consists of several CMake projects, which all have similar errors (i.e. missing symbols from the standard library).

```
/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=i686-none-linux-android --gcc-toolchain=/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/toolchains/x86-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sysroot  -DBOOST_ALL_NO_LIB -DBOOST_THREAD_DONT_PROVIDE_THREAD_DESTRUCTOR_CALLS_TERMINATE_IF_JOINABLE -DBOOST_THREAD_PROVIDES_EXECUTORS -DBOOST_THREAD_VERSION=4 -DDEBUG -DFMT_EXCEPTIONS=0 -DFMT_USE_NOEXCEPT=1 -D__ANDROID__ -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/Workspace/project/PSPDFCore/generated-jni -I/Workspace/project/PSPDFCore/PSPDFCore -I/Workspace/project/Vendor/boost/. -I/Workspace/project/Vendor/boost -isystem /Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/cxx-stl/llvm-libc++/include -isystem /Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/android/support/include -isystem /Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/cxx-stl/llvm-libc++abi/include  -isystem /Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=19 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions  -O0 -fno-limit-debug-info  -fPIC   -std=c++14 -fdata-sections -ffunction-sections -Wno-deprecated-register -Wno-undefined-bool-conversion -stdlib=libc++ -std=gnu++14 -o CMakeFiles/boost.dir/libs/thread/future.cpp.o -c /Workspace/project/Vendor/boost/libs/thread/future.cpp
```

Here's the error generated by clang:

```
In file included from /Workspace/project/Vendor/boost/libs/thread/future.cpp:6:
In file included from /Workspace/project/Vendor/boost/./boost/thread/detail/config.hpp:11:
In file included from /Workspace/project/Vendor/boost/./boost/config.hpp:57:
In file included from /Workspace/project/Vendor/boost/./boost/config/platform/linux.hpp:15:
In file included from /Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/cxx-stl/llvm-libc++/include/cstdlib:86:
In file included from /Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/cxx-stl/llvm-libc++/include/stdlib.h:94:
/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/android/support/include/stdlib.h:44:44: error: unknown type name 'locale_t'
long double strtold_l(const char*, char**, locale_t);
                                           ^
/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/android/support/include/stdlib.h:45:47: error: unknown type name 'locale_t'
long long strtoll_l(const char*, char**, int, locale_t);
                                              ^
/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/android/support/include/stdlib.h:46:57: error: unknown type name 'locale_t'
unsigned long long strtoull_l(const char*, char**, int, locale_t);
                                                        ^
/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/android/support/include/stdlib.h:53:38: error: unknown type name 'locale_t'
double strtod_l(const char*, char**, locale_t);
                                     ^
/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/android/support/include/stdlib.h:54:37: error: unknown type name 'locale_t'
float strtof_l(const char*, char**, locale_t);
                                    ^
/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/android/support/include/stdlib.h:55:41: error: unknown type name 'locale_t'
long strtol_l(const char*, char**, int, locale_t);
                                        ^
/Users/davidschreiber/Library/Android/sdk/ndk-bundle-r16beta2/sources/android/support/include/stdlib.h:56:51: error: unknown type name 'locale_t'
unsigned long strtoul_l(const char*, char**, int, locale_t);
```

**Comment by DanAlbert** [comment] 2017-11-02 22:06
Interesting. You shouldn't need `-stdlib=libc++` to use libc++ in the NDK, the cmake toolchain should be handling that for you. That said, it shouldn't break things either :)

**Comment by davidschreiber** [comment] 2017-11-03 09:24
Our NDK r15c build works just fine too when dropping the `-stdlib=libc++` argument. So it seems like something about the argument and the include paths changed with the latest `clang` in NDK. Is there a way to dump/print the include paths `clang` uses so I could compare them?

**Comment by DanAlbert** [comment] 2017-11-03 18:09
Clang wasn't updated in r16. Adding `-v` to your cflags will put clang into verbose mode where it dumps information about includes paths (among other things).

I don't think I'd changed anything in how we use libandroid_support in r16, but tbh most of the work on r16 happened about a quarter ago now, so my memory is a little foggy :) I'll take a look at this soon.

**Comment by DanAlbert** [comment] 2017-11-06 21:42
Trivial repro: https://gist.github.com/DanAlbert/001ecf9d4cc2ed335fe938e40d9cad65

**Comment by DanAlbert** [comment] 2017-11-06 22:19
Looks like the reason for the change is that our supposedly not updated Clang got updated: https://android-review.googlesource.com/c/platform/prebuilts/clang/host/linux-x86/+/409069

With that directory present, we get:

```
#include "..." search starts here:
#include <...> search starts here:
 /work/src/ndk/out/android-ndk-r17-canary/sources/cxx-stl/llvm-libc++/include
 /work/src/ndk/out/android-ndk-r17-canary/sources/android/support/include
 /work/src/ndk/out/android-ndk-r17-canary/sources/cxx-stl/llvm-libc++abi/include
 /work/src/ndk/out/android-ndk-r17-canary/sysroot/usr/include/arm-linux-androideabi
 /work/src/ndk/out/android-ndk-r17-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/../include/c++/v1 <-- this one is new
 /work/src/ndk/out/android-ndk-r17-canary/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include
 /work/src/ndk/out/android-ndk-r17-canary/sysroot/usr/include
End of search list.
```

Clang will use it with -std=libc++. That's a bad thing, because those libc++ headers are not the same as the ones we ship in the NDK (while the code bases are pretty much the same, the exact revision used in the toolchain build might differ from the one in the NDK, and there are still a few local configuration changes in the NDK).

@davidschreiber: The reason you pass this flag is just because you do that on other platforms, right? The quick fixes that I could do for r16 would be to either delete that directory in the NDK (it shouldn't be used anyway; if it gets used, that's a problem) or to append `-stdlib=libstdc++` after all the user's flags so the compiler doesn't use `-stdlib=libc++` in the first place. The former reverts to the r15 behavior, but the latter may be what we want long term anyway (though soon it's going to be `-stdlib=none`, we just don't have a clang up to date enough for that flag yet).

**Comment by DanAlbert** [comment] 2017-11-06 22:48
https://android-review.googlesource.com/#/c/platform/ndk/+/529820 fixes this. I'm a little hesitant to pull this into r16, but I think I will since this corrects a regression.

**Comment by davidschreiber** [comment] 2017-11-08 19:02
The reason we had the flags in the first place is, as far as I can remember, that there was some issue with an earlier NDK version (one of NDK 14/15) that would not build properly without it. We've now removed the flag for Android but kept it on our other platforms.

**Comment by DanAlbert** [comment] 2017-11-08 19:21
Okay, that works. This is fixed in r16 and I've added a regression test, so it shouldn't cause any harm now.

**Comment by DanAlbert** [comment] 2017-11-08 19:22
(leaving this open until the patch actually merges into r16, it's running through presubmit right now)

**Comment by DanAlbert** [comment] 2017-11-14 22:27
This got merged a while ago and I forgot to close the bug. r16 is now released.

**Closed by DanAlbert** 2017-11-14 22:27 UTC
Labels: cmake
