### ISSUE TITLE
NDK platform static libraries need to be updated

### ISSUE THREAD

**Issue by enh** [android-ndk/ndk#272] opened 2016-12-24 18:47 UTC
looks like the libc.a files haven't changed since API level 21? (and before that, not since 9?)

```
/tmp/android-ndk-r14-beta1$ find platforms/ -name libc.a | xargs sha1sum | sort
303952da61b721445bd36783a65a12f252bb80c1  platforms/android-21/arch-mips64/usr/lib64/libc.a
303952da61b721445bd36783a65a12f252bb80c1  platforms/android-22/arch-mips64/usr/lib64/libc.a
303952da61b721445bd36783a65a12f252bb80c1  platforms/android-23/arch-mips64/usr/lib64/libc.a
303952da61b721445bd36783a65a12f252bb80c1  platforms/android-24/arch-mips64/usr/lib64/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-12/arch-arm/usr/lib/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-13/arch-arm/usr/lib/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-14/arch-arm/usr/lib/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-15/arch-arm/usr/lib/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-16/arch-arm/usr/lib/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-17/arch-arm/usr/lib/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-18/arch-arm/usr/lib/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-19/arch-arm/usr/lib/libc.a
4fb38c3f717236f53e26f25bc47cd1f4455c83c9  platforms/android-9/arch-arm/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-12/arch-x86/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-13/arch-x86/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-14/arch-x86/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-15/arch-x86/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-16/arch-x86/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-17/arch-x86/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-18/arch-x86/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-19/arch-x86/usr/lib/libc.a
53f7fd97112dc262479057d35de112afd001e4ed  platforms/android-9/arch-x86/usr/lib/libc.a
5981f99cea41a70401f6c87bd5d47916cea1d6ae  platforms/android-21/arch-arm/usr/lib/libc.a
5981f99cea41a70401f6c87bd5d47916cea1d6ae  platforms/android-22/arch-arm/usr/lib/libc.a
5981f99cea41a70401f6c87bd5d47916cea1d6ae  platforms/android-23/arch-arm/usr/lib/libc.a
5981f99cea41a70401f6c87bd5d47916cea1d6ae  platforms/android-24/arch-arm/usr/lib/libc.a
5a209620ce2d805cbe29bc3b5a122731ce930a1a  platforms/android-21/arch-x86_64/usr/lib/libc.a
5a209620ce2d805cbe29bc3b5a122731ce930a1a  platforms/android-21/arch-x86/usr/lib/libc.a
5a209620ce2d805cbe29bc3b5a122731ce930a1a  platforms/android-22/arch-x86_64/usr/lib/libc.a
5a209620ce2d805cbe29bc3b5a122731ce930a1a  platforms/android-22/arch-x86/usr/lib/libc.a
5a209620ce2d805cbe29bc3b5a122731ce930a1a  platforms/android-23/arch-x86_64/usr/lib/libc.a
5a209620ce2d805cbe29bc3b5a122731ce930a1a  platforms/android-23/arch-x86/usr/lib/libc.a
5a209620ce2d805cbe29bc3b5a122731ce930a1a  platforms/android-24/arch-x86_64/usr/lib/libc.a
5a209620ce2d805cbe29bc3b5a122731ce930a1a  platforms/android-24/arch-x86/usr/lib/libc.a
5f17a5b10001698571ffe98e58fdfe709b7b79b2  platforms/android-21/arch-x86_64/usr/lib64/libc.a
5f17a5b10001698571ffe98e58fdfe709b7b79b2  platforms/android-22/arch-x86_64/usr/lib64/libc.a
5f17a5b10001698571ffe98e58fdfe709b7b79b2  platforms/android-23/arch-x86_64/usr/lib64/libc.a
5f17a5b10001698571ffe98e58fdfe709b7b79b2  platforms/android-24/arch-x86_64/usr/lib64/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-12/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-13/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-14/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-15/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-16/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-17/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-18/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-19/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-21/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-22/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-23/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-24/arch-mips/usr/libr6/libc.a
72c485139dd3f3ed98654050cddce0f37e8f2f0d  platforms/android-9/arch-mips/usr/libr6/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-12/arch-mips/usr/lib/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-13/arch-mips/usr/lib/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-14/arch-mips/usr/lib/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-15/arch-mips/usr/lib/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-16/arch-mips/usr/lib/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-17/arch-mips/usr/lib/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-18/arch-mips/usr/lib/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-19/arch-mips/usr/lib/libc.a
90bc2a46746e5f76bec141b6e24e4c8ef0a5ad10  platforms/android-9/arch-mips/usr/lib/libc.a
a94b8664771de0db1c0bbe1da4f54158f3562be5  platforms/android-21/arch-arm64/usr/lib/libc.a
a94b8664771de0db1c0bbe1da4f54158f3562be5  platforms/android-22/arch-arm64/usr/lib/libc.a
a94b8664771de0db1c0bbe1da4f54158f3562be5  platforms/android-23/arch-arm64/usr/lib/libc.a
a94b8664771de0db1c0bbe1da4f54158f3562be5  platforms/android-24/arch-arm64/usr/lib/libc.a
fafb113df91ed07126abfe9fbfa8cfbe0999e396  platforms/android-21/arch-mips/usr/lib/libc.a
fafb113df91ed07126abfe9fbfa8cfbe0999e396  platforms/android-22/arch-mips/usr/lib/libc.a
fafb113df91ed07126abfe9fbfa8cfbe0999e396  platforms/android-23/arch-mips/usr/lib/libc.a
fafb113df91ed07126abfe9fbfa8cfbe0999e396  platforms/android-24/arch-mips/usr/lib/libc.a
/tmp/android-ndk-r14-beta1$ 
```

hit while trying to build toybox with NDK r14beta1 using --unified-headers. we'd get references to stuff (even including stderr) that isn't in the libc.a file.

**Comment by yan12125** [comment] 2016-12-25 05:11
> we'd get references to stuff (even including stderr) that isn't in the libc.a file.

Did you specify -D__ANDROID_API__=XX?

From https://android.googlesource.com/platform/ndk.git/+/master/docs/UnifiedHeaders.md:

> Pass `-D__ANDROID_API__=$API` when compiling. This define used to be provided
   by `<android/api-level.h>`, but with only one set of headers this is no
   longer possible. In the future we will look in to adding `-mandroid-version`
   or similar to Clang so this is automatic.

I've got the same error before. The reason is that in stdio.h, stderr have different names before and after API 23:
```C
#if __ANDROID_API__ >= 23
extern FILE* stdin __INTRODUCED_IN(23);
extern FILE* stdout __INTRODUCED_IN(23);
extern FILE* stderr __INTRODUCED_IN(23);

/* C99 and earlier plus current C++ standards say these must be macros. */
#define stdin stdin
#define stdout stdout
#define stderr stderr
#else
/* Before M the actual symbols for stdin and friends had different names. */
extern FILE __sF[] __REMOVED_IN(23);

#define stdin (&__sF[0])
#define stdout (&__sF[1])
#define stderr (&__sF[2])
#endif
```

**Comment by enh** [comment] 2016-12-25 06:31
the point is, both `__sF` and `stdin`/`stdout`/`stderr` should be in a >= 23 libc.a, but they're not. the "new" libc.a files are just copies of the 21 libc.a files, as the hashes show. (it would perhaps have been clearer if i'd also shown an `nm | grep` or something too.)

**Comment by yan12125** [comment] 2016-12-25 06:59
I got it. I was using dynamic linking and libc.so have stdin/stdout/stderr symbols. Now I got linker failures for static linking, too.

**Comment by johannkoenig** [comment] 2017-09-08 17:36
Was this resolved? I do not have linking issues with r14b, but r15c is failing to link stderr/stdout. Using make_standalone_toolchain.py --arch arm

git clone https://chromium.googlesource.com/webm/libvpx
mkdir build
# create toolchain, add to path
CROSS=arm-linux-androideabi- ../libvpx/configure --target=armv7-android-gcc

ivfdec.c.o:ivfdec.c:function file_is_ivf: error: undefined reference to 'stderr'
(among others)

**Comment by enh** [comment] 2017-09-08 17:41
no, no-one is working on updating the libc.a files yet.

if you're linking statically, you'll want to target API < 23. iirc API 21 was the last libc.a update.

**Comment by johannkoenig** [comment] 2017-09-08 18:12
make_standalone_toolchains.py defaults to API 14 for arm (21 for arm64):
WARNING:__main__:Defaulting to target API 14 (minimum supported target for arm)

Using CC=clang CXX=clang++ the build completes successfully.

Adding the api explicitly to the gcc build does work:
CFLAGS=-D__ANDROID_API__=14 LDFLAGS=-D__ANDROID_API__=14 CXXFLAGS=-D__ANDROID_API__=14

so maybe the default API is not treated the same way between r14b and r15c?

**Comment by yan12125** [comment] 2017-09-09 14:48
Might be related to a known issue [1]:

>  * Standalone toolchains using GCC are not supported out of the box. To use GCC, pass -D__ANDROID_API__=$API when compiling. Note: this is not something we will be fixing.

[1] https://android.googlesource.com/platform/ndk.git/+/master/docs/UnifiedHeaders.md

**Comment by nargus** [comment] 2017-11-13 18:46
If the libc.a won't be updated to match the unified header of stdio.h in r16, can we not simply "fix" the stdio.h so it define them correctly for the library?

**Comment by enh** [comment] 2017-11-13 18:54
i think you should just switch to clang now. (we're removing GCC in r18 anyway.)

**Comment by DanAlbert** [comment] 2017-11-13 19:02
What does clang have to do with this?

@nargus: no, we can't fix this for static libraries without breaking it for shared libraries, which are the average case by a very wide margin.

**Comment by enh** [comment] 2017-11-13 19:04
(there are two bugs on this bug... it's half forked into "i'm getting the wrong results because i'm using GCC and it doesn't define `__ANDROID_API__`". it's not clear whether nargus has a real problem or it just piling on the GCC problem.)

**Comment by DanAlbert** [comment] 2017-11-13 19:06
Ah, I see. Yeah, the GCC problem is not something we have any intention of fixing. It's been marked as such in the changelog since r14.

**Comment by nargus** [comment] 2017-11-13 19:54
I'm actually already on Clang and has been trying to get my project compiled on the new r16 (beta-2). It's now almost working, except for the stdin/stdout linker errors mentioned above.

**Comment by Adam-VisualVocal** [comment] 2017-11-16 08:18
Same here. I'm trying to compile libjpeg-turbo for armeabi-v7a and I also get the same type of "undefined reference to 'stderr'" errors. I'm using clang.

**Comment by yan12125** [comment] 2017-11-16 08:29
Looks like it's not completely fixed for clang yet: https://android-review.googlesource.com/c/platform/bionic/+/522595

**Comment by DanAlbert** [comment] 2017-11-16 08:38
That's why the bug is still open. Targeting anything newer than android-21 for a static executable is not expected to work regardless of your compiler.

**Comment by nargus** [comment] 2017-11-16 19:50
@Adam-VisualVocal I managed to "fixed" the issue by using --include with my custom header that undef & define the macros back to its pre-API 23. A bit hacky, but works just fine :)

**Comment by DanAlbert** [comment] 2017-11-16 21:18
Why not just target android-21?

**Comment by nargus** [comment] 2017-11-16 21:42
Unfortunately, we actually need 24 :)

**Comment by DanAlbert** [comment] 2017-11-16 21:48
If you're statically linking libc.a, you're not getting it. That's the root cause of this bug.

**Comment by DanAlbert** [comment] 2018-01-29 20:47
This may end up happening for 17 beta 2, but I suspect this is more likely for r18. There's some work that needs to be done to make sure libandroid_support isn't used with libc.a since libc.a already contains everything in libandroid_support.a and will lead to multiple symbol definition errors. Unfortunately given the number of build systems we support I think this is likely to be a fair amount of work.

**Comment by alexcohn** [comment] 2018-01-31 11:18
@DanAlbert I believe you don't need all that many rebuilds of **libc.a**. You drop armeabi and both MIPS for r17, don't you? Then, you don't really care about the versions below API 21: whoever needs these can use the **android-14** binary (they have already found the workarounds, anyway; unified headers hardly worsen the situation here).

**Comment by DanAlbert** [comment] 2018-02-01 17:53
Our plan is to have only one libc.a for each arch going forward (always the latest). So far we haven't been able to come up with any reasons to use an old library.

That still leaves the problem of not being able to link when using libandroid_support.

**Comment by DanAlbert** [comment] 2018-02-14 08:14
Fixed in r17.

**Closed by DanAlbert** 2018-02-14 08:14 UTC
