### ISSUE TITLE
[r12b] Linker error when using luajit with clang & c++_static

### ISSUE THREAD

**Issue by cezheng** [android-ndk/ndk#176] opened 2016-08-04 10:07 UTC
Android NDK r12b's is generating linker error when luajit is present, with clang toolchain & c++_static STL.

The error is like this:

```
[armeabi-v7a] Gdbserver      : [arm-linux-androideabi] libs/armeabi-v7a/gdbserver
[armeabi-v7a] Gdbsetup       : libs/armeabi-v7a/gdb.setup
[armeabi-v7a] Compile++ thumb: hello-jni <= hello-jni.cpp
[armeabi-v7a] SharedLibrary  : libhello-jni.so
/path/to/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /path/to/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a(pr-support.o): multiple definition of '_Unwind_GetRegionStart'
/path/to/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /path/to/android-ndk-r12b/sources/cxx-stl/llvm-libc++abi/../llvm-libc++/libs/armeabi-v7a/libunwind.a(Unwind-EHABI.o): previous definition here
/path/to/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /path/to/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a(pr-support.o): multiple definition of '_Unwind_GetLanguageSpecificData'
/path/to/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /path/to/android-ndk-r12b/sources/cxx-stl/llvm-libc++abi/../llvm-libc++/libs/armeabi-v7a/libunwind.a(Unwind-EHABI.o): previous definition here
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi-v7a/libhello-jni.so] Error 1
```

I have created a demo project to reproduce the problem: https://github.com/cezheng/luajit-failure-ndk-r12b. Detailed info about the demo is written in the README of the repo.

Just clone the project and run ndk-build.

Compiling with gcc 4.9 & gnustl_static seems to be fine.

**Comment by DanAlbert** [comment] 2016-08-04 16:58
There's something temperamental about the link order here. I'm fairly certain I've fixed this in the platform build system before, so hopefully the same solution will work for the NDK.

**Comment by DanAlbert** [comment] 2016-08-11 16:50
Tested with r13-beta1 and it works fine.

**Comment by DanAlbert** [comment] 2016-08-11 16:51
(I was able to repro with r12b though. Not sure exactly what the fix was, but we did redo libc++ in r13.)

**Comment by cezheng** [comment] 2016-08-11 18:00
Thanks, I'll have a try

**Comment by cezheng** [comment] 2016-09-02 05:59
https://github.com/android-ndk/ndk/wiki

I read the r13 release schedule and it says that r13 will be released in Sep. Since beta2 didn't come out in August, I'm not sure if we have have a stable release of r13 this month. Since our project relies on clang & libc++, the newest stable release of NDK that can build our project is r10e. 

However, r10e does not work correctly with precompiled header, and is taking too long to build. Using a beta release of NDK to build production code is somehow scary.

**Comment by DanAlbert** [comment] 2016-09-02 21:41
Apologies for the delay. The QA team has been really busy with Android Studio and we haven't been able to get r13 beta 2 in for testing yet. I'm told it should be doable next week. Assuming we can get this out soon, r13 stable should still be doable for September, but it might be late September depending on the incoming bug rate for r13 beta 2.

I'll update the wiki.

**Comment by cezheng** [comment] 2016-09-08 12:14
Thanks for sharing the process. Cheers:beer:

**Comment by tavianator** [comment] 2016-09-15 22:58
Did anyone ever figure out a workaround for this (other than updating to a beta NDK)?

**Comment by DanAlbert** [comment] 2016-09-15 23:05
It's possible that `c++_shared` works. That may or may not be an acceptable work around for you.

**Comment by cezheng** [comment] 2016-09-15 23:09
Use r10e or wait for r13 stable

**Comment by DanAlbert** [comment] 2016-09-15 23:12
Was this a problem with r11 as well? You'd be better off with r11 than r10 since that was a much better clang.

**Comment by cezheng** [comment] 2016-09-15 23:28
I remember failing to build our project with r11, not sure if it was the same error since that's several months ago.

**Comment by tavianator** [comment] 2016-11-01 14:32
For the record, you can use `-Wl,--allow-multiple-definition` to suppress the error.

**Comment by DanAlbert** [comment] 2016-11-01 15:00
Is this still an issue with r13?

**Comment by tavianator** [comment] 2016-11-01 15:41
I'm still getting this with r13b (is that newer than r13 by the way?  I'm not clear on the versioning scheme)

```
/tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: error: /tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/armv7-a/libgcc.a(pr-support.o): multiple definition of '__gnu_unwind_frame'
/tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: /tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/armv7-a/libunwind.a(Unwind-EHABI.o): previous definition here
/tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: error: /tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/armv7-a/libgcc.a(pr-support.o): multiple definition of '_Unwind_GetRegionStart'
/tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: /tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/armv7-a/libunwind.a(Unwind-EHABI.o): previous definition here
/tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: error: /tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/armv7-a/libgcc.a(pr-support.o): multiple definition of '_Unwind_GetLanguageSpecificData'
/tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: /tmp/ndk-arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/armv7-a/libunwind.a(Unwind-EHABI.o): previous definition here
collect2: error: ld returned 1 exit status
```

**Comment by DanAlbert** [comment] 2016-11-01 15:43
Bummer. Reopening and triaging for r14. This was passing for me at some time in development. I'll have to check on that to make sure it hasn't regressed (I was never able to repro at all, so no test case to add). It's possible that I'm just missing some of the repro steps.

> (is that newer than r13 by the way? I'm not clear on the versioning scheme)

The number is the major release, the letter is a hotfix (r13 is initial release, r13b is first hotfix, and so on).

**Comment by tavianator** [comment] 2016-11-01 16:52
@DanAlbert I have a reproducer here, let me know if it works for you: https://gist.github.com/tavianator/fb34581482ac07292c7918b67b29c4ca

**Comment by DanAlbert** [comment] 2016-11-01 16:55
Thanks! I have a handful of other things in my queue right now, but I'll let you know if this repros when I can find time to look at it.

**Comment by DanAlbert** [comment] 2017-01-06 00:29
Just rechecked the original repo case and it's fine with r13b and r14-beta1.

@tavianator: Given that we can't support the GCC/libc++ combination in standalone toolchains any more (gcc bug), I had to modify your repro case to use Clang. Your link line is missing `-flto` (you can remove the `-lc++_shared`, btw, the toolchains aren't as dumb as they used to be), but if I add that it works with r13b and r14-beta1. I was able to make it fail with r12b and gcc, fwiw.

Anyway, it looks like this is actually fixed now. If I did something wrong with the repro case, please reopen.

**Closed by DanAlbert** 2017-01-06 00:29 UTC
