### ISSUE TITLE
Compilation of assembly files broken

### ISSUE THREAD

**Issue by avs333** [android-ndk/ndk#649] opened 2018-03-12 01:17 UTC
Please fix the include paths for asm files that require preprocessing (*.S). 
Broken since ndk-16, I believe. E.g.:

```
[arm64-v8a] Compile        : lib <= file1.c
[...]  --sysroot /path_to/android-ndk-r17-beta1/sysroot \
-isystem /path_to/android-ndk-r17-beta1/sysroot/usr/include/aarch64-linux-android file1.c

[arm64-v8a] Compile        : lib <= file2.S
[...]  -isystem /path_to/android-ndk-r17-beta1/sysroot/usr/include file2.S
<------ fatal error: asm/unistd.h: No such file or directory

```
(Here, file2.S has "#include <asm/unistd.h>" on the first line.)

**Comment by DanAlbert** [comment] 2018-03-15 22:53
Assuming this is ndk-build based on the output format (it really helps us if you fill out the template rather than delete it; there are a ton of variables involved with building things for Android that can change whether or not your issue reproduces).

```makefile
# Android.mk
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := foo
LOCAL_SRC_FILES := foo.S
include $(BUILD_SHARED_LIBRARY)
```

```asm
// foo.S
#include <asm/unistd.h>
```

Works for me with ndk-build in r16b and trunk. Please include a test case like the bug template asked.

**Comment by rprichard** [comment] 2018-03-16 01:07
It works for me, but only because ndk-build is including `/usr/include/asm/unistd.h`.

The preprocessed assembly block in ndk-build is different from the C and C++ compile blocks:
 - It doesn't specify `--sysroot`
 - It doesn't add the arch-specific include directory.

I was wondering why there was this difference, but maybe there isn't a reason.

### ev-compile-c-source

```
--sysroot $$(call host-path,$$(SYSROOT_INC)) \
$(SYSROOT_ARCH_INC_ARG) \
```

https://android.googlesource.com/platform/ndk/+/5b7d4603f812c9e160094a7d3e3d9be3958f2009/build/core/definitions.mk#1662

### ev-compile-s-source

`-isystem $$(call host-path,$$(SYSROOT_INC)/usr/include)`

https://android.googlesource.com/platform/ndk/+/5b7d4603f812c9e160094a7d3e3d9be3958f2009/build/core/definitions.mk#1690

**Comment by rprichard** [comment] 2018-03-16 01:51
I wonder if our CMake toolchain file has the same bug...

**Comment by avs333** [comment] 2018-03-16 06:55
Dear Dan!

Thank you very much for the answer! Not that I'm really depressed about all that just thought it'd be better if it could be fixed anyway.
A sample project would be, e.g.:  https://avs234.net/lib.tgz

Best regards,
Alexey

**Comment by rprichard** [comment] 2018-04-03 00:04
> I wonder if our CMake toolchain file has the same bug...

Looks like it already does the right thing.

**Comment by avs333** [comment] 2018-04-03 09:46
Heavens, yes, it does!
I didn't even try that because my code won't compile with clang for sure (too much gcc-specific stuff to keep pace with the trends right away). 
But the testcase works OK, indeed.

**Comment by rprichard** [comment] 2018-04-04 00:58
Fixed in https://android-review.googlesource.com/c/platform/ndk/+/654839

**Closed by rprichard** 2018-04-04 00:58 UTC
Labels: ndk-build
