### ISSUE TITLE
[BUG] SIGSEGV in Greedy Register Allocator pass in clang for armv7a with NDK r20

### ISSUE THREAD

**Issue by ngg** [android-ndk/ndk#1044] opened 2019-07-16 11:10 UTC
I'm trying to update our toolchain from using NDK r19 to r20. I've got a SIGSEGV in the compiler when I'm compiling our C++ project to armv7a (API version does not matter). It was working in r19 and it compiles for other architectures on r20 (x86, x64, arm64), but r20 armv7a crashes. I've minimized the C++ code to have no external dependencies or includes. Optimization level matters: it crashes with -O2, -O3, -Os and -Oz, but compiles with -O0, -O1

To reproduce the crash, compile the file below with:
`${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang++ -fstack-protector-strong -O2 -c x.cpp`

```c++
// x.cpp
struct P
{
    long long a;
    long long b;
};
struct S
{
    int b;
    P p;
    P* pp;
};
struct Y
{
    Y();
    ~Y();
};
void g(void*);
struct X
{
    S* t()
    {
        Y y1;
        Y y2;
        g(&y2);
        return 0;
    }

    X()
    {
        g(this);
    }

    ~X()
    {
    }
};
void f(const P& p)
{
    X x;
    auto it = x.t()->pp + 2;
    long long y = p.a;
    long long z = it->a;
    S& s = *x.t();
    long long u = s.p.b + y;
    if (s.p.a != s.p.a - z + y) {
        s.p.a = s.p.a - z + y;
    }
    if (s.p.b != u) {
        s.b = 1;
        s.p.b = u;
    }
    it->a = p.a;
}
```

The crash report looks like:
```
 % ~/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang++ -fstack-protector-strong -O2 -c x.cpp
Stack dump:
0.      Program arguments: /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -cc1 -triple armv7-unknown-linux-android16 -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name x.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature -fp-only-sp -target-feature +d16 -target-feature +vfp3 -target-feature -fp16 -target-feature -vfp4 -target-feature -fp-armv8 -target-feature -neon -target-feature -crypto -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /home/ngglocal/git/TresoritCore/out/android/x.gcno -resource-dir /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/8.0.7 -internal-isystem /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1 -internal-isystem /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/local/include -internal-isystem /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/8.0.7/include -internal-externc-isystem /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/arm-linux-androideabi -internal-externc-isystem /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/include -internal-externc-isystem /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include -O2 -fdeprecated-macro -fdebug-compilation-dir /home/ngglocal/git/TresoritCore/out/android -ferror-limit 19 -fmessage-length 134 -stack-protector 2 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o x.o -x c++ x.cpp 
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'x.cpp'.
4.      Running pass 'Greedy Register Allocator' on function '@_Z1fRK1P'
#0 0x000000000242f066 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x242f066)
#1 0x000000000242dca0 llvm::sys::RunSignalHandlers() (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x242dca0)
#2 0x000000000242f34f (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x242f34f)
#3 0x00007f81daf01680 (/lib64/libpthread.so.0+0x14680)
#4 0x0000000001f159b3 (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1f159b3)
#5 0x0000000001f178ab (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1f178ab)
#6 0x0000000001fc102f (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1fc102f)
#7 0x0000000001fbf3fc (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1fbf3fc)
#8 0x0000000001fc276b (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1fc276b)
#9 0x0000000001fbd710 (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1fbd710)
#10 0x0000000001fbcdc5 (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1fbcdc5)
#11 0x0000000001fb9e42 (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1fb9e42)
#12 0x0000000001fb8335 llvm::RegAllocBase::allocatePhysRegs() (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1fb8335)
#13 0x0000000001fb9cc8 (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1fb9cc8)
#14 0x0000000001e79ec3 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1e79ec3)
#15 0x000000000209208b llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x209208b)
#16 0x00000000020924e3 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x20924e3)
#17 0x00000000020928ad (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x20928ad)
#18 0x000000000209265d llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x209265d)
#19 0x0000000002755c1c (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2755c1c)
#20 0x0000000002753184 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2753184)
#21 0x0000000002936591 (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2936591)
#22 0x000000000307b7a8 clang::ParseAST(clang::Sema&, bool, bool) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x307b7a8)
#23 0x00000000028d0cf5 clang::FrontendAction::Execute() (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x28d0cf5)
#24 0x000000000286db67 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x286db67)
#25 0x0000000002932ff5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x2932ff5)
#26 0x00000000018876d4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x18876d4)
#27 0x0000000001883f22 main (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1883f22)
#28 0x00007f81d9fc929b __libc_start_main (/lib64/libc.so.6+0x2329b)
#29 0x0000000001883029 _start (/home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x1883029)
clang++: error: unable to execute command: Segmentation fault
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7a-unknown-linux-android16
Thread model: posix
InstalledDir: /home/ngglocal/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/x-1ce485.cpp
clang++: note: diagnostic msg: /tmp/x-1ce485.sh
clang++: note: diagnostic msg: 

********************
[1]    13522 exit 254    -fstack-protector-strong -O2 -c x.cpp
```

**Comment by ngg** [comment] 2019-07-16 14:48
I could reproduce this issue on upstream LLVM, and bisecting the git repo showed that the bug was introduced in https://github.com/llvm/llvm-project/commit/d5d0a4d27fbf4b360635fbfa721857e4d698ca28 (r341136) and it is already fixed by https://github.com/llvm/llvm-project/commit/a69084ffa844d09d685a10b7b41a509c309687af (r349693).
r19 was based on r339409 and r20 is based on r346389c, so this seems legit.
Can you tell me an ETA when will be an NDK update available that covers the fix?

**Comment by pirama-arumuga-nainar** [comment] 2019-07-16 16:18
r21 will have a compiler update that covers this fix.

**Comment by ngg** [comment] 2019-07-16 16:31
Current version of https://android.googlesource.com/platform/ndk/+/refs/heads/master/ndk/toolchains.py mentions r349610b which is too old to fix this. That version is also too old to to fix https://github.com/android-ndk/ndk/issues/1010 (that bug was fixed in https://github.com/llvm/llvm-project/commit/dd8cd6d26b1706d83d4aea0c09e46f0e21195de5 r351310)
Will r21 contain r353983 like most other Android uses of LLVM? (according to [README of prebuilt clang](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/README.md))

**Comment by pirama-arumuga-nainar** [comment] 2019-07-16 16:33
@ngg: Yes, r21 will have r353983, if not something newer than that.  @DanAlbert to confirm.

**Comment by pirama-arumuga-nainar** [comment] 2019-07-16 17:27
@ngg If the issue is isolated to a particular function, you can selectively [disable](https://clang.llvm.org/docs/LanguageExtensions.html#extensions-for-selectively-disabling-optimization) optimization to continue your migration to r20.

**Comment by DanAlbert** [comment] 2019-07-16 19:06
Yeah, we're still waiting for a compiler update before we ship r21. We can make sure this is cherry-picked for r21 if the compiler we update to won't be new enough to have the fix already.

**Comment by ngg** [comment] 2019-07-17 06:56
@pirama-arumuga-nainar Thanks for the tip to disable optimizations for some part, I also ran into #1010 which is a blocker issue for us, until it is fixed (it's not a compile error, it just miscompiles code which is much harder to check), we'll wait with the update until both of these are fixed.
@DanAlbert Thanks, sounds good.
Can you label this issue with r21 please?

**Comment by DanAlbert** [comment] 2019-07-17 07:05
Done. Thanks for the reminder.

**Comment by DanAlbert** [comment] 2019-09-04 19:45
Master now has r365631, so this will be in r21.

**Closed by DanAlbert** 2019-09-04 19:45 UTC
Labels: bug, clang
