### ISSUE TITLE
"__ctype_get_mb_cur_max" UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by hoodar** [android-ndk/ndk#576] opened 2017-11-24 02:43 UTC
#### Description

__ANDROID_API__=14 is defined but still got an error message while loading 
library:
E/AndroidRuntime( 8161): FATAL EXCEPTION: main
E/AndroidRuntime( 8161): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__ctype_get_mb_cur_max" referenced by "libxxx.so"...
E/AndroidRuntime( 8161):        at java.lang.Runtime.loadLibrary(Runtime.java:361)
E/AndroidRuntime( 8161):        at java.lang.System.loadLibrary(System.java:525)
E/AndroidRuntime( 8161):        at com.huawei.application.SharkPlayerApplication.onCreate(SharkPlayerApplication.java:39)
E/AndroidRuntime( 8161):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 8161):        at com.lbe.client.zz.ba.callApplicationOnCreate(InstrumentationDelegate.java:168)
E/AndroidRuntime( 8161):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4477)
E/AndroidRuntime( 8161):        at android.app.ActivityThread.access$1300(ActivityThread.java:144)
E/AndroidRuntime( 8161):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
E/AndroidRuntime( 8161):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8161):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 8161):        at android.app.ActivityThread.main(ActivityThread.java:5136)
E/AndroidRuntime( 8161):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 8161):        at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 8161):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 8161):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 8161):        at dalvik.system.NativeStart.main(Native Method)

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: R16
* Build sytem: standalone toolchain
* Host OS: Windows 32bit
* Compiler:  clang
* ABI: armeabi
* STL: libc++
* NDK API level:  14
* Device API level: [ro.build.version.sdk]: [18]

**Comment by enh** [comment] 2017-11-27 15:59
hmm. the support library still has
```
#undef MB_CUR_MAX
size_t __ctype_get_mb_cur_max(void);
#define MB_CUR_MAX __ctype_get_mb_cur_max()
```
in its <stdlib.h>, but doesn't actually define `__ctype_get_mb_cur_max` any more.

**Comment by enh** [comment] 2017-11-27 16:06
(and doesn't seem to have ever done so, so i guess i'm not sure what's going on...)

**Comment by DanAlbert** [comment] 2017-11-27 19:14
Yeah, this doesn't look like it should work. We don't have any test failures caused by this. I guess maybe this doesn't end up getting used in any tests?  Something I'll need to look in to a bit more.

**Comment by rprichard** [comment] 2018-02-23 01:32
I assume this is a duplicate of https://github.com/android-ndk/ndk/issues/544.

**Comment by DanAlbert** [comment] 2018-02-23 07:46
Yep.

**Closed by DanAlbert** 2018-02-23 07:46 UTC
