### ISSUE TITLE
Build ffmpeg 4.0 fails only on toolchain x86

### ISSUE THREAD

**Issue by bolds07** [android-ndk/ndk#715] opened 2018-06-06 22:01 UTC
OS: Ubuntu 16.04
NDK: 17
FFmpeg: 4.0

command to generate toolchain:
```
$NDK/build/tools/make-standalone-toolchain.sh --use-llvm --platform=android-${API_LVL} --install-dir=${TOOLCHAIN} --arch=${ARCH} --stl=libc++  
```

I tested for ARCH= arm, arm64, x86 and x86_64... only x86 fails

ffmpeg compile command:
```

export PKG_CONFIG="$(which pkg-config)"
export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"
export CC="${CROSS_PREFIX}clang"
export CXX="${CROSS_PREFIX}clang++"
export CPP="${CROSS_PREFIX}cpp"
export AR="${CROSS_PREFIX}ar"
export LD="${CROSS_PREFIX}ld"
export NM="${CROSS_PREFIX}nm"
export RANLIB="${CROSS_PREFIX}ranlib"
export STRIP="${CROSS_PREFIX}strip"
export LDFLAGS="-L${PREFIX}/lib -L${TOOLCHAIN}/lib -L${SYSROOT}/usr/lib -fPIE --sysroot=${SYSROOT} "
export CFLAGS="-I${PREFIX}/include -I${SYSROOT}/usr/include -fPIE " 
export CXXFLAGS="${CFLAGS} "
export CPPFLAGS="${CFLAGS} "
export PATH="$PATH:$PREFIX/bin:$NDK/build"
export CROSS_SYSROOT="${SYSROOT}"
  

CROSS_COMPILE_FLAGS="--target-os=linux \
 --arch=${ARCH} \
		--cpu=${CPU} \
 --cross-prefix=${CROSS_PREFIX} \
 --enable-cross-compile \
		--cc=${CC} \
		--cxx=${CXX} \
 --sysroot=$SYSROOT"


 ./configure --prefix=$PREFIX \
 $CROSS_COMPILE_FLAGS \
 --pkg-config=$(which pkg-config) \
 --pkg-config-flags="--static" \
 --enable-pic \
 --enable-gpl \
 --enable-nonfree \
 \
 --disable-shared \
 --disable-static \
 \
 --enable-ffmpeg \
 --disable-ffplay \
 --disable-ffprobe 
	 
	
make clean
make 
make install V=1
```

the error stack is too long, i prefered to attach to a file
[error.txt](https://github.com/android-ndk/ndk/files/2078288/error.txt)

[h264_cabac-edf51d.txt](https://github.com/android-ndk/ndk/files/2078294/h264_cabac-edf51d.txt)

[h264_cabac-edf51d.sh.txt](https://github.com/android-ndk/ndk/files/2078296/h264_cabac-edf51d.sh.txt)

```
clang60: error: unable to execute command: Segmentation fault (core dumped)
clang60: error: clang frontend command failed due to signal (use -v to see invocation)
```

**Comment by pirama-arumuga-nainar** [comment] 2018-06-06 22:06
Duplicate of #693

**Closed by pirama-arumuga-nainar** 2018-06-06 22:06 UTC
