### ISSUE TITLE
Clang include order of header files

### ISSUE THREAD

**Issue by bhupeshpant19jan** [android-ndk/ndk#842] opened 2018-11-12 07:12 UTC
#### Clang header file Include order

I am not getting the desired include path searches in Clang. I have specified the following include paths,

```
 -If:/office/dev/otools/inc/platformsdk/android/clang/ 
-If:/nugetcache/androidndk.16.1.9/sources/cxx-stl/llvm-libc++/include/ 
-If:/nugetcache/androidndk.16.1.9/sources/cxx-stl/llvm-libc++/include/support/android/ 
-If:/nugetcache/androidndk.16.1.9/sysroot/usr/include/ 
-If:/nugetcache/androidndk.16.1.9/sysroot/usr/include/i686-linux-android/
-If:/nugetcache/androidndk.16.1.9/sources/cxx-stl/llvm-libc++/include/ext/ 
-If:/nugetcache/androidndk.16.1.9/sources/cxx-stl/llvm-libc++abi/include/ 
- I...  <Other project specific includes>
```

Now as per my understanding, I expect the clang to search in the above mentioned order, but the search is being made from the current directory to the path onward.

```
2:12] error DX0064: [PipDA585A22CA6241A8, {Compiling xxx.cpp 
In file included from f:\\dev\gdi\gdiplus\engine\ddi\xxx.cpp:19:
In file included from ./precomp.hpp:51:
In file included from F://dev/otools/inc/platformsdk/android/win32port\_math.h:4:
In file included from f:/nugetcache/androidndk.16.1.9/sources/cxx-stl/llvm-libc++/include\math.h:309:
In file included from f:/nugetcache/androidndk.16.1.9/sources/cxx-stl/llvm-libc++/include\type_traits:390:
In file included from f:/nugetcache/androidndk.16.1.9/sources/cxx-stl/llvm-libc++/include\cstddef:44:
In file included from f:/nugetcache/.A/VCCompiler.Headers.2a3ELSDbwsHpIL_7VWfK4g/crt\stddef.h:11:
f:/nugetcache/.A/VCCompiler.Headers.2a3ELSDbwsHpIL_7VWfK4g/crt\corecrt.h(450,39) :  error: typedef redefinition with different types ('unsigned short' vs 'unsigned int')
typedef unsigned short                wint_t;
                                      ^
f:/nugetcache/androidndk.16.1.9/sysroot/usr/include\bits/wctype.h(36,23) :  note: previous definition is here
typedef __WINT_TYPE__ wint_t;
                      ^
```

In the above logs we can clearly see that cstddef include <stddef.h> and from there we again include stddef.h using include_next<>. In this case I expect the searching to be made from the extreme left to right (or as per my list above from top to bottom) . So the search for this file should be first made at clang path and then sysroot and so on.

* NDK Version: 16r
* Build system: Clang
* Compiler: Clang
* STL: libc++
* NDK API level: 21

**Comment by DanAlbert** [comment] 2018-11-12 19:14
Clang isn't a build system. What build system are you using?

**Comment by alexcohn** [comment] 2018-11-13 11:48
I don't think `f:/nugetcache/.A/VCCompiler.Headers.2a3ELSDbwsHpIL_7VWfK4g/` is your current directory. Even if it were, why would it link to Microsoft Windows SDK?

It seems that you are compiling from Visual Studio. Maybe, it injects its inlcude paths for Clang? Maybe your CMake doesn't understand you perform cross-compilation?

**Comment by bhupeshpant19jan** [comment] 2018-11-14 04:29
We write cross -plat code and these VC headers are included to provide cross-plat interfaces.

**Comment by DanAlbert** [comment] 2018-11-14 07:08
You should never include any of those paths manually. That is the job of the build system. If you have to do that manually, there's a bug in your build system. If you're *not* doing that manually, there's still a bug in your build system, because that's not the right order, and most of those need to *not* be explicitly included.

The problem is as Alex pointed out.

````
f:/nugetcache/.A/VCCompiler.Headers.2a3ELSDbwsHpIL_7VWfK4g/crt\corecrt.h(450,39) :  error: typedef redefinition with different types ('unsigned short' vs 'unsigned int')
typedef unsigned short                wint_t;
````

Your project includes an incorrect definition of `wint_t`.

Closing because this does not appear to be any of our build systems (at least, none of ours will cause the above by default, so it would be user error if that's the case). Happy to answer questions, but there's nothing for us to fix in the NDK here.

**Closed by DanAlbert** 2018-11-14 07:08 UTC

**Comment by bhupeshpant19jan** [comment] 2018-11-15 09:52
On that note, can you recommend whether sysroot should come before or after the libc++ includes in, header files include paths?
What would be the implication if I add libc++/includes path before sysroot. I am able to successfully compile the project but could not find any implication of it.

**Comment by bhupeshpant19jan** [comment] 2018-11-16 06:33
A quick check for above query?

**Comment by DanAlbert** [comment] 2018-11-27 04:12
libc++ comes before the sysroot. Dependencies always come after the depender.

**Comment by bhupeshpant19jan** [comment] 2018-11-27 07:06
Thanks, for your reply. Surprisingly our apps have been using it Sysroot earlier than libc++ from sometimes now. I intended to correct it but want to confirm it officially. 
Thanks for your reply Dan, I will also check with the test app to confirm it visually.

**Comment by DanAlbert** [comment] 2018-11-27 07:15
Like I said, check the actual order clang is using with `-v`. `-I`, `-isystem`, and `--sysroot` all have different semantics.
