### ISSUE TITLE
gdb debug couldn't be connected on targetSdkVersion 24.

### ISSUE THREAD

**Issue by pm1100tm** [android-ndk/ndk#224] opened 2016-10-19 07:30 UTC
I find that gdb debug could not be connected on targetSdkVersion 24.
It works on targetSdkVersion 23.
Used sample: https://github.com/googlesamples/android-ndk >> hello-gl2
Is there any workaround?

[Reproduction]
1. Prepare for ant-build: In Terminal >> android update project -p . --target android-24
2. Edit AndroidManifest.xml: <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="24"/>
3. Edit jni/Application.mk( Optional ) APP_ABI := all -> APP_ABI := armeabi-v7a
4. ndk-build NDK_DEBUG=1
5. ant debug >> created bin/GL2JNIActivity-debug.apk
6. Install the apk file to Android7.0 device. 
7. Start gdb In Terminal.

[result]
Error: unable to connect to device.
Remote connection closed.

[My environment]
Android SDK (targetSdkVersion=24)
Android NDK r12b, r13
ant 1.9.4
Nexus 6P ( Android 7.0 )

**Comment by DanAlbert** [comment] 2016-10-19 07:33
> 7. Start gdb In Terminal.

Does this mean you're not using `ndk-gdb`?

**Comment by pm1100tm** [comment] 2016-10-19 08:40
I was using ndk-gdb like this: ndk-gdb --launch --verbose --nowait

**Comment by pm1100tm** [comment] 2016-10-19 09:38
Sorry for repro step 2: 
***Edit AndroidManifest.xml
android:name="GL2JNIActivity"  >>  "com.android.gl2jni.GL2JNIActivity"
and set this: <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="24"/>

**Comment by jmgao** [comment] 2016-10-20 19:32
Can you post the full output from ndk-gdb.py?

**Comment by jmgao** [comment] 2016-10-20 23:53
Looks like this is a permissions issue, the default permission for /data/data/<pkgname> is `rwxr-x--x` on 23, and `rwx------` on 24. (This was a bit annoying to reproduce, because the permissions are only set on a fresh install, not an upgrade).

You can work around this with `adb shell run-as <pkgname> chmod a+x /data/data/<pkgname>`, until we release an update of ndk-gdb.py that does that automatically.

**Comment by pm1100tm** [comment] 2016-10-21 05:42
Reproduction Output: 

***targetSdkVersion 24 (unable to connect to device)
$ ndk-gdb --launch --verbose --nowait
ADB command used: 'adb -s HT4C5JT00648'
ADB version: Android Debug Bridge version 1.0.36 Revision 84e3321d5db3-android
Using project directory: /Users/wondu/Desktop/Case/ndkmd/hello-gl2 
Found package name: com.android.gl2jni
Selected target activity: 'com.android.gl2jni.GL2JNIActivity'
Application ABIs: arm64-v8a, armeabi, armeabi-v7a, mips, mips64, x86, x86_64, 
Device ABIs: arm64-v8a, armeabi-v7a, armeabi
Selecting ABI: arm64-v8a
Detected pretty printer: none
Found application data directory: /data/data/com.android.gl2jni
App gdbserver not found at /data/data/com.android.gl2jni/lib/gdbserver, uploading.
Copying gdbserver to /data/data/com.android.gl2jni/arm64-gdbserver.
Uploaded gdbserver to /data/data/com.android.gl2jni/arm64-gdbserver
Launching activity com.android.gl2jni/com.android.gl2jni.GL2JNIActivity...
Sleeping for 0.25 seconds.
Pulling '/system/bin/app_process64' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/bin/app_process64'
Pulling '/system/bin/linker64' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/bin/linker64'
Pulling '/system/lib64/libc.so' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/lib64/libc.so'
Pulling '/system/lib64/libm.so' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/lib64/libm.so'
Pulling '/system/lib64/libdl.so' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/lib64/libdl.so'
Starting gdbserver...
Redirecting gdbserver output to /var/folders/v0/sw2r7mtd30z8h95v1grbshbm00_q0q/T/gdbclient.log
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Error: unable to connect to device.
Remote connection closed

***targetSdkVersion 23 (able to connect to device)
$ ndk-gdb --launch --verbose --nowait
ADB command used: 'adb -s HT4C5JT00648'
ADB version: Android Debug Bridge version 1.0.36 Revision 84e3321d5db3-android
Using project directory: /Users/wondu/Desktop/Case/ndkmd/hello-gl2 
Found package name: com.android.gl2jni
Selected target activity: 'com.android.gl2jni.GL2JNIActivity'
Application ABIs: arm64-v8a, armeabi, armeabi-v7a, mips, mips64, x86, x86_64, 
Device ABIs: arm64-v8a, armeabi-v7a, armeabi
Selecting ABI: arm64-v8a
Detected pretty printer: none
Found application data directory: /data/data/com.android.gl2jni
App gdbserver not found at /data/data/com.android.gl2jni/lib/gdbserver, uploading.
Copying gdbserver to /data/data/com.android.gl2jni/arm64-gdbserver.
Uploaded gdbserver to /data/data/com.android.gl2jni/arm64-gdbserver
Launching activity com.android.gl2jni/com.android.gl2jni.GL2JNIActivity...
Sleeping for 0.25 seconds.
Pulling '/system/bin/app_process64' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/bin/app_process64'
Pulling '/system/bin/linker64' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/bin/linker64'
Pulling '/system/lib64/libc.so' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/lib64/libc.so'
Pulling '/system/lib64/libm.so' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/lib64/libm.so'
Pulling '/system/lib64/libdl.so' to '/Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/lib64/libdl.so'
Starting gdbserver...
Redirecting gdbserver output to /var/folders/v0/sw2r7mtd30z8h95v1grbshbm00_q0q/T/gdbclient.log
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
warning: Could not load shared library symbols for 149 libraries, e.g. /system/lib64/libcutils.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
0x0000007add81325c in __epoll_pwait () from /Users/wondu/Desktop/Case/ndkmd/hello-gl2/obj/local/arm64-v8a /system/lib64/libc.so
(gdb)

I will try to the workaround you suggested. Thanks.

**Comment by pm1100tm** [comment] 2016-10-21 05:48
It works, Thanks!

**Comment by pm1100tm** [comment] 2016-10-21 06:13
It works to me after tried to do the workaround jmgao suggested.
"adb shell run-as <pkgname> chmod a+x /data/data/<pkgname>"
ndk-gdb connect to device.

**Comment by jmgao** [comment] 2016-10-21 09:39
Fix merged in https://android.googlesource.com/platform/ndk/+/b3bff3c4^!/

**Closed by jmgao** 2016-10-21 09:39 UTC
Labels: gdb
