### ISSUE TITLE
android.toolchain.cmake toolchain gives missing compiler error

### ISSUE THREAD

**Issue by xCuri0** [android-ndk/ndk#509] opened 2017-09-05 14:51 UTC
When trying the use the `android.toolchain.cmake` to build a project I get this error.
```
-- Android: Selected Clang toolchain 'arm-linux-androideabi-clang' with GCC toolchain 'arm-linux-androideabi-4.9'
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:

    /opt/android-ndk-beta/toolchains//prebuilt/linux-x86_64/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/mnt/storage2/salt/glfw/Release/CMakeFiles/CMakeOutput.log".
```
For some reason I didn't have problems building NDK CMake samples in Android Studio.

I am using NDK r16 beta from AUR

**Comment by tiwoc** [comment] 2017-09-08 06:17
This is a duplicate of #504.

**Closed** 2017-09-08 17:05 UTC
