### ISSUE TITLE
"undefined refference" for Inline static members in class template specialization 

### ISSUE THREAD

**Issue by tower120** [android-ndk/ndk#591] opened 2017-12-08 14:44 UTC
#### Description

```c++
namespace jni_interface{
    template<class ...Args>
    class SignalSender;

    template<>
    class SignalSender<>{
        inline static struct MethodIds{
            inline static jmethodID pulse;
            inline static jmethodID link;
        } methodIds;
    public:
        SignalSender(const std::string& id)
        {
            void* d = methodIds.link;                 // linker error here.
        }
    };
}
```

And later in the code:
```c++
SignalSender<> s1("s1");
```

Cause:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\Andy\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\AndroidProjects\cpptest1\app\.externalNativeBuild\cmake\debug\x86_64 --target native-lib}
  [1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
  [2/2] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\x86_64\libnative-lib.so
  FAILED: cmd.exe /C "cd . && C:\NDK\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=x86_64-none-linux-android --gcc-toolchain=C:/NDK/android-ndk-r16b/toolchains/x86_64-4.9/prebuilt/windows-x86_64 --sysroot=C:/NDK/android-ndk-r16b/sysroot -fPIC -isystem C:/NDK/android-ndk-r16b/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++1z -frtti -fexceptions -Werror=return-type -Werror=uninitialized -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot C:/NDK/android-ndk-r16b/platforms/android-21/arch-x86_64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\x86_64\libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o  -llog -landroid -latomic -lm "C:/NDK/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/libgnustl_static.a" && cd ."
  C:\AndroidProjects\cpptest1\app\src\main\cpp/jni_interface/SignalSender.h:45: error: undefined reference to 'jni_interface::SignalSender<>::MethodIds::link'
  clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

```

---

If make SignalSender, as non-template specialization, everything compiles fine.
```c++
class SignalSender{
   // class body here
}
SignalSender s1("s1");
```

#### Environment Details

* NDK Version: r16b
* Host OS: Windows 10
* Compiler: default (Clang).
```
externalNativeBuild {
   cmake {
       cppFlags "-std=c++1z -frtti -fexceptions -Werror=return-type -Werror=uninitialized"
   }
}
```

**Comment by rprichard** [comment] 2017-12-08 21:43
This issue was already filed in upstream Clang on 2017-10-21: https://bugs.llvm.org/show_bug.cgi?id=35027. The repro for that bug fails with upstream Clang 5.0.0 and passes with trunk (r320133): https://godbolt.org/g/BPQuJr.

This commit looks like it involves template specializations and inline static data members. Maybe it's the fix? https://github.com/llvm-mirror/clang/commit/549aaf11afe537d779888d05324759c2f3ef83b5.

The problem still reproduces with clang-4479392:
```
$ ~/android/ndk/prebuilts/clang/host/linux-x86/clang-4479392/bin/clang --version
Android clang version 5.0.2 (https://us3-mirror-android.googlesource.com/a/toolchain/clang a6f105c75c9eacaf6bb716d8fcfa0296989d1b36) (https://us3-mirror-android.googlesource.com/a/toolchain/llvm 2ada0df0345eb2bcb3749fd37a6f1d25d6684b64) (based on LLVM 5.0.2svn)
```

**Comment by rprichard** [comment] 2017-12-08 21:59
@stephenhines @DanAlbert I think updating Clang would fix this issue.

**Comment by DanAlbert** [comment] 2018-03-16 00:50
Looks like we got the commit that fixed this in r17.

**Comment by rprichard** [comment] 2018-03-16 00:55
Are you sure? AFAICT, this bug reproduces in clang-4639204, which is the newest prebuilt we have in AOSP master.

**Comment by DanAlbert** [comment] 2018-03-16 01:17
I just tested with master... I possibly screwed up my test case? Hang on.

**Comment by rprichard** [comment] 2018-03-16 01:23
Here's a less-reduced test case (but with the irrelevant `jni.h` and `string` dependencies removed): 

```c++
namespace jni_interface{
    template<class ...Args>
    class SignalSender;

    template<>
    class SignalSender<>{
        inline static struct MethodIds{
            inline static void *pulse;
            inline static void *link;
        } methodIds;
    public:
        SignalSender(const char *id)
        {
            void *d = methodIds.link;                 // linker error here.
        }
    };

    SignalSender<> s1("s1");
}

int main() {}
```

output:

```
$ ~/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++ test.cpp -std=c++17
<success, no output>

$ /ssd2/stand-arm-16-r17beta1/bin/clang++ test.cpp -std=c++17
/tmp/test-ab10da.o:test.cpp:function jni_interface::SignalSender<>::SignalSender(char const*): error: undefined reference to 'jni_interface::SignalSender<>::MethodIds::link'
clang60++: error: linker command failed with exit code 1 (use -v to see invocation)

$ /ssd2/stand-arm-16-r17beta1/bin/clang++ --version
Android (4639204 based on r316199) clang version 6.0.1 (https://android.googlesource.com/toolchain/clang 279c0d3a962121a6d1d535e7b0b5d9d36d3c829d) (https://android.googlesource.com/toolchain/llvm aadd87ffb6a2eafcb577913073d46b20195a9cdc) (based on LLVM 6.0.1svn)
Target: armv7a-none-linux-android
Thread model: posix
InstalledDir: /ssd2/stand-arm-16-r17beta1/bin
```

**Comment by stephenhines** [comment] 2018-03-16 01:28
Android Clang 6.0.1 < Upstream 6.0. Upstream does their version bump right after a new release comes out, so our 6.0.1 is prior to the official release (pretty much could come from anything after 5.0 released). We can locate the patch needed to fix this and cherry-pick it, but I would almost just prefer to leave the compiler alone for r17 and fix this for r18. Chih-hung has a new toolchain under test right now, and we will likely be switching to that next week, but it does move the compiler ahead from ~November to ~February, so that's a lot of churn for a beta release.

**Comment by DanAlbert** [comment] 2018-03-16 01:34
Interestingly this worked fine when I put the sample in ndk-build but doesn't with cmake... That alone deserves some investigation.

**Comment by DanAlbert** [comment] 2018-03-16 01:45
Never mind, the reason it worked with ndk-build and not cmake is because ndk-build defaulted to -O2 and cmake defaulted to -O0.

**Comment by rprichard** [comment] 2018-06-21 21:18
This issue looks fixed in the r18 canary clang.

**Closed by rprichard** 2018-06-21 21:18 UTC
Labels: clang
