### ISSUE TITLE
Clang++ for arm64 can generate buggy assembly for functions with VLA

### ISSUE THREAD

**Issue by N-Bz** [android-ndk/ndk#781] opened 2018-08-31 09:36 UTC
#### Description

When using VLA inside C++ code, compiled for `arm64`, we have found some edge cases where the generated assembly for the function corrupts the caller stack pointer (i.e. restore it to a wrong value).

I've attached a sample project with a single `main.cpp` file and the associated `Makefile` to reproduce the issue, and a commented disassembly of the function containing the bug: [clang_vla_armv8.tar.gz](https://github.com/android-ndk/ndk/files/2339476/clang_vla_armv8.tar.gz)

The code contains three configurations defines that can be used to trigger or remove the bug. When compiled with `g++`, or with `clang++` with a target other than `arm64`, the code has no issue, regardless of the chosen configuration.

Note: We know that VLAs are not part of the C++ standard, and that we're invoking a compiler extension (`-pedantic` warns if set), but since both `g++` and `clang++` claims to support the VLAs in c++ for compatiblity with C99, we did not expect this code to fail.

#### Environment Details

The bug was reproduced on Linux (Ubuntu 16.06 & 17.10), and on macOS (High Sierra)

The bug was tested on `clang++` for `arm64` in NDKs `15c`, `16b`, `17b` and `18-beta2`. All NDKs presented the same behavior (`g++`, if available, compiles fine, `clang++` for `arm32` also, but `clang++` for `arm64` has the issue)

We used stand-alone toolchain, but we expect the issue to be present with any build system.

**Comment by jmgao** [comment] 2018-08-31 18:14
@stephenhines @pirama-arumuga-nainar

**Comment by pirama-arumuga-nainar** [comment] 2018-08-31 22:33
Tried this with the pending update to clang r333878.  The bug doesn't reproduce.  Looks like https://reviews.llvm.org/D45524 fixed the bug in upstream.

**Comment by pirama-arumuga-nainar** [comment] 2018-08-31 22:37
@N-Bz Btw, thanks for the simple and clear repro case.  This made further investigation much easier.

**Comment by DanAlbert** [comment] 2018-08-31 22:43
(actually waiting to have the new clang available, but assigning to myself since I'll be the one updating the NDK)

**Comment by N-Bz** [comment] 2018-09-01 08:06
> Tried this with the pending update to clang r333878. The bug doesn't reproduce. Looks like https://reviews.llvm.org/D45524 fixed the bug in upstream.

Indeed this seems to be exactly the problem we experienced.

This is not a blocking issue for us now, since we found ways to avoid this bug (using `-Werror=vla` and fixing the code to use other things, mainly), so waiting for r19 is perfectly fine.

**Comment by DanAlbert** [comment] 2018-10-17 20:11
New clang is in r19.

**Closed by DanAlbert** 2018-10-17 20:11 UTC
Labels: clang
