### ISSUE TITLE
[BUG] Compilation error after upgrading to r19

### ISSUE THREAD

**Issue by Slion** [android-ndk/ndk#894] opened 2019-01-24 13:02 UTC
#### Description

After upgrading from r18b to r19 I'm getting compilation errors in system headers such as:
`C:/Users/micro/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\cstdlib:155:9: error: no member named 'at_quick_exit' in the global namespace`
or
`C:/Users/micro/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\support/xlocale/__posix_l_fallback.h:80:12: error: no member named 'iswblank' in the global namespace; did you mean 'isblank'?`

It looks like something is amiss with my build configuration. The project itself is rather large and complex with multiple cmake files all over the place. Everything worked fine with r18b though. Any help appreciated. 

#### Environment Details

* NDK Version: r19.
* Build system: cmake 3.10.2
* Host OS: Windows 10
* Compiler: Clang.
* ABI: x86, x86_64, armeabi-v7a, arm64-v8a
* STL: c++_static
* NDK API level: 26
* Device API level: 27
* Android Studio 3.3

**Comment by Slion** [comment] 2019-01-24 13:05
Looks like someone had a similar issue#452. Though it's not quite clear how it was fixed then.

**Comment by DanAlbert** [comment] 2019-01-24 17:13
How are you invoking CMake? We test CMake as part of the release, so we know this isn't broken in the common case. We need more information about your configuration.

**Comment by Slion** [comment] 2019-01-25 10:35
CMake is invoked from Android Studio. In gradle it looks like that:
`            externalNativeBuild
                    {
                        cmake
                                {
                                    path 'src/main/cpp/CMakeLists.txt'
                                    //
                                    buildStagingDirectory = rootProject.buildDir
                                }
                    }`

However the Android app binary has a dependency on our engine which is out of the Android tree.
That Android CMakeList.txt is including our engine like that:
`add_subdirectory(../../../../../..     ../../../../../../../../bin/Engine/Android/Engine)`

**Comment by DanAlbert** [comment] 2019-01-25 21:31
I'm guessing what's happening is that one of those CMake files is wrongly setting up its own NDK include paths. It's also possible that one of those projects has headers that are shadowing the NDK's headers and that's breaking lookup within the stdlib. If the project has any headers with the same names as anything in the C or C++ stdlib, bad things happen.

If neither of those are the problem, I can maybe provide more guesses if you can share the compile command (the actual clang++ invocation, not the gradle or cmake command; I know this is logged somewhere in the project directory but I don't know where), but a repro case would be the most valuable.

**Comment by koying** [comment] 2019-02-02 13:44
Same issue going from NDK 18 to NDK 19 from Android studio
```
[32/1277] Building CXX object ../cmake_build/libupnp/CMakeFiles/libupnp.dir/Neptune/Source/System/StdC/NptStdcEnvironment.cpp.o
FAILED: D:\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi21 --gcc-toolchain=D:/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64   -isystem D:/android-sdk/ndk-bundle/sysroot/usr/include -isystem D:/android-sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -isystem d:/winlin/mrmc-depends/arm-linux-androideabi-21/include -isystem d:/winlin/mrmc-depends/arm-linux-androideabi-21/lib/libzip/include -isystem d:/winlin/mrmc-depends/arm-linux-androideabi-21/include/freetype2 -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../.. -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../lib -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../lib/addons/library.xbmc.addon -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../xbmc -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../xbmc/addons/include -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../addons/library.kodi.guilib -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../addons/library.xbmc.addon -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../addons/library.kodi.adsp -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../addons/library.kodi.audioengine -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../addons/library.xbmc.pvr -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../addons/library.xbmc.codec -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../xbmc/linux -ID:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../xbmc/cores/dvdplayer --sysroot D:/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -fno-addrsig -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ -frtti -fexceptions  -std=c++11 -D_DEBUG -DHAVE_CONFIG_H -DANDROID -DTARGET_POSIX -DTARGET_LINUX -D_LINUX -DTARGET_ANDROID -D__ANDROID_API__=21 -D_GLIBCXX_USE_C99_MATH_TR1 -D__STDC_CONSTANT_MACROS -D_FILE_DEFINED -DNPT_CONFIG_ENABLE_LOGGING -DPLT_HTTP_DEFAULT_USER_AGENT="\"UPnP/1.0 DLNADOC/1.50 MrMCDev\"" -DPLT_HTTP_DEFAULT_SERVER="\"UPnP/1.0 DLNADOC/1.50 MrMCDev\"" -Wno-inconsistent-missing-override -Wno-overloaded-virtual -O0 -fno-limit-debug-info  -fPIC   -DRAR_SILENT -MD -MT ../cmake_build/UnrarXLib/CMakeFiles/UnrarXLib.dir/extract.cpp.o -MF ..\cmake_build\UnrarXLib\CMakeFiles\UnrarXLib.dir\extract.cpp.o.d -o ../cmake_build/UnrarXLib/CMakeFiles/UnrarXLib.dir/extract.cpp.o -c D:\cbro\src\mrmc\lib\UnrarXLib\extract.cpp
In file included from D:\cbro\src\mrmc\lib\UnrarXLib\extract.cpp:2:
In file included from D:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../xbmc\Util.h:23:
D:/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\cmath:314:9: error: no member named 'signbit' in the global namespace; did you mean 'sigwait'?
using ::signbit;
      ~~^
D:/android-sdk/ndk-bundle/sysroot/usr/include\signal.h:129:5: note: 'sigwait' declared here
int sigwait(const sigset_t* __set, int* __signal);
    ^
In file included from D:\cbro\src\mrmc\lib\UnrarXLib\extract.cpp:2:
In file included from D:/cbro/src/mrmc/tools/android/packaging/packaging/../../../../xbmc\Util.h:23:
D:/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\cmath:315:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
D:/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\cmath:316:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
D:/android-sdk/ndk-bundle/sysroot/usr/include\math.h:375:5: note: 'finite' declared here
int finite(double __x) __attribute_const__;
[...]
```

**Comment by alexcohn** [comment] 2019-02-03 10:18
This all boils down to a subtle difference between `_LIBCPP_ALWAYS_INLINE` and `_LIBCPP_INLINE_VISIBILITY` which has been redefined [recently](https://reviews.llvm.org/D49914) to hiding symbols from the ABI when **libc++** is built with an ABI version after ABI v1.

**Comment by galactoid** [comment] 2019-02-03 17:11
Same issue for my project. Don't know that helps exactly, but now everything builds fine.

1. Android Studio -> Invalidate Caches /Restart.
2. Build -> Refresh Linked C++ Projects
3. Set exact cmake version, because log shows like 3.6.4 was used in build
```
    externalNativeBuild {
        cmake {
            version "3.10.2"
            path 'CMakeLists.txt'
        }
    }

```

**Comment by piwinux** [comment] 2019-02-20 09:12
I am also facing this issue, but in my case, cleaning/rebuilding does not help.

@alexcohn Could you elaborate a little bit more on what happens in this case?

@Slion Did you solve this problem? You mentioned you would try with the version of CMake shipped with Android Studio but did not give an update (in my case it did not help).

**Comment by piwinux** [comment] 2019-02-20 14:36
I had this issue while upgrading from NDK 16, and the problem was that my library was configured so that the include directory of the NDK (`<ndk>/sysroot/usr/include`) was passed to the compiler.

My understanding of the problem in my case (`no member named 'signbit'`) was that `include/c++/v1/cmath` includes `include/c++/v1/math.h`, which at some point uses `#include_next <math.h>`. But in this case `include/math.h`, which defines `signbit`, could not be included, because there was no `-I<ndk>/sysroot/usr/include` following mine.

**Comment by Slion** [comment] 2019-03-04 14:40
> Don't know that helps exactly, but now everything builds fine.

It's weird, when I do Run (CTRL+F5) in Android Studio it builds and runs fine in the emulator.
When I do Make Project (F7) I get those errors.

**Comment by DanAlbert** [comment] 2019-03-04 20:30
So far there's nothing here that we can even investigate. Based on one comment this is maybe just an issue with needing a clean build after updating? Another highlights a case where the build script itself was wrong.

If anyone has information on how to reproduce this problem I'll reopen this, but as-is there's nothing we can do (and it's hard to say for sure that there's even an NDK bug here), so closing.

**Closed by DanAlbert** 2019-03-04 20:30 UTC
Labels: bug, needs-info

**Comment by Slion** [comment] 2019-03-05 14:10
The issue is not with the NDK it seems.
I tracked it down to the gradle plugin `com.android.tools.build:gradle:3.3.0` works while `com.android.tools.build:gradle:3.3.1` is broken as mentioned in first posts and `com.android.tools.build:gradle:3.3.2` is even more broken. I'll stick to 3.3.0 for now. Not sure where to report those issues.

**Comment by Slion** [comment] 2019-03-05 14:30
Opened a bug against Android Studio:
https://issuetracker.google.com/issues/127290460

**Comment by DanAlbert** [comment] 2019-03-05 19:37
Glad you were able to narrow that down. Triaged the Studio bug so the right people see it.

**Comment by Slion** [comment] 2019-03-06 08:46
I did more testing with r19b, clean clone, Gradle Plugin 3.3.0 and am getting those stdlib compilation errors again. So I'm not sure what was done yesterday but today it does look like the error is with the NDK rather than Gradle Plugin.

**Comment by alexcohn** [comment] 2019-03-06 08:54
You can isolate the Gradle dependency by looking at the `.externalNativeBuild\cmake\release\armeabi-v7a\cmake_build_command.txt` (or `debug`, also the ABI may vary).

**Comment by Slion** [comment] 2019-03-07 13:41
> You can isolate the Gradle dependency by looking at the `.externalNativeBuild\cmake\release\armeabi-v7a\cmake_build_command.txt` (or `debug`, also the ABI may vary).

Not sure what you mean. I do know it's an NDK issue rather than a Gradle Plugin issue.

**Comment by Slion** [comment] 2019-03-07 13:49
It took some time to take a closer look at those errors. Here is how `at_quick_exit` is defined in stdlib.h from NDK r19.
```
#if __ANDROID_API__ >= 21
int at_quick_exit(void (*__fn)(void)) __INTRODUCED_IN(21);
void quick_exit(int __status) __noreturn __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */
```

So it sure looks like __ANDROID_API__ is not defined properly when the compiler gets there. I still have to find out where __ANDROID_API__ is defined.

**Comment by Slion** [comment] 2019-03-07 14:17
Looks like I fixed it by changing `minSdkVersion` from 14 to 21.
Both `compileSdkVersion` and `targetSdkVersion` are still set to 26.
Not sure why it was working on NDK r18, @DanAlbert was the logic handling those Gradle variables changed in r19?

**Comment by enh** [comment] 2019-03-07 15:16
> So it sure looks like `__ANDROID_API__` is not defined properly when the compiler gets there.

meaning not set at all? i wonder if we should have a `#error` in <features.h> for that case?

**Comment by Slion** [comment] 2019-03-07 15:43
> meaning not set at all?
My best guess is that is was set to 14 since:
> I fixed it by changing minSdkVersion from 14 to 21.
but then:
> Not sure why it was working on NDK r18

**Comment by DanAlbert** [comment] 2019-03-07 17:26
Your build scripts are doing something that is preventing the compiler from finding libandroid_support. Yes, it changed a bunch in r19, but all of our build systems handle that for you.

My best guess is still what I said originally: one of your CMakeLists.txt files is setting up some NDK include paths itself, which is ordering them incorrectly, which is breaking this. If you can share your CMakeLists.txt or a failing compile command, it should be fairly obvious.

**Comment by Slion** [comment] 2019-03-08 06:58
> one of your CMakeLists.txt files is setting up some NDK include paths itself

Why then would changing `minSdkVersion` fix the issue?
Here are the only Android specific includes defined in my CMake project:
```
    include_directories(SYSTEM ${ANDROID_NDK}/sysroot/usr/include)
    include_directories(SYSTEM ${ANDROID_NDK}/sources/android/native_app_glue)
```
Other than that it's also linking against the Android GL libraries.
That's all it does really. It's a multi-platform project and we only completed Android support in 2018.

**Comment by DanAlbert** [comment] 2019-03-08 07:50
> Why then would changing minSdkVersion fix the issue?

Because libandroid_support is only needed when your `minSdkVersion` is less than 21.

> include_directories(SYSTEM ${ANDROID_NDK}/sysroot/usr/include)

Delete this.

**Comment by Slion** [comment] 2019-03-08 08:01
Thanks! That include directory was indeed the root of the problem.
I can even reproduce the issue when adding that include directory to [native-activity](https://github.com/googlesamples/android-ndk/tree/master/native-activity).

Removing the following from my CMake file is the proper fix:
```
include_directories(SYSTEM ${ANDROID_NDK}/sysroot/usr/include)
```

**Comment by noloader** [comment] 2019-10-15 13:00
Thank you @Dan. I was panicking.

**Comment by machinekoder** [comment] 2020-04-02 08:54
Yikes, it doesn't work for me. Does anyone know which include directory should be included instead of the one in sysroot?

**Comment by DanAlbert** [comment] 2020-04-02 09:09
Don't worry about it. The compiler handles it for you. If you just stop passing toolchain include directories to the toolchain it'll work. If it doesn't, file a new bug with all the information I asked for above.
