### ISSUE TITLE
ndk-gdb doesn't ignore user output from Makefile when detecting application properties

### ISSUE THREAD

**Issue by pm-kan** [android-ndk/ndk#98] opened 2016-05-18 15:03 UTC
ndk-gdb.py detect application ABI (STL, etc.) using first line of non-filtered output of `make --no-print-dir -f <...>build-local.mk -C <...> DUMP_SOMETHING` (see `dump_var`), so if Android.mk contains something like `($info some message)`, "some message" will be used as a result and application ABI, will not be detected.

**Comment by rprichard** [comment] 2017-10-14 01:45
Duplicate of https://issuetracker.google.com/37124812. Presumably the fix is to make ndk-gdb skip lines that don't match the expected `VAR=VAL` pattern. Maybe add a prefix to reduce the possibility of collision, but I doubt that's practical.

**Comment by rprichard** [comment] 2017-10-14 01:52
I misremembered. For some reason, I thought make's `DUMP_{VAR}` target dumped a `VAR=VAL` line, but now that I've checked again, it only dumps the value.

**Comment by rprichard** [comment] 2017-10-17 00:06
Fixed with https://android.googlesource.com/platform/ndk/+/02a9c7c95bc0c75532362ceae21a627e49ae4e50

**Closed by rprichard** 2017-10-17 00:06 UTC
