### ISSUE TITLE
Compiler bug when catching exceptions with -flto=thin

### ISSUE THREAD

**Issue by mad-rain** [android-ndk/ndk#717] opened 2018-06-08 06:49 UTC
#### Description

Hi!

std::runtime_error exception is being caught inside catch(...) instead of catch(const std::exception &) when using -flto=thin, -fexceptions, -fno-rtti and c++_static as a standard library.

Minimized repro case:

[https://github.com/mad-rain/dynamic-cast-repro](https://github.com/mad-rain/dynamic-cast-repro)

#### Environment Details

* NDK Version: 17.0.4754217
* Build system: ndk-build
* Host OS: Mac
* Compiler: Clang
* ABI: x86, armv7eabi
* STL: c++_static
* NDK API level: 15

**Comment by rprichard** [comment] 2018-06-08 08:19
The problem reproduces in NDK r15c through r17 (including the r17b candidate). It looks fixed in r18 canary (build 4828501, clang 4751641 based on r328903).

The r17b candidate's compiler is version 4691093 based on r316199.

It looks like the compiler puts two copies of `std::exception`'s typeinfo object into `libtest.so`. I'd guess it gets one copy from `libc++_static.a` (built with `-frtti`) and then emits a copy itself (because `-fno-rtti` requires that a copy be emitted everywhere?). Presumably part of `libtest.so` is using one copy and another part is using the other copy.

```
$ nm  obj/local/x86/libtest.so  | c++filt | grep 'typeinfo for std::exception'
000474b8 d typeinfo for std::exception
00047548 D typeinfo for std::exception
```

I can reproduce something similar using the Clang installed on my desktop (and either the bfd or gold linkers). https://gist.github.com/rprichard/8aff519360f26bf199e487bf9106d26b

My guess is that this is (or was) an upstream LLVM bug. Maybe https://bugs.llvm.org/show_bug.cgi?id=36187?

**Comment by rprichard** [comment] 2018-06-21 23:31
This issue appears fixed with the r18 canary clang.

**Closed by rprichard** 2018-06-21 23:31 UTC

**Comment by mad-rain** [comment] 2019-07-18 13:49
Reproduces again on r20:

NDK Version: 20.0.5594570
Build system: ndk-build
Host OS: Mac
Compiler: Clang
ABI: x86, armv7eabi
STL: c++_static
NDK API level: 16
