### ISSUE TITLE
libc++ printf numbered argument format produces garbled output

### ISSUE THREAD

**Issue by arrix** [android-ndk/ndk#413] opened 2017-06-07 01:30 UTC
#### Description
POSIX printf allows specifying argument position in the format (`"%n$"` and `"*m$"`).
http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html

In libc++ it works fine in ndk r12b, crashes in r13b and produces garbled output in r14b.

In the following example, s2 is supposed to be "Hello World" but ends up garbled.
```
char s1[1000] {0};
char s2[1000] {0};
snprintf(s1, sizeof(s1), "%s %s", "World", "Hello"); // World Hello 
snprintf(s2, sizeof(s2), "%2$s %1$s", "World", "Hello"); //  ����b�Ơh�ƠݒƠݒƠ�Y�@Y��A:p	
```
#### Environment Details
APP_CPPFLAGS += -std=c++14
APP_STL := c++_shared

* NDK Version: 14.1.3816874.
* Build sytem: ndk-build
* Host OS: Mac
* Compiler: Clang
* ABI: armeabi-v7a 
* STL: c++_shared
* NDK API level: 19
* Device API level: 21
* Device: Nexus 5 Android 6.0.1

**Comment by DanAlbert** [comment] 2017-06-08 21:52
Guessing that this is something missing from libandroid_support (alternatively, something that's broken in libandroid_support but works on the device).

**Comment by alexcohn** [comment] 2017-06-11 13:38
Could not reproduce this with NDK r14b on emulator, neither arm or x86. Note that STL or CPPFLAGS are not expected to have any effect on this: it's pure C.

**Comment by arrix** [comment] 2017-06-12 02:33
I was using Nexus 5 Android 6.0.1. Added the information in description too.

**Comment by arrix** [comment] 2017-06-12 06:02
@alexcohn I just tested again. The problem only occurs with LLVM libc++. With GNU STL it's fine.
The behaviour is consistent on both device and emulator.

**Comment by alexcohn** [comment] 2017-06-12 08:30
Can you share your project? I simply cannot understand where STL can be involved.

**Comment by enh** [comment] 2017-06-12 16:32
isn't it only libc++ that gets libandroid_support linked in? and doesn't libandroid_support have broken bits of musl's stdio? and isn't one of the differences that musl's stdio doesn't support numbered arguments? i think this is sadly completely expected (for now) and one of the main reasons that danalbert isn't happy making libc++ the default (for now).

**Comment by DanAlbert** [comment] 2017-06-12 19:06
What @enh said. `libandroid_support` gets linked to your project when you use libc++. This is maybe on the table for r16. It depends on the path we end up taking to get libandroid_support fixed up. We want to replace it with the bionic source so there aren't any surprises like this, but short term we may need to just update (and add a lot of tests) to the musl/BSD sources we're using there.

If we end up being able to use bionic's sources, this will go away in r16, else it will be r17.

**Comment by alexcohn** [comment] 2017-06-13 10:05
Oh, now it does make sense. It's enough to add `LOCAL_STATIC_LIBRARIES += android_support` to my pure C project without STL - and the result is same as reported by @arrix.

**Comment by fornwall** [comment] 2017-06-13 10:13
> libandroid_support gets linked to your project when you use libc++

@DanAlbert If one is using a standalone toolchain and targeting android-21 or later, is it possible/recommended to use the current libc++ in NDK r15 without linking in libandroid_support?

**Comment by DanAlbert** [comment] 2017-07-24 21:04
@fornwall: Maybe. I don't remember exactly the shape things were in at that time (as of today there are a few APIs that weren't added until very recently, I want to say N, but maybe O?), but it somewhat depends on which parts of libc++ you use since it's mostly contained in the headers and the linker will remove anything you didn't use.

You would need to pass `-nostdlib` and link things manually (or hack up libc++.so/libc++.a in your standalone toolchains, which are actually just linker scripts).

**Comment by alexcohn** [comment] 2017-07-25 09:07
@fornwall: you can use non-prebuilt STL and modify `sources/cxx-stl/llvm-libc++/Android.mk` to remove all references to **android_support**. I would recommend to link this STL statically to reduce both build efforts and side effects.

**Comment by enh** [comment] 2017-07-25 14:50
looking at the source for r16's new sane libandroid_support (https://android.googlesource.com/platform/ndk.git/+/master/sources/android/support/) i see just these trivial _l function declarations that are post-L: https://android.googlesource.com/platform/ndk.git/+/master/sources/android/support/include/stdlib.h

**Comment by DanAlbert** [comment] 2017-07-25 18:34
libandroid_support is built targeting android-14 though, so the library still has everything else in it and will be used anyway.

**Comment by DanAlbert** [comment] 2017-07-25 22:42
The actual bug here is fixed in r16 though (fixed by just deleting the code in libandroid_support)

**Closed by DanAlbert** 2017-07-25 22:42 UTC
Labels: compatlib
