### ISSUE TITLE
Unknown event that is listed

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#493] opened 2017-08-25 19:16 UTC
--------------------------------------------------------------------------------

#### Description
I execute app_profile.py with configuration: 

run record_options = "-e cpu-cycles:u -f 4000 -g --duration 15"

and it works great. Then, I listed on the device the available events. From the device, I saw that the following two tracepoint events are available:

raw_syscalls:sys_enter
raw_syscalls:sys_exit

However, when I execute the app_profiler.py with configuration:

record_options = "-e raw_syscalls:sys_enter -a -g -duration 15"

it always tells me the following:

Unknown event_type 'raw_syscalls:sys_enter', try `simpleperf list` to list all possible event type names

What am I doing wrong?

Thanks for any help.

**UPDATE:** hw-cache events, hardware events, raw events provided by cpu pmu, and software events work correctly. However, all the tracepoint events are not recognized.

#### Environment Details

* NDK Version:r15c.
* Host OS: Mac
* Device API level: 24

**Comment by yabinc** [comment] 2017-08-25 20:10
It is because of how app_profiler.py run simpleperf. app_profiler.py first copies simpleperf to the app's context, then run it. And the selinux policy of Android doesn't allow accessing /sys/debug/kernel/tracing from app's context, so simpleperf can't read tracepoint events available in the system.
This is changed in ndk r16, the --app option is added to simpleperf record cmd, and app_profiler.py runs simpleperf from shell's context. If you really want to try tracepoint events, you can do either of the followings:
1. get a rooted device. On a rooted device, app_profiler.py doesn't  run simpleperf in app's context, and you can access all tracepoint events.
2. Wait for ndk r16 beta a, or download newest simpleperf from https://android.googlesource.com/platform/prebuilts/simpleperf/. It should give you access to raw_syscalls:sys_enter and raw_syscalls:sys_exit events.

By the way, you use record_options = "-e raw_syscalls:sys_enter -a -g -duration 15", but -a option is only available on rooted devices.

Currently simpleperf doesn't put much effort on tracing syscalls, so feel free to let me know anything you want it to support.

**Comment by brok85** [comment] 2017-08-25 20:19
> get a rooted device. On a rooted device, app_profiler.py doesn't run simpleperf in app's context, and you can access all tracepoint events.

> By the way, you use record_options = "-e raw_syscalls:sys_enter -a -g -duration 15", but -a option is only available on rooted devices.

The device I am using it is already rooted. Should I try directly the new version?

> so feel free to let me know anything you want it to support

Well I just started using "perf-like" commands so I am not an expert about it. What I am trying to achieve with simpleperf is to see which libraries a specific thread (e.g., the main thread of the foreground app) is using and what are the system calls originated from that thread. For example, I would like to see which libraries and syscalls are executed as a consequence of pushing a button of the foreground app.

**Comment by brok85** [comment] 2017-08-25 20:41
I just opened the app folder in data/data/app_package_name and executed the following command:

./simpleperf stat -e raw_syscalls:sys_enter -p 12288 --duration 5
264  raw_syscalls:sys_enter   # 52.776 /sec  (100%)

As you can see, I used a tracepoint event and it is executed correctly. However, if I run 

./simpleperf record -e raw_syscalls:sys_enter -p 12288 --duration 5

It tells me the following:

simpleperf F 08-25 16:35:34 12714 12714 record.h:158] Check failed: size < 1u << 16 (size=107660, 1u << 16=65536) 
Aborted 

What is that error and how can I solve it?

**Comment by yabinc** [comment] 2017-08-25 21:54
> The device I am using it is already rooted. Should I try directly the new version?
On a rooted device, I have tested that run app_profiler.py shouldn't report below error: Unknown event_type 'raw_syscalls:sys_enter'. Can you paste the log of running app_profiler.py?

> Well I just started using "perf-like" commands so I am not an expert about it. What I am trying to achieve with simpleperf is to see which libraries a specific thread (e.g., the main thread of the foreground app) is using and what are the system calls originated from that thread. For example, I would like to see which libraries and syscalls are executed as a consequence of pushing a button of the foreground app.

It is good to know your need. Sadly currently there is no interface in simpleperf_report_lib.py to report tracing data. So probably there is no way to report the recorded syscall data unless you parse perf.data manually. I will work on this as soon as possible.

> simpleperf F 08-25 16:35:34 12714 12714 record.h:158] Check failed: size < 1u << 16 (size=107660, 1u << 16=65536) Aborted

I don't know why this check can fail and I can't reproduce it. Which kernel version are you using (you can show that by `uname -a`)? And the device name?

**Comment by brok85** [comment] 2017-08-25 22:09
It is an LG V10 running android 7.0 with kernel version 3.10.84-g0f4a9fd.

Is it possible to have an event to count how many times a specific library is executed from a specific thread?

**Comment by yabinc** [comment] 2017-08-25 22:30
what do you mean by "how many times a specific library is executed"?
If you mean syscall happen in the library, probably we can do this by tracing raw_syscalls:sys_enter. But the problem is syscalls are usually wrapped by libc.so. So what happens is the library -> libc.so -> syscall in the kernel. So we need to record the callstack (using -g or --call-graph fp) to know if the syscall happens from the library. To record the callstack for tracepoint events, it needs new kernel like v4.4, or the system is after Android OMR1.

If you mean how many times the api functions in a library is called, maybe it is possible by linux uprobe, but it is not supported by simpleperf yet. Maybe you can try https://developer.android.com/studio/profile/systrace.html#app-trace.

**Comment by brok85** [comment] 2017-08-26 05:48
Well i guess that tracing how many times any apis of a certain library are called from a specific thread would be enough for now. So my best bet is with systrace rather than simpleperf?

Thanks

**Comment by yabinc** [comment] 2017-08-28 16:35
I think so. systrace is for tracing kernel/userspace events, and simpleperf is mainly based on sampling.

**Comment by brok85** [comment] 2017-08-28 19:29
Ok. Thanks for the advice. I was particularly interested in doing that with simpleperf because it could be used at runtime while systrace is mostly for collecting info and analyzing them offline. I will look into systrace anyway.

Any luck with my previous problem?

> simpleperf F 08-25 16:35:34 12714 12714 record.h:158] Check failed: size < 1u << 16 (size=107660, 1u << 16=65536) Aborted

Thanks a lot!

**Comment by enh** [comment] 2017-08-28 19:30
(i'm trying to borrow an LG V10 so we can test this.)

**Comment by brok85** [comment] 2017-08-28 20:03
@yabinc and @enh, thanks a lot for all the help you are giving me! 

I will wait for further updates then.

**Comment by DanAlbert** [comment] 2018-03-16 03:03
Did we ever get one?

**Comment by yabinc** [comment] 2018-03-16 18:07
Yes, I got one LG V10, but never checked it. Created bug https://buganizer.corp.google.com/issues/75278602.

**Comment by brok85** [comment] 2018-03-16 20:16
Hi, 
it does not seem to be a problem only of the LG V10. I have just tested a Nexus 5 (Lineage OS-Android 7.1.2), kernel version 3.4.0-gdbd1c67 and gives me the same error with a tracepoint event:

`./simpleperf record -e writeback:writeback_written -p 12288 --duration 5`

`simpleperf F record.h:158] Check failed: size < 1u << 16 (size=68428, 1u << 16=65536) 
Aborted `

I feel that the problem comes up with any tracepoint event on any device, but I didn't test all the devices of course.

**Comment by yabinc** [comment] 2018-03-22 23:39
Sorry for the long delay. I think it should be fixed by https://android-review.googlesource.com/c/platform/system/extras/+/646389.
However, I can't reproduce the problem using the same options you gave. Can you double check the fix by trying the new simpleperf binary in your environment? I uploaded a new binary at https://github.com/yabinc/profiling_data/blob/master/simpleperf.

**Comment by brok85** [comment] 2018-03-23 19:28
Hi @yabinc 
thanks for the update. I think that the binary you uploaded is for arm64, which is good for the LG V10. Unfortunately, I don't have it rooted anymore and cannot test it. Would you be able to compile a binary for 32bit ARMs so I can test it on the Nexus 5? I was getting the same problem on the nexus 5 too, which is rooted.

**Comment by yabinc** [comment] 2018-03-23 19:40
simpleperf binary for 32bit ARM is uploaded at https://github.com/yabinc/profiling_data/blob/master/simpleperf32.

**Comment by brok85** [comment] 2018-03-23 20:01
@yabinc 
thanks for the updated version. I run it but no matter what command I run (e.g., ./simpleperf32.dms list), it always gives me
 
`Illegal instruction`

as response. The only thing I did was to modify the read/write rights of the file (chmod 777 simpleperf32.dms) after I pushed it on the /data/local/tmp folder of the phone. I had to change it otherwise it wouldn't let me run it.

Did I do anything wrong?

**Comment by yabinc** [comment] 2018-03-23 21:25
Sorry, it is because I uploaded simpleperf binaries built for specific devices, which contains instructions only supported on some arm devices. I have fixed this by uploading binaries built for generic_arm. Can you try again?

**Comment by brok85** [comment] 2018-03-25 19:57
@yabinc 
it seems to be working now! Now I can record also tracepoint events without problems!

thanks a lot for the help!

One last question: tracepoint events are kernel generated or PMU generated?

**Comment by yabinc** [comment] 2018-03-26 17:43
tracepoint events are kernel generated, any kernel function can add a custom tracepoint, as in https://www.kernel.org/doc/Documentation/trace/tracepoints.txt.

**Closed** 2018-03-27 18:08 UTC
Labels: simpleperf
