### ISSUE TITLE
Termios tcgetattr() method returns errno 25 whenever trying to set attributes for a terminal in r15, working perfectly fine with r14

### ISSUE THREAD

**Issue by mj8894** [android-ndk/ndk#483] opened 2017-08-17 11:36 UTC
#### Description
We are using NDK to access serial port via native code in our app but with r15 we are getting error [ENOTTY] in the tcsetattr() method of termios, the issue was resolved after degrading to r14. Does someone know why this might be happening.

* NDK Version: r15
* Build system:cmake

**Comment by mj8894** [comment] 2017-08-17 13:31
Update: After some search in the unified headers I found out that TCSANOW isn't defined properly in the inlines method. Hopefully this will be fixed very soon.

**Comment by enh** [comment] 2017-08-17 14:29
Duplicate of https://github.com/android-ndk/ndk/issues/441

**Closed by enh** 2017-08-17 14:29 UTC
