### ISSUE TITLE
Bug in r20's armv7a-linux-androideabi*-clang

### ISSUE THREAD

**Issue by aprelev** [android-ndk/ndk#1010] opened 2019-06-14 15:21 UTC
#### Description
Consider function `foo`:
```C
uint32_t foo(uint32_t const src[static 4]) {
    return
        ((src[0] & 0xff00) >> 8) |
        ((src[1] & 0xff00)) |
        ((src[2] & 0xff00) << 8) |
        ((src[3] & 0xff00) << 16);
}
```
Compiling this function with `armv7a-linux-androideabi*-clang -O1` yields
```asm
foo:
  ldrb    r1, [r0, #1]
  ldrb    r2, [r0, #5]
  ldrb    r3, [r0, #9]
  ldr     r0, [r0, #12]
  orr     r1, r1, r2, lsl #8
  orr     r1, r1, r3, lsl #8
  bic     r0, r0, #255
  orr     r0, r1, r0, lsl #16
  bx      lr
```
while [compiling the same function with LLVM's version](https://godbolt.org/z/amdy_Z) of `clang -O1 -target arm-v7a-androideabi` produces similar albeit different assembly:
```asm
foo:
  ldrb r1, [r0, #1]
  ldrb r2, [r0, #5]
  ldrb r3, [r0, #9]
  lsl r3, r3, #8  ; <<< This shift is missing from NDK's assembly
  orr r1, r1, r2, lsl #8
  orr r1, r1, r3, lsl #8
  ldr r0, [r0, #12]
  bic r0, r0, #255
  orr r0, r1, r0, lsl #16
  bx lr
```
This missing shift is crucial; for `src[] = {0x03020100, 0x07060504, 0x0b0a0908, 0x0f0e0d0c}` faulty version produces `0x0d000d01` while the correct one produces `0x0d090501`.

#### Environment Details

* NDK version: 20.0.5594570.
* Build system: any.
* Host OS: any.

**Comment by stephenhines** [comment] 2019-06-14 16:41
Confirmed that this is broken in the NDK r20 release, but it is fixed in the current compiler (r353983c). @DanAlbert do you want to tag this in some way for r21? The compiler that you are switching to has this fixed.

**Comment by DanAlbert** [comment] 2019-06-14 16:55
> while compiling the same function with LLVM's version of clang

Just to clarify, "LLVM's version of Clang" is what we ship. godbolt just has a newer version than NDK r20. Like @stephenhines says, the fix will be in r21.

**Comment by aprelev** [comment] 2019-06-14 17:17
@DanAlbert, godbolt’s version identifies as 8.0.0, NDK’s — as 8.0.7, that is why I thought NDK provides patches for clang.

**Comment by stephenhines** [comment] 2019-06-14 17:20
So we follow TOT Clang, and our version number has nothing to do with upstream Clang in actuality. TOT Clang switches to the next release number once the prior release goes out. The .7 part indicates that we had ~7 updates to the toolchain during this time period. FWIW, our current Clang identifies as 9.0.4, even though 9.0.0 hasn't been released.

**Comment by aprelev** [comment] 2019-06-14 17:27
I see. Thank you for the clarification.

**Comment by DanAlbert** [comment] 2019-06-14 17:30
(we don't have the update submitted yet, so this bug is still present)

**Comment by ngg** [comment] 2019-07-17 06:58
This bug is fixed upstream in llvm/llvm-project@dd8cd6d (r351310), please cherry-pick this commit to r21 if an older llvm will be used there.

**Comment by DanAlbert** [comment] 2019-07-17 07:04
Can guarantee that whatever ships with r21 will be at least this new. There's already a clang new enough to have this fix in the Android repo, it just isn't what we'll be shipping for r21 because it's already quite old and hasn't had a build that doesn't regress the NDK tests yet, so we're waiting for a fresher/more stable revision.

**Comment by DanAlbert** [comment] 2019-09-04 19:46
Master has r365631, which will be in r21.

**Closed by DanAlbert** 2019-09-04 19:46 UTC
Labels: bug, clang
