### ISSUE TITLE
Clang crashes while compiling SDL for arm

### ISSUE THREAD

**Issue by marijnvdwerf** [android-ndk/ndk#384] opened 2017-05-04 22:38 UTC
#### Description
Clang crashes while compileing `SDL_Wave.c`, but only for arm (non-v7a).
Exception details: https://gist.github.com/marijnvdwerf/13c6f45fcc97c8cc9ca9d9324d86830c
built using https://github.com/marijnvdwerf/openrct2-dependencies-android (`./build.sh`)

#### Environment Details
* NDK Version:14.1.3816874
* Build sytem: dmake
* Host OS: Mac
* Compiler: Clang
* ABI: arm
* STL: C++
* NDK API level: 16

**Comment by DanAlbert** [comment] 2017-05-05 02:30
Hmm, something isn't quite right with that test case. It fails because it's trying to install something to `/usr/lib`. I'm guessing it's depending on an environment variable that I don't have set?

**Comment by DanAlbert** [comment] 2017-05-05 02:38
All I was going to do is check that the test case passes with the new Clang I synced to the other day. If it would be easier than fixing the test case, you can actually pull a build straight from our build servers: https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md

Either master or ndk-r15-release should be fine for testing this. They're more or less identical right now.

**Comment by 1bsyl** [comment] 2017-05-18 08:37
Seem a duplicate of #259

**Closed** 2017-05-18 15:16 UTC
