### ISSUE TITLE
Excessive alignment hint for ARM NEON load/store produced by clang toolchain?

### ISSUE THREAD

**Issue by scottcjt** [android-ndk/ndk#640] opened 2018-02-18 09:33 UTC
#### Description

For the following code:

```c++
#include <arm_neon.h>

void foo(float32x4_t *dst, const float *src) {
  *dst = vld1q_f32(src);
}
```

Switches:

```
-target armv7-none-linux-androideabi \
-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mfpu=neon -O3
```

It seems like clang (tried r15 and r16) will produce 128-bits alignment hint while old gcc from r12 only requires 64 bits. Is it intended behavior? It causes NEON programs get **BUS\_ADRALN** on Android platforms prior to 6.0, where a float32x4_t seems not 128-bits aligned.

An actual scenario is `tensorflow/tensorflow/contrib/lite/kernels/internal/optimized/neon_tensor_utils.cc:NeonMatrixBatchVectorMultiplyAccumulate` in TensorFlow Lite.

Below are some environment info:

clang -v:

```
Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: armv7-none-linux-android
Thread model: posix
```

Host: OSX 10.13
ABI/STL: not used
APILevel: not specified, found this in command-line "-D __ANDROID_API__=14"

**Comment by rprichard** [comment] 2018-02-21 04:44
Using `alignof(float32x4_t)`, it's apparent that GCC thinks the type is 8-byte aligned, whereas Clang thinks it's 16-byte aligned. I see that Clang is willing to use 128-bit-hinted Neon instructions, which fail if the value isn't sufficiently aligned.

If I understand correctly, the TensorFlow Lite code would hit a bus error if it were compiled with a current NDK's Clang and then run on an older platform.

I'm able to reproduce something like that using a heap allocation on K. A 16-byte heap allocation is sometimes only 8-byte aligned on K. When it's 8, the app can hit the bus error on a 128-hinted instruction like:
```
    vst1.64 {d16, d17}, [r5:128]
```

**Comment by stephenhines** [comment] 2018-02-21 05:43
Android's vectors are more aligned than GCC's vectors. This is a deliberate ABI breakage, as ext_vector (how float32x4_t is defined) is non-portable, in any case. You must ensure that your float32x4_t allocations are 16-byte aligned.

**Comment by rprichard** [comment] 2018-02-21 06:28
I'm wondering how/whether TensorFlow deals with this situation then. Maybe it's using GCC?

https://github.com/tensorflow/tensorflow/blob/ddef51c1c93f66989ac7a88b88b89f5b2a9df599/tensorflow/contrib/android/cmake/build.gradle#L25

If it switched to Clang, presumably the code the reporter referenced is going to segfault? e.g. It simply allocates floatx32_t using `new[]` ([[link]](https://github.com/tensorflow/tensorflow/blob/00986f1d75211fcdc3ad47d949ea523c450e802d/tensorflow/contrib/lite/kernels/internal/optimized/neon_tensor_utils.cc#L40-L43
))

```c++
  // The arrays used to cache the vector.
  float32x4_t* vector_cache_float32x4 =
      new float32x4_t[(m_cols / kFloatWeightsPerNeonLane) *
                      sizeof(float32x4_t)];
```

It could replace this code with a call to `[posix_]memalign`. I see an `AlignedMalloc` function [[here]](https://github.com/tensorflow/tensorflow/blob/57529c06f855985fe770b17c7c1c19e1a750ed2b/tensorflow/core/platform/posix/port.cc#L77). Maybe that's what it should use.

Maybe it's feasible to configure the NDK Clang to assume at most 64-bit alignment for Neon instructions? If the targeted Android API were new enough (23?), it could assume the full alignment.

**Comment by rprichard** [comment] 2018-02-21 06:32
FWIW: Here's a review that touched the vector alignment setting for ARM32 Clang. It was originally going to affect Android (along with every other target), but was modified to leave Android's vector alignment at 128 bits. https://reviews.llvm.org/D33205.

**Comment by stephenhines** [comment] 2018-02-21 06:34
No, the NDK clang *CANNOT* use 64-bit alignment for float32x4_t, or any other 128-bit type. We crossed that bridge years ago, and we have RenderScript code (and other prebuilts) that require the full 128-bit alignment. I think that memalign is the best way to make progress here. I am not sure what TensorFlow is doing exactly, but perhaps we can sync up with Jean-Luc to see what they know about it. Their team (RenderScript) is also maintaining the core user of the 128-bit alignment requirement on these types.

**Comment by rprichard** [comment] 2018-02-21 07:29
> No, the NDK clang CANNOT use 64-bit alignment for float32x4_t, or any other 128-bit type. ...

I wasn't suggesting changing the alignment of `float32x4_t`. The idea was to leave `float32x4_t` at 128 bits but avoid assuming that an address of `float32x4_t*` type is aligned when the only evidence is the type.

> I think that memalign is the best way to make progress here.

Yeah, that looks like an easy fix for TensorFlow. I searched the TensorFlow project for uses of `float32x4_t`, and all but the one are allocating them on the stack, which will properly align them to 128 bits.

**Comment by stephenhines** [comment] 2018-02-21 07:52
I found 2 in our checkout of external/tensorflow :

```
external/tensorflow/tensorflow/contrib/lite/kernels/internal/optimized/neon_tensor_utils.cc:41:7: error: type 'float32x4_t' (vector of 4 'float32_t' values) requires 16 bytes of alignment and the default allocator only guarantees 8 bytes [-Werror,-Wover-aligned]
      new float32x4_t[(m_cols / kFloatWeightsPerNeonLane) *
      ^
external/tensorflow/tensorflow/contrib/lite/kernels/internal/optimized/neon_tensor_utils.cc:171:7: error: type 'float32x4_t' (vector of 4 'float32_t' values) requires 16 bytes of alignment and the default allocator only guarantees 8 bytes [-Werror,-Wover-aligned]
      new float32x4_t[(v_size / kFloatWeightsPerNeonLane) *
      ^
2 errors generated.
```

I am experimenting with -Werror=over-aligned for a different bug, which has already caused some problems in Android. I'm probably just going to suppress this error for now, but we should be able to get this cleaned up and tested properly.

**Comment by scottcjt** [comment] 2018-02-21 08:27
An armv7a crash report FYI:

```
I/DEBUG   (  258): signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 76ead008
I/DEBUG   (  258):     r0 76ead008  r1 00000000  r2 00000004  r3 76ca0cd0
I/DEBUG   (  258):     r4 00000640  r5 fffffff0  r6 76ead008  r7 00000320
I/DEBUG   (  258):     r8 00000640  r9 76ca0cc0  sl 00000000  fp 77595940
I/DEBUG   (  258):     ip 76ca4b48  sp 775958d8  lr 00000320  pc 740b8bb8  cpsr 800f0010
I/DEBUG   (  258):     d0  c019031900000000  d1  c02de3b4c00d31e3
I/DEBUG   (  258):     d2  c020403cc026de2c  d3  c026de2cbff8ee44
I/DEBUG   (  258):     d4  c01a75c5c036ea2a  d5  c036ea2ac015b86e
I/DEBUG   (  258):     d6  c0386958c0249798  d7  c01ec685c03d6366
I/DEBUG   (  258):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  258):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  258):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  258):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  258):     d16 3ced29553d7a2361  d17 bf04bf48be91786d
I/DEBUG   (  258):     d18 bf216043bf63ea94  d19 bf6abb1ebfc3db3a
I/DEBUG   (  258):     d20 bfdf953cc0037d3c  d21 bfc9a83abf50cdb4
I/DEBUG   (  258):     d22 bd394f60bf37d95c  d23 bfedbf83bfc7cd4e
I/DEBUG   (  258):     d24 0000000000000000  d25 0000000000000000
I/DEBUG   (  258):     d26 0000000000000000  d27 0000000400000004
I/DEBUG   (  258):     d28 0000000000000000  d29 0000000000000000
I/DEBUG   (  258):     d30 0000000400000004  d31 0000000400000004
I/DEBUG   (  258):     scr 28000013

Offending PC:

   b8ba8:       e0806102        add     r6, r0, r2, lsl #2
   b8bac:       f4630a8d        vld1.32 {d16-d17}, [r3]!
   b8bb0:       e2822004        add     r2, r2, #4
   b8bb4:       e152000e        cmp     r2, lr
   b8bb8:       f4460aef        vst1.64 {d16-d17}, [r6 :128]
   b8bbc:       bafffff9        blt     b8ba8 <_ZN6tflite12tensor_utils39NeonMatrixBatchVectorMultiplyAccumulateEPKfiiS2_iPfi+0x104>
```

This crash report is generated on Android 4.4. As you expect, heap allocated memory (in `r6`) is not always 16-bytes aligned.

It sounds like this breakage happened some versions before, so it's impossible to "fix" it again. If current compiler behavior is decided to be kept, fixing TensorFlow sounds reasonable.

**Comment by DanAlbert** [comment] 2018-03-15 22:57
Sounds like nothing to do on the NDK side of this. Closing.

**Closed by DanAlbert** 2018-03-15 22:57 UTC

**Comment by bjacob** [comment] 2020-06-03 20:08
For the record, defining float32x4_t to have 128-bit alignment seems like a x86-ism. Historically on x86 unaligned vector loads/stores have been substantially slower than aligned ones. On the ARM architecture on the other hand, this hasn't been an issue. Instead, the CPU handles unaligned vector accesses internally so that software does not need to be more convoluted. 

ARM32 retained the ability to decorate instructions with alignment qualifiers, for marginal latency gains that don't make a significant performance impact in optimized code (which by definition is written to hide minor latency differences in memory accesses). In ARM64 these are gone altogether -- there literally are only unaligned memory access instructions in ARM64 NEON.

It's too bad that this Android/Clang aspect is nullifying this progress, especially seeing how much more important the ARM architecture is than x86 to Android.

**Comment by enh-google** [comment] 2020-06-03 20:29
as explained above, this is just something we're stuck with for app compat reasons: "No, the NDK clang CANNOT use 64-bit alignment for float32x4_t, or any other 128-bit type. We crossed that bridge years ago, and we have RenderScript code (and other prebuilts) that require the full 128-bit alignment."

we're pretty cool, but we can't change the past.

**Comment by bjacob** [comment] 2020-06-03 21:02
I don't think we disagree on anything - and thanks for the interesting historical bit about it originating in renderscript.
